// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `adapter/info`.
 */
export type AdapterInfoParams = { 
/**
 * Storage handle. Defaults to "main" (the shared DB). Accepts the legacy
 * `dbPath` field name as an alias.
 */
handle?: string, };
