//! String templates for the files `generate/module` emits.
//!
//! Pure functions: input is `GenerateModuleParams`, output is the
//! rendered file contents. No I/O lives here — the caller in
//! [`super::GeneratorModule::generate_module_inner`] does the writes.
//! That keeps the templates testable in isolation and the I/O paths
//! easy to swap (e.g., a future "dry run" mode that prints rather than
//! writes).
//!
//! # What gets emitted
//!
//! For every `generate/module` call, four files land in the module's
//! directory:
//!
//! | File | Template fn | Purpose |
//! |---|---|---|
//! | `mod.rs` | [`mod_rs_template`] | `ServiceModule` impl with envelope-based dispatch + concurrency test scaffold |
//! | `types.rs` | [`types_rs_template`] | One `CommandRequest<P>` / `CommandResponse<T>` pair per declared command, with `#[derive(TS)]` |
//! | `DESIGN.md` | [`design_md_template`] | Per-module design doc skeleton (Role / Command surface / State / Concurrency / Migration notes / Kinks) |
//! | `README.md` | [`readme_template`] | Author-facing summary + wire-up reminder + cross-refs |
//!
//! Each template follows the canonical shape in
//! [COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md §3 (Module Design Template)](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md).

use super::struct_name;
use super::types::GenerateModuleParams;

/// Render the canonical `mod.rs` template for a new module.
///
/// The output is a compilable Rust file the moment the caller wires
/// it into the parent `modules/mod.rs`. It:
///
/// - declares a `pub struct <Name>Module` with `ServiceModule` impl,
/// - parses every command via `CommandRequest::from_value` + dispatches
///   to a typed `&self` handler method,
/// - materializes each handler's result via
///   `CommandResponse::ok(...).into_command_result()`,
/// - includes a test-only `with_executor` constructor so concurrency
///   tests can inject a stubbed dispatch chain,
/// - opts into the per-resource lock scaffold when
///   `params.stateful == true` (per
///   [field manual §4.1](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md)),
/// - emits a `#[cfg(test)] mod tests` block with a multi-thread
///   concurrency stress-test skeleton primed for the author to
///   extend.
pub fn mod_rs_template(params: &GenerateModuleParams) -> String {
    let name = &params.name;
    let description = &params.description;
    let struct_prefix = struct_name(name);
    let priority_variant = params.priority.as_variant_str();
    let command_prefixes = render_command_prefixes(name, &params.commands);
    let event_subscriptions = render_string_array(&params.events_subscribed);

    let typed_imports = render_typed_imports(name, &params.commands);
    let stateful_imports = if params.stateful {
        "use dashmap::DashMap;\n"
    } else {
        ""
    };
    let resource_state_decl = render_resource_state_decl(params.stateful);
    let stateful_field = render_stateful_field(params.stateful);
    let stateful_init = render_stateful_init(params.stateful);
    let stateful_helper = render_stateful_helper(params.stateful, &struct_prefix);
    let handler_methods = render_handler_methods(name, &params.commands);
    let command_dispatch_arms = render_command_dispatch_arms(name, &params.commands);
    let events_published_doc = render_published_events_doc(&params.events_published);
    let concurrency_test = render_concurrency_test(name, &struct_prefix, params.stateful);

    format!(
        r#"//! {description}
//!
//! Auto-generated by `@continuum-modules/generator` via the
//! `generate/module` command. Fill in real command handlers in
//! place of the `not yet implemented` stubs below.
//!
//! Commands provided: {commands_csv}
//! Events subscribed: {events_sub_csv}
//! Events published:  {events_pub_csv}
//!
//! # References
//!
//! - [docs/architecture/MODULE-ARCHITECTURE.md](../../../../../../docs/architecture/MODULE-ARCHITECTURE.md) — module pattern doctrine
//! - [docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md) — author's field manual
//! - `DESIGN.md` (next to this file) — per-module design skeleton
//!
//! # Wire-up
//!
//! 1. Add `pub mod {name};` to `core/continuum-core/src/modules/mod.rs`
//! 2. Register `Arc::new({struct_prefix}Module::new())` at runtime startup
//! 3. Replace each handler's `not yet implemented` body with real logic
{events_published_doc}

use std::sync::{{Arc, RwLock}};

use async_trait::async_trait;
{stateful_imports}use serde_json::Value;

use crate::runtime::{{
    command_executor::{{self, CommandExecutor}},
    CommandRequest, CommandResponse, CommandResult, ModuleConfig, ModulePriority, ServiceModule,
}};

pub mod types;
{typed_imports}
{resource_state_decl}
/// The `{name}` module. Owns the `{name}/*` command surface.
pub struct {struct_prefix}Module {{
    /// Optional executor override for tests — inject a registry with
    /// stub modules so cross-module calls are observable + assertable
    /// (per [field manual §3](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md)).
    /// Production uses the kernel-global at call time.
    executor_override: RwLock<Option<Arc<CommandExecutor>>>,
{stateful_field}}}

impl {struct_prefix}Module {{
    /// Production constructor — uses the kernel-global executor.
    pub fn new() -> Self {{
        Self {{
            executor_override: RwLock::new(None),
{stateful_init}        }}
    }}

    /// Test-only constructor — inject an explicit executor so each
    /// test owns its dispatch chain without trampling the global
    /// `OnceLock`. See field manual §4.2.
    #[cfg(test)]
    pub fn with_executor(executor: Arc<CommandExecutor>) -> Self {{
        Self {{
            executor_override: RwLock::new(Some(executor)),
{stateful_init}        }}
    }}

    /// Resolve the executor for the current call. Tests get the
    /// injected one; production gets the kernel-global.
    #[allow(dead_code)]
    fn executor(&self) -> Arc<CommandExecutor> {{
        if let Some(ex) = self
            .executor_override
            .read()
            .unwrap_or_else(|e| e.into_inner())
            .clone()
        {{
            return ex;
        }}
        command_executor::executor()
    }}
{stateful_helper}
{handler_methods}}}

impl Default for {struct_prefix}Module {{
    fn default() -> Self {{
        Self::new()
    }}
}}

#[async_trait]
impl ServiceModule for {struct_prefix}Module {{
    fn config(&self) -> ModuleConfig {{
        ModuleConfig {{
            name: "{name}",
            priority: ModulePriority::{priority_variant},
            command_prefixes: &[{command_prefixes}],
            event_subscriptions: &[{event_subscriptions}],
            needs_dedicated_thread: false,
            max_concurrency: 0,
            tick_interval: None,
        }}
    }}

    async fn initialize(
        &self,
        _ctx: &crate::runtime::ModuleContext,
    ) -> Result<(), String> {{
        Ok(())
    }}

    async fn handle_command(
        &self,
        command: &str,
        params: Value,
    ) -> Result<CommandResult, String> {{
        let _ = &params; // silence unused warning when no commands
        match command {{
{command_dispatch_arms}
            other => Err(format!(
                "{{other}}: not handled by `{name}` module (auto-generated stub)"
            )),
        }}
    }}

    fn as_any(&self) -> &dyn std::any::Any {{
        self
    }}
}}
{concurrency_test}"#,
        description = description,
        struct_prefix = struct_prefix,
        name = name,
        priority_variant = priority_variant,
        command_prefixes = command_prefixes,
        event_subscriptions = event_subscriptions,
        typed_imports = typed_imports,
        stateful_imports = stateful_imports,
        resource_state_decl = resource_state_decl,
        stateful_field = stateful_field,
        stateful_init = stateful_init,
        stateful_helper = stateful_helper,
        handler_methods = handler_methods,
        command_dispatch_arms = command_dispatch_arms,
        events_published_doc = events_published_doc,
        concurrency_test = concurrency_test,
        commands_csv = csv_or_none(&params.commands),
        events_sub_csv = csv_or_none(&params.events_subscribed),
        events_pub_csv = csv_or_none(&params.events_published),
    )
}

/// Render the canonical `types.rs` template for a new module.
///
/// Emits one `<CmdName>Params` + `<CmdName>Result` pair per declared
/// command, each with `#[derive(TS)]` exporting to
/// `protocol/typescript/<name>/`. Authors fill in real fields; the
/// scaffolded structs compile as-is (empty bodies).
pub fn types_rs_template(params: &GenerateModuleParams) -> String {
    let name = &params.name;
    let mut body = String::new();

    body.push_str(&format!(
        r#"//! Typed params + result for the {name} module's commands.
//!
//! Every wire type carries `#[derive(TS)]` and exports to
//! `protocol/typescript/{name}/` so TS consumers get auto-generated
//! bindings — no hand-written duplicate types across the
//! Rust ↔ TS boundary.
//!
//! Authors fill in real fields on each `<CmdName>Params` /
//! `<CmdName>Result` pair. The empty bodies compile as-is so the
//! scaffold lands green; replace each TODO with the real wire shape
//! per [COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md §3](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md).
//!
//! # ts-rs annotation rules
//!
//! - `#[ts(type = "string")]` on `Uuid` fields — wire format is the
//!   UUID's canonical string
//! - `#[ts(optional, ...)]` on `Option<T>` fields
//! - `#[serde(skip_serializing_if = "Option::is_none")]` on optional
#[ts(optional)]
//!   output fields so absent != null on the wire
//! - `rename_all = "camelCase"` on every struct (already set below)

use serde::{{Deserialize, Serialize}};
use ts_rs::TS;
"#
    ));

    if params.commands.is_empty() {
        body.push_str(
            "\n// No commands declared yet — author adds Params/Result pairs as commands land.\n",
        );
        return body;
    }

    for command in &params.commands {
        let type_stem = command_to_type_stem(name, command);
        body.push_str(&format!(
            r#"
// ── {command} ───────────────────────────────────────────────────

#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../protocol/typescript/{name}/{type_stem}Params.ts")]
#[serde(rename_all = "camelCase")]
pub struct {type_stem}Params {{
    // TODO(author): add typed fields for the `{command}` params.
}}

#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../protocol/typescript/{name}/{type_stem}Result.ts")]
#[serde(rename_all = "camelCase")]
pub struct {type_stem}Result {{
    // TODO(author): add typed fields for the `{command}` result.
}}
"#
        ));
    }
    body
}

/// Render the per-module `DESIGN.md` skeleton. Authors replace the
/// TODO bullets with real content as they fill in handlers. The
/// section headers are required so future maintainers find the
/// contract quickly.
pub fn design_md_template(params: &GenerateModuleParams) -> String {
    let name = &params.name;
    let description = &params.description;

    let commands_table = if params.commands.is_empty() {
        "_No commands declared yet._".to_string()
    } else {
        let mut s =
            String::from("| Command | Params type | Result type | Notes |\n|---|---|---|---|\n");
        for command in &params.commands {
            let type_stem = command_to_type_stem(name, command);
            s.push_str(&format!(
                "| `{command}` | `{type_stem}Params` | `{type_stem}Result` | TODO |\n"
            ));
        }
        s
    };

    let events_pub_md = if params.events_published.is_empty() {
        "_None._".to_string()
    } else {
        let mut s = String::new();
        for e in &params.events_published {
            s.push_str(&format!("- `{e}` — TODO describe payload + trigger\n"));
        }
        s
    };

    let state_section = if params.stateful {
        "Per-resource state stored in `DashMap<ResourceId, Arc<tokio::sync::Mutex<ResourceState>>>`. The per-resource mutex serializes concurrent access on the same resource; different resources stay parallel via DashMap's per-shard locking. See field manual §4.1.\n\nTODO(author): document the ResourceState fields and lifecycle (when resources are inserted, when evicted)."
    } else {
        "Stateless. The module holds no mutable state across calls (apart from the test-only `executor_override`).\n\nIf this changes, set `stateful: true` in the generator spec and re-scaffold — or follow the field manual §4.1 pattern manually."
    };

    let concurrency_section = if params.stateful {
        "Per-resource lock pattern (field manual §4.1):\n\n- Different resources stay fully parallel via DashMap shards.\n- Same-resource concurrent calls serialize via `tokio::sync::Mutex` held across the `.await`.\n- Multi-thread stress test in `mod.rs::tests::handlers_serialize_per_resource_under_concurrent_load` pins the invariant.\n\nTODO(author): list invariants the per-resource lock protects (e.g., monotone counters, ordering)."
    } else {
        "Module is stateless; concurrency-safe by construction. The scaffolded multi-thread stress test in `mod.rs::tests::handlers_under_concurrent_load` smoke-tests typed-envelope routing under load.\n\nIf this module gains stateful handlers later, re-scaffold with `stateful: true` and follow field manual §4."
    };

    format!(
        r#"# `{name}` module — Design

> **Author note**: this file is scaffolded by `generate/module`.
> Replace each `TODO` as you fill in handlers. Section headers are
> required so future maintainers find the contract quickly.
>
> Canonical reference: [COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md).

## Role

Which of the three primitives does this module serve?
(**Commands** / **Events** / **Persona** — see field manual §1.)

> _{description}_

TODO(author): one-paragraph summary of the module's role in the
larger system. Which persona workflows depend on it? What does it
provide that no other module does?

## Command surface

{commands_table}

## Cross-module dependencies

Which other modules does this one call via `executor.execute_json(...)`?

- TODO(author): list each, with a one-line note on what's expected

## State model

{state_section}

## Events emitted

{events_pub_md}

## Concurrency contract

{concurrency_section}

## Migration notes

If this module replaces a TS implementation, what did the rethink
change vs the TS shape?
(See field manual §5 — *"rethink, don't port"*.)

- TODO(author)

## Kinks found

Document any concurrency / wire / lifecycle kinks the migration
surfaced. Substrate primitives get refined from these — flag any
that suggest a follow-up substrate refinement.

- TODO(author)
"#,
        name = name,
        description = description,
        commands_table = commands_table,
        state_section = state_section,
        events_pub_md = events_pub_md,
        concurrency_section = concurrency_section,
    )
}

/// Render the README the generator drops into the new module's
/// directory. Captures the same metadata as the mod.rs docstring in
/// Markdown form, plus the explicit wire-up step the author still
/// needs to perform manually, plus cross-refs to the field manual +
/// the scaffolded `DESIGN.md`.
pub fn readme_template(params: &GenerateModuleParams) -> String {
    let name = &params.name;
    let description = &params.description;
    let struct_prefix = struct_name(name);

    let commands_md = render_md_list("Commands", &params.commands);
    let events_sub_md = render_md_list("Events subscribed", &params.events_subscribed);
    let events_pub_md = render_md_list("Events published", &params.events_published);

    let stateful_note = if params.stateful {
        "\n**Stateful**: this module holds per-resource state under a per-resource lock. \
         See `DESIGN.md` §Concurrency contract."
    } else {
        ""
    };

    format!(
        r#"# `{name}` module

{description}{stateful_note}

Auto-generated by `@continuum-modules/generator`. Files in this directory:

- `mod.rs` — `ServiceModule` impl + dispatch + concurrency test scaffold
- `types.rs` — typed `Params` / `Result` for every declared command
- `DESIGN.md` — per-module design doc (fill in as handlers land)

References:
- [docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md) — author's field manual
- [docs/architecture/MODULE-ARCHITECTURE.md](../../../../../../docs/architecture/MODULE-ARCHITECTURE.md) — doctrine

## Contract

{commands_md}

{events_sub_md}

{events_pub_md}

## Author's next step

The scaffold compiles as soon as it's wired into the parent module:

```rust
// core/continuum-core/src/modules/mod.rs
pub mod {name};
```

And registered at runtime startup:

```rust
runtime.register(Arc::new({struct_prefix}Module::new()));
```

After that:
1. Fill in real handler bodies in `mod.rs` (replace each `Err("...not yet implemented...")`)
2. Add typed fields to each `Params` / `Result` in `types.rs`
3. Document the module's contract in `DESIGN.md`
4. Extend the concurrency stress test in `mod.rs::tests` to call real handlers
"#,
        name = name,
        description = description,
        stateful_note = stateful_note,
        struct_prefix = struct_prefix,
        commands_md = commands_md,
        events_sub_md = events_sub_md,
        events_pub_md = events_pub_md,
    )
}

// ── helpers ──────────────────────────────────────────────────────────

/// Render the `command_prefixes` array literal. Strategy: emit each
/// declared command exactly (e.g., `"chat/send"`) AND the module's
/// `name/` prefix so future commands under the same prefix route
/// through this module without re-running the generator. If the
/// caller declares no commands, the prefix alone is enough.
fn render_command_prefixes(name: &str, commands: &[String]) -> String {
    let mut entries: Vec<String> = commands.iter().map(|c| format!("\"{c}\"")).collect();
    let prefix = format!("\"{name}/\"");
    if !entries.contains(&prefix) {
        entries.push(prefix);
    }
    entries.join(", ")
}

fn render_string_array(items: &[String]) -> String {
    items
        .iter()
        .map(|s| format!("\"{s}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Generate the `use types::{...}` line at the top of mod.rs,
/// importing each declared command's typed Params + Result.
fn render_typed_imports(name: &str, commands: &[String]) -> String {
    if commands.is_empty() {
        return String::new();
    }
    let mut types: Vec<String> = Vec::with_capacity(commands.len() * 2);
    for command in commands {
        let stem = command_to_type_stem(name, command);
        types.push(format!("{stem}Params"));
        types.push(format!("{stem}Result"));
    }
    format!("use types::{{{}}};\n", types.join(", "))
}

/// `ResourceState` struct declaration. Only emitted when stateful.
fn render_resource_state_decl(stateful: bool) -> String {
    if !stateful {
        return String::new();
    }
    String::from(
        r#"
/// Per-resource state managed by this module. Authors add the fields
/// each handler reads/mutates. Wrapped in `tokio::sync::Mutex` inside
/// the module's per-resource lock map so concurrent access on the
/// same resource serializes (different resources stay parallel).
#[derive(Debug, Default)]
struct ResourceState {
    // TODO(author): add per-resource fields here.
}
"#,
    )
}

/// Per-resource lock map field on the module struct. Only emitted
/// when stateful.
fn render_stateful_field(stateful: bool) -> String {
    if !stateful {
        return String::new();
    }
    String::from(
        "\n    /// Per-resource locks. Different ids stay parallel (DashMap\n    /// shards); same id serializes via `tokio::sync::Mutex` held\n    /// across the read-then-async-then-write window in handlers.\n    /// See [field manual §4.1](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md).\n    resource_locks: DashMap<String, Arc<tokio::sync::Mutex<ResourceState>>>,\n",
    )
}

/// Per-resource lock map initializer in the `new` / `with_executor`
/// bodies. Only emitted when stateful.
fn render_stateful_init(stateful: bool) -> String {
    if !stateful {
        return String::new();
    }
    String::from("            resource_locks: DashMap::new(),\n")
}

/// `resource_lock(&self, id)` get-or-create helper. Only emitted
/// when stateful.
fn render_stateful_helper(stateful: bool, _struct_prefix: &str) -> String {
    if !stateful {
        return String::new();
    }
    String::from(
        r#"
    /// Get-or-create the per-resource lock for `id`. `DashMap::entry`
    /// is atomic within a shard, so concurrent callers either find
    /// the same `Arc` (one wins the slot, others clone) or both
    /// create distinct `Arc`s for distinct ids (different shards
    /// stay parallel). See field manual §4.1.
    #[allow(dead_code)]
    fn resource_lock(&self, id: &str) -> Arc<tokio::sync::Mutex<ResourceState>> {
        self.resource_locks
            .entry(id.to_string())
            .or_insert_with(|| Arc::new(tokio::sync::Mutex::new(ResourceState::default())))
            .clone()
    }
"#,
    )
}

/// One typed `&self` handler method per declared command. Each body
/// is a stub that errors with `not yet implemented` so the scaffold
/// compiles + the author fills in real logic afterwards.
fn render_handler_methods(name: &str, commands: &[String]) -> String {
    if commands.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    for command in commands {
        let stem = command_to_type_stem(name, command);
        let handler = command_to_handler_name(name, command);
        s.push_str(&format!(
            r#"
    /// Typed handler for `{command}`. Replace the `Err` body with
    /// real logic; the typed envelope wiring in `handle_command` is
    /// already in place.
    #[allow(dead_code, unused_variables)]
    pub async fn {handler}(
        &self,
        params: {stem}Params,
    ) -> Result<{stem}Result, String> {{
        Err("{command}: not yet implemented in this scaffolded module".to_string())
    }}
"#
        ));
    }
    s
}

/// Dispatch arms for `handle_command`. Each arm parses the typed
/// envelope, calls the typed handler method, materializes the
/// typed response.
fn render_command_dispatch_arms(name: &str, commands: &[String]) -> String {
    if commands.is_empty() {
        return String::new();
    }
    commands
        .iter()
        .map(|command| {
            let stem = command_to_type_stem(name, command);
            let handler = command_to_handler_name(name, command);
            format!(
                "            \"{command}\" => {{\n                \
                 let req = CommandRequest::<{stem}Params>::from_value(params)?;\n                \
                 let result = self.{handler}(req.params).await?;\n                \
                 CommandResponse::ok(result).into_command_result()\n            \
                 }}"
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_published_events_doc(events: &[String]) -> String {
    if events.is_empty() {
        return String::new();
    }
    let mut s = String::from("//!\n//! Documented published events (no runtime wiring; \n//! publishers emit at their own pace):\n");
    for e in events {
        s.push_str(&format!("//!   - `{e}`\n"));
    }
    s
}

/// Multi-thread concurrency stress test scaffold per field manual §4.2.
/// When stateful, also includes a per-resource serialization sanity
/// check.
fn render_concurrency_test(name: &str, struct_prefix: &str, stateful: bool) -> String {
    let extra_stateful_test = if stateful {
        format!(
            r#"
    /// Concurrent handlers on DIFFERENT resource ids must stay
    /// parallel; on the SAME id must serialize via the per-resource
    /// mutex. This test pins the parallel-different-ids half — the
    /// serializes-same-id half should be added once a real handler
    /// is in place.
    /// See field manual §4.1.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn resource_locks_stay_parallel_across_distinct_ids() {{
        let module = Arc::new({struct_prefix}Module::new());
        let mut tasks = Vec::new();
        for i in 0..16 {{
            let module = module.clone();
            tasks.push(tokio::spawn(async move {{
                // Acquiring distinct ids must not block each other.
                let lock = module.resource_lock(&format!("resource-{{i}}"));
                let _guard = lock.lock().await;
                // TODO(author): exercise the real handler under the lock.
            }}));
        }}
        for t in tasks {{
            t.await.expect("task must not panic");
        }}
        // 16 distinct ids ⇒ 16 distinct lock entries.
        assert_eq!(module.resource_locks.len(), 16);
    }}
"#
        )
    } else {
        String::new()
    };

    format!(
        r#"
// ════════════════════════════════════════════════════════════════
// Tests
// ════════════════════════════════════════════════════════════════
//
// The concurrency stress test below is mandatory per
// [field manual §4.2](../../../../../../docs/architecture/COMMAND-INFRASTRUCTURE-FIELD-MANUAL.md).
// Single-threaded `#[tokio::test]` would silently serialize even
// genuinely racy code and pass; `flavor = "multi_thread",
// worker_threads = 4` actually preempts across OS threads so race
// windows open.
//
// Extend the test as you fill in real handler bodies — assert no
// losses, distinct ids, per-call ordering invariants, etc.

#[cfg(test)]
mod tests {{
    use super::*;

    #[tokio::test]
    async fn config_advertises_module_name_and_prefix() {{
        let m = {struct_prefix}Module::new();
        let cfg = m.config();
        assert_eq!(cfg.name, "{name}");
        assert!(
            cfg.command_prefixes.iter().any(|p| p == &"{name}/"),
            "module's own `name/` prefix must appear in command_prefixes"
        );
    }}

    /// Multi-thread concurrency smoke test. Scaffolded per field
    /// manual §4.2 — extend as real handlers land.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn handlers_under_concurrent_load() {{
        const PARALLEL: usize = 16;
        let module = Arc::new({struct_prefix}Module::new());
        let mut tasks = Vec::with_capacity(PARALLEL);
        for _ in 0..PARALLEL {{
            let module = module.clone();
            tasks.push(tokio::spawn(async move {{
                // TODO(author): replace with a real handler call once
                // the scaffold is filled in. The Arc<Module> here is
                // the production multi-persona usage pattern.
                module.config()
            }}));
        }}
        for t in tasks {{
            t.await.expect("task must not panic");
        }}
    }}
{extra_stateful_test}}}
"#
    )
}

fn render_md_list(title: &str, items: &[String]) -> String {
    if items.is_empty() {
        format!("## {title}\n\n_None declared._")
    } else {
        let mut s = format!("## {title}\n\n");
        for it in items {
            s.push_str(&format!("- `{it}`\n"));
        }
        s
    }
}

fn csv_or_none(items: &[String]) -> String {
    if items.is_empty() {
        "(none)".to_string()
    } else {
        items.join(", ")
    }
}

/// Convert a command like `chat/poll` (with module name `chat`) into
/// the canonical PascalCase type stem `Poll`. For nested commands
/// like `chat/analyze/findings`, produces `AnalyzeFindings`.
///
/// Strategy: strip the leading `<module>/` if present, then convert
/// the remainder to PascalCase (splitting on `/`, `-`, `_`).
fn command_to_type_stem(module_name: &str, command: &str) -> String {
    let stripped = command
        .strip_prefix(&format!("{module_name}/"))
        .unwrap_or(command);
    pascal_case(stripped)
}

/// Convert a command like `chat/poll` into the canonical snake_case
/// handler name `handle_poll`. For nested commands like
/// `chat/analyze/findings`, produces `handle_analyze_findings`.
fn command_to_handler_name(module_name: &str, command: &str) -> String {
    let stripped = command
        .strip_prefix(&format!("{module_name}/"))
        .unwrap_or(command);
    let snake = stripped.replace(['/', '-'], "_");
    format!("handle_{snake}")
}

fn pascal_case(s: &str) -> String {
    s.split(['/', '-', '_'])
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<String>()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::modules::generator::types::PrioritySpec;

    fn sample_params() -> GenerateModuleParams {
        GenerateModuleParams {
            name: "demo".into(),
            description: "Sample module for template tests".into(),
            commands: vec!["demo/echo".into(), "demo/ping".into()],
            events_subscribed: vec!["data:demo_items:created".into()],
            events_published: vec!["demo:event:emitted".into()],
            priority: PrioritySpec::Normal,
            force: false,
            stateful: false,
        }
    }

    // ── mod.rs template ──────────────────────────────────────────────

    #[test]
    fn mod_rs_contains_struct_definition_and_trait_impl() {
        let s = mod_rs_template(&sample_params());
        assert!(s.contains("pub struct DemoModule"));
        assert!(s.contains("impl ServiceModule for DemoModule"));
        assert!(s.contains("ModulePriority::Normal"));
    }

    #[test]
    fn mod_rs_uses_typed_envelope_dispatch_for_each_command() {
        let s = mod_rs_template(&sample_params());
        // Each declared command's arm parses CommandRequest with the
        // typed Params + calls the typed handler + materializes
        // CommandResponse — the canonical envelope pattern.
        assert!(
            s.contains("CommandRequest::<EchoParams>::from_value(params)?"),
            "demo/echo must parse the typed envelope: {s}"
        );
        assert!(
            s.contains("self.handle_echo(req.params).await?"),
            "demo/echo must dispatch to handle_echo: {s}"
        );
        assert!(
            s.contains("CommandResponse::ok(result).into_command_result()"),
            "demo/echo must materialize the typed response: {s}"
        );
        assert!(s.contains("CommandRequest::<PingParams>::from_value(params)?"));
        assert!(s.contains("self.handle_ping(req.params).await?"));
    }

    #[test]
    fn mod_rs_emits_typed_handler_methods_for_each_command() {
        let s = mod_rs_template(&sample_params());
        assert!(
            s.contains("pub async fn handle_echo(") && s.contains("params: EchoParams"),
            "handle_echo method must exist with typed param: {s}"
        );
        assert!(s.contains("Result<EchoResult, String>"));
        assert!(s.contains("pub async fn handle_ping("));
    }

    #[test]
    fn mod_rs_imports_envelope_types_from_runtime() {
        let s = mod_rs_template(&sample_params());
        assert!(s.contains("CommandRequest"), "must import CommandRequest");
        assert!(s.contains("CommandResponse"), "must import CommandResponse");
        assert!(s.contains("CommandExecutor"), "must import CommandExecutor");
    }

    #[test]
    fn mod_rs_includes_with_executor_constructor_for_tests() {
        let s = mod_rs_template(&sample_params());
        assert!(
            s.contains("#[cfg(test)]"),
            "must scope test-only constructor"
        );
        assert!(
            s.contains("pub fn with_executor(executor: Arc<CommandExecutor>) -> Self"),
            "with_executor must be available for test injection"
        );
        assert!(s.contains("executor_override"));
    }

    #[test]
    fn mod_rs_emits_concurrency_stress_test_with_multi_thread_runtime() {
        let s = mod_rs_template(&sample_params());
        assert!(
            s.contains("flavor = \"multi_thread\", worker_threads = 4"),
            "concurrency test must use multi-thread tokio per field manual §4.2"
        );
        assert!(s.contains("fn handlers_under_concurrent_load"));
        assert!(
            s.contains("Arc::new(DemoModule::new())"),
            "test must use Arc<Module> per production multi-persona pattern"
        );
    }

    #[test]
    fn mod_rs_for_stateless_module_omits_resource_lock_scaffold() {
        let s = mod_rs_template(&sample_params());
        assert!(
            !s.contains("resource_locks: DashMap"),
            "stateless module must NOT carry the resource lock field: {s}"
        );
        assert!(
            !s.contains("ResourceState"),
            "stateless module must NOT declare ResourceState"
        );
        assert!(
            !s.contains("use dashmap::DashMap"),
            "stateless module must NOT import dashmap"
        );
    }

    #[test]
    fn mod_rs_for_stateful_module_emits_per_resource_lock_scaffold() {
        let mut p = sample_params();
        p.stateful = true;
        let s = mod_rs_template(&p);
        assert!(
            s.contains("use dashmap::DashMap"),
            "stateful module must import dashmap"
        );
        assert!(
            s.contains("struct ResourceState"),
            "stateful module must declare ResourceState"
        );
        assert!(
            s.contains("resource_locks: DashMap<String, Arc<tokio::sync::Mutex<ResourceState>>>"),
            "stateful module must carry the canonical per-resource lock map"
        );
        assert!(
            s.contains("fn resource_lock(&self, id: &str)"),
            "stateful module must expose the get-or-create helper"
        );
        assert!(
            s.contains("resource_locks_stay_parallel_across_distinct_ids"),
            "stateful module must include the per-resource concurrency test"
        );
    }

    #[test]
    fn mod_rs_subscribes_to_declared_events() {
        let s = mod_rs_template(&sample_params());
        assert!(s.contains("\"data:demo_items:created\""));
    }

    #[test]
    fn mod_rs_documents_published_events_in_module_docstring() {
        let s = mod_rs_template(&sample_params());
        assert!(s.contains("Documented published events"));
        assert!(s.contains("`demo:event:emitted`"));
    }

    #[test]
    fn mod_rs_for_command_less_module_still_compiles_shape() {
        let mut p = sample_params();
        p.commands.clear();
        let s = mod_rs_template(&p);
        // Even with no commands the module-name prefix is in
        // command_prefixes so future commands route through it.
        assert!(s.contains("\"demo/\""));
        // The dispatch block is empty; the catch-all stays.
        assert!(s.contains("other => Err"));
        // No typed import line (no commands → no types).
        assert!(!s.contains("use types::{"));
    }

    // ── types.rs template ────────────────────────────────────────────

    #[test]
    fn types_rs_emits_params_and_result_for_each_command() {
        let s = types_rs_template(&sample_params());
        assert!(s.contains("pub struct EchoParams"));
        assert!(s.contains("pub struct EchoResult"));
        assert!(s.contains("pub struct PingParams"));
        assert!(s.contains("pub struct PingResult"));
    }

    #[test]
    fn types_rs_annotates_for_ts_rs_export_with_camel_case() {
        let s = types_rs_template(&sample_params());
        assert!(s.contains("#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]"));
        assert!(s.contains("#[serde(rename_all = \"camelCase\")]"));
        assert!(
            s.contains("export_to = \"../../../protocol/typescript/demo/EchoParams.ts\""),
            "export_to path must match the canonical shared/generated layout"
        );
    }

    #[test]
    fn types_rs_for_command_less_module_emits_no_params_structs() {
        let mut p = sample_params();
        p.commands.clear();
        let s = types_rs_template(&p);
        assert!(!s.contains("pub struct"));
        assert!(s.contains("No commands declared yet"));
    }

    // ── design.md template ───────────────────────────────────────────

    #[test]
    fn design_md_includes_all_required_sections() {
        let s = design_md_template(&sample_params());
        for header in [
            "## Role",
            "## Command surface",
            "## Cross-module dependencies",
            "## State model",
            "## Events emitted",
            "## Concurrency contract",
            "## Migration notes",
            "## Kinks found",
        ] {
            assert!(
                s.contains(header),
                "DESIGN.md must include header `{header}`: {s}"
            );
        }
    }

    #[test]
    fn design_md_lists_each_command_in_the_surface_table() {
        let s = design_md_template(&sample_params());
        assert!(s.contains("| `demo/echo` | `EchoParams` | `EchoResult` |"));
        assert!(s.contains("| `demo/ping` | `PingParams` | `PingResult` |"));
    }

    #[test]
    fn design_md_state_section_reflects_stateful_flag() {
        let stateless = design_md_template(&sample_params());
        assert!(
            stateless.contains("Stateless"),
            "stateless module's state section must say so"
        );

        let mut p = sample_params();
        p.stateful = true;
        let stateful = design_md_template(&p);
        assert!(
            stateful.contains("Per-resource state stored in `DashMap"),
            "stateful module's state section must describe the lock pattern"
        );
    }

    // ── README template ──────────────────────────────────────────────

    #[test]
    fn readme_lists_declared_contract_and_three_files() {
        let s = readme_template(&sample_params());
        assert!(s.contains("# `demo` module"));
        assert!(s.contains("- `demo/echo`"));
        assert!(s.contains("- `demo/ping`"));
        // The README must mention all three scaffolded files so the
        // author knows what's there.
        assert!(s.contains("mod.rs"));
        assert!(s.contains("types.rs"));
        assert!(s.contains("DESIGN.md"));
        assert!(s.contains("pub mod demo;"));
        assert!(s.contains("DemoModule::new()"));
    }

    #[test]
    fn readme_for_stateful_module_announces_stateful_status() {
        let mut p = sample_params();
        p.stateful = true;
        let s = readme_template(&p);
        assert!(
            s.contains("**Stateful**"),
            "stateful module's README must announce it: {s}"
        );
    }

    #[test]
    fn readme_handles_empty_lists_gracefully() {
        let mut p = sample_params();
        p.commands.clear();
        p.events_subscribed.clear();
        p.events_published.clear();
        let s = readme_template(&p);
        assert!(s.contains("_None declared._"));
    }

    // ── naming helpers ───────────────────────────────────────────────

    #[test]
    fn command_to_type_stem_strips_module_prefix_and_pascals() {
        assert_eq!(command_to_type_stem("chat", "chat/poll"), "Poll");
        assert_eq!(
            command_to_type_stem("chat", "chat/analyze/findings"),
            "AnalyzeFindings"
        );
        assert_eq!(
            command_to_type_stem("ai", "ai/inference/start"),
            "InferenceStart"
        );
        // Without the module prefix, pascal the whole thing.
        assert_eq!(
            command_to_type_stem("chat", "collaboration/chat/poll"),
            "CollaborationChatPoll"
        );
        // Dash-separated parts convert cleanly too.
        assert_eq!(
            command_to_type_stem("ai-provider", "ai-provider/route"),
            "Route"
        );
    }

    #[test]
    fn command_to_handler_name_strips_module_prefix_and_snakes() {
        assert_eq!(command_to_handler_name("chat", "chat/poll"), "handle_poll");
        assert_eq!(
            command_to_handler_name("chat", "chat/analyze/findings"),
            "handle_analyze_findings"
        );
        assert_eq!(
            command_to_handler_name("ai", "ai/inference/start"),
            "handle_inference_start"
        );
    }
}
