// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThermalSeverity } from "./ThermalSeverity";

/**
 * Tuneable thresholds for the cascade. Loaded from policy file in
 * PR-3c2 (extends PolicyFile). For PR-3c1, callers pass typed values
 * so the evaluator is testable with any threshold set.
 *
 * Pinned to the values from the spec's §"Adjustment Cascade" table;
 * callers may override per-policy (the spec's table is the default
 * for the M-Air anchor + 5090 anchor).
 */
export type CascadeThresholds = { specMissRateAdvance: number, specMissRateRetreat: number, inferenceQueueDepthAdvance: number, inferenceQueueDepthRetreat: number, vramUsedPctAdvance: number, vramUsedPctRetreat: number, systemMemUsedPctAdvance: number, systemMemUsedPctRetreat: number, 
/**
 * Thermal severity at or above which step 2 enters. Step 2's
 * other enter conditions are step 1 sustained + mem high.
 */
thermalAdvance: ThermalSeverity, batteryPctAdvance: number, batteryPctRetreat: number, 
/**
 * Battery percentage that triggers EmergencyAdvanceToMax. Below
 * this, the cascade jumps straight to MAX regardless of current
 * step. Default 10% per spec.
 */
batteryPctEmergency: number, };
