// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Decision the cascade evaluator emits per signal. PR-3c2 wires
 * these into the local governor's `on_pressure_signal` to actually
 * rewrite the policy.
 */
export type CascadeAction = { "kind": "hold" } | { "kind": "advance" } | { "kind": "retreat" } | { "kind": "emergencyAdvanceToMax" };
