// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GovernorPolicy } from "./GovernorPolicy";
import type { PressureSignal } from "./PressureSignal";

/**
 * Telemetry snapshot — current policy + cascade-step counter +
 * recent cascade history (PR-3 wires the history; PR-1 ships the
 * shape).
 */
export type GovernorSnapshot = { currentPolicy: GovernorPolicy, 
/**
 * Number of cascade-step transitions since boot. Diagnostic — high
 * counts = oscillation, low counts = stable.
 */
cascadeTransitionCount: number, 
/**
 * Last N pressure signals received. PR-3 implements; PR-1 ships
 * the slot. Empty in PR-1.
 */
recentSignals: Array<PressureSignal>, };
