// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scoring weights for `DemandAlignedRecall` (Lane H PR-3). Sum should
 * be ~1.0 by convention; the governor's policy file enforces this.
 */
export type RecallScoreWeights = { semantic: number, outcomeHistory: number, recency: number, tierProximity: number, provenanceTrust: number, };
