// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ping result - includes uptime and connection stats
 */
export type PingResult = { uptimeMs: bigint, connectionsTotal: bigint, requestsProcessed: bigint, activeCategories: number, };
