// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewOutcome } from "./ReviewOutcome";
import type { WorkArtifactReference } from "./WorkArtifactReference";

export type WorkReviewParams = { room: string, review_id: string, card_id: string, submission_id: string, artifact: WorkArtifactReference, review_card_id: string, review_claim_id: string, outcome: ReviewOutcome, evidence: WorkArtifactReference, };
