// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewOutcome } from "./ReviewOutcome";
import type { WorkArtifactReference } from "./WorkArtifactReference";

export type WorkReviewParams = { 
/**
 * The room the review card lives in (id or name).
 */
room: string, 
/**
 * The review card you hold.
 */
review_card_id: string, 
/**
 * Your verdict.
 */
outcome: ReviewOutcome, 
/**
 * What you ran and saw; becomes the review's evidence.
 */
evidence_text?: string, 
/**
 * Minted when omitted.
 */
review_id?: string, 
/**
 * The card under review; read from the review card when omitted.
 */
card_id?: string, 
/**
 * The submission reviewed; the latest when omitted.
 */
submission_id?: string, 
/**
 * Its artifact; read off the board when omitted.
 */
artifact?: WorkArtifactReference, 
/**
 * Your claim on the review card; read off the board when omitted.
 */
review_claim_id?: string, 
/**
 * A typed evidence reference instead of evidence_text.
 */
evidence?: WorkArtifactReference, };
