// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkDuplicatesParams = { 
/**
 * Which room's board to read — a room name (`academy`) or channel id you are
 * subscribed to. Default: the room you are standing in. Boards are PER ROOM.
 */
room?: string, 
/**
 * Which columns to group (default `["open"]`). Empty = every card.
 */
states: Array<string>, 
/**
 * How far above the embedder's unrelated-pair mean two cards must sit to be
 * called the same card, in standard deviations. Default 6 — deliberately
 * tighter than `work/similar`'s 3: "related" and "the same" are different
 * floors. Measured 2026-09-16 on the live board: at 3σ (cosine 0.57 on
 * qwen3-embedding-0.6b) connected components CHAINED 59 unrelated engineering
 * cards into one group at cohesion 0.45, while every true duplicate sat at
 * 1.00. Lower it to widen; the result names the floor it joined at.
 */
minZ: number, };
