// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewOutcome } from "./ReviewOutcome";
import type { WorkArtifactReference } from "./WorkArtifactReference";

export type WorkReviewParams = { 
/**
 * Review room (ID/name).
 */
room: string, 
/**
 * The review card you hold.
 */
review_card_id: string, 
/**
 * Your verdict.
 */
outcome: ReviewOutcome, 
/**
 * What you ran and saw; becomes the review's evidence.
 */
evidence_text?: string, 
/**
 * Minted when omitted.
 */
review_id?: string, 
/**
 * Parent card; defaults to review's parent.
 */
card_id?: string, 
/**
 * Submission; defaults to latest.
 */
submission_id?: string, 
/**
 * Artifact; defaults to board.
 */
artifact?: WorkArtifactReference, 
/**
 * Review claim; defaults to board.
 */
review_claim_id?: string, 
/**
 * A typed evidence reference instead of evidence_text.
 */
evidence?: WorkArtifactReference, };
