// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The same content-addressed reference the AIRC submission protocol carries.
 */
export type WorkArtifactReference = { 
/**
 * SHA-256 of the patch bytes, not a git sha.
 */
hash: string, 
/**
 * Artifact byte length.
 */
size_bytes: number, 
/**
 * Optional media type.
 */
mime?: string, };
