// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkSimilarHit } from "./WorkSimilarHit";

export type WorkSimilarResult = { 
/**
 * What was compared against: the card's id, or `text`.
 */
query: string, 
/**
 * How many cards were scored (after the state filter).
 */
searched: number, space: string, gate: string, hits: Array<WorkSimilarHit>, };
