// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerHypothesis } from "./LedgerHypothesis";

export type CardLedger = { cardId: string, 
/**
 * Facts established by observation this turn or before: file ranges read with what
 * they showed, tests run with the failing assertion, commands and their outcome.
 */
known: Array<string>, hypotheses: Array<LedgerHypothesis>, 
/**
 * The single unknown the answer turns on.
 */
unknown: string, 
/**
 * The next observation to run — the first act of the next turn.
 */
nextTest: string, 
/**
 * Once decided: file:line and the intended edit.
 */
decidedFix?: string, atMs: number, by: string, };
