// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A role's declared lane requirement — the recipe's word on what a seat must hold
 * before one of its minds sits there ([`crate::cognition::grid_allocation::Requirement`]).
 */
export type CitizenRequirement = { 
/**
 * Tokens one turn of this role needs (a real coding turn, a chat turn).
 */
windowTokens: number, 
/**
 * The least capable model this role is competent on (`capability_rank`); 0 = any.
 */
minCapability: number, 
/**
 * Per-stream decode below this is not a seat; absent = not judged.
 */
decodeFloorTps?: number, };
