// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One competing explanation and the observation that would settle it.
 */
export type LedgerHypothesis = { claim: string, evidenceFor: Array<string>, evidenceAgainst: Array<string>, 
/**
 * The cheapest observation that would confirm or kill this claim.
 */
test: string, };
