// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionRole } from "./RegionRole";
import type { RegionScope } from "./RegionScope";

/**
 * A view-intent: one surface of the room bound to a live payload `kind`. Carries
 * *where it belongs* and *how central it is* — never how it looks.
 */
export type Region = { 
/**
 * Stable region name within the room (`"scoreboard"`, `"messages"`, `"roster"`).
 */
name: string, 
/**
 * The live payload `kind` this region binds to — the same string an
 * `ObserverSpec` subscribes to and a `StateEnvelope` carries (e.g. a
 * `ChatViewState`'s `KIND`). The renderer resolves the payload by this kind.
 */
kind: string, 
/**
 * Which layout zone this region belongs to.
 */
scope: RegionScope, 
/**
 * How central this region is within its zone.
 */
role: RegionRole, 
/**
 * Whether the region streams (subscribe + re-render on revision) or is static.
 */
live: boolean, };
