// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-call outcome. Flattens the FIVE return sites of the old `Option<String>`.
 */
export type ActStatus = "Executed" | { "Errored": { message: string, } } | { "AlreadySatisfied": { repeat: number, } } | { "RedundantOrientation": { repeat: number, } };
