// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditEntryKind } from "./AuditEntryKind";

/**
 * One audit log entry. Append-only — entries are written once, never
 * modified. The `chain_hash` is computed from the entry's content + the
 * previous entry's chain_hash, forming the tamper-detection chain.
 *
 * The `payload` field is a free-form JSON value — each kind has its
 * own payload shape that downstream tooling decodes. Keeping the wire
 * format open-ended means new audit kinds can ship without a schema
 * migration; tooling that doesn't recognize a kind just records the
 * raw JSON.
 */
export type AuditEntry = { 
/**
 * Monotonic sequence number. Starts at 0 for the genesis entry.
 * Verifier asserts seq == prev_seq + 1 — gap detection.
 */
seq: number, 
/**
 * Unix-ms timestamp the entry was recorded. Caller's clock —
 * verifier asserts monotonic-non-decreasing across entries.
 */
timestampMs: number, 
/**
 * Which event kind this entry records.
 */
kind: AuditEntryKind, 
/**
 * Free-form JSON payload for this entry. Shape per-kind; the
 * recorder doesn't validate the inner shape (downstream tooling
 * does). On the TS wire it surfaces as `unknown` — consumers
 * narrow by `kind`.
 */
payload: unknown, 
/**
 * Hex-encoded SHA-256 chain hash:
 * `sha256(seq || timestamp_ms || kind || payload || prev_chain_hash)`.
 * Genesis entry's prev_chain_hash is the all-zeros string of length 64.
 */
chainHash: string, 
/**
 * The hash of the previous entry. Genesis = "0" * 64.
 */
prevChainHash: string, };
