// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallStatus } from "./CallStatus";
import type { PayloadRef } from "./PayloadRef";

export type CallHeader = { request_id: string, session_id: string, cycle_id: number | null, room_id: string, cause: string, cause_root: string | null, captured_at_ms: number, started_at_ms: number, status: CallStatus, model: string | null, 
/**
 * References bind to retained generations, never caller-supplied paths.
 */
request: PayloadRef, terminal: PayloadRef | null, 
/**
 * Stable event cursor; callers upsert lifecycle events by session/request ID.
 */
cursor: string, };
