// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaRef } from "../identity/PersonaRef";

export type CognitionPromptParams = { 
/**
 * The persona (UUID) whose verbatim LLM I/O to inspect.
 */
persona_id: PersonaRef, 
/**
 * How many recent LLM calls to return (newest last). Default 10, max 100.
 */
limit: number | null, 
/**
 * Read the retained previous capture segment instead of the current one.
 */
previous?: boolean, };
