// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvalPassProgress = { 
/**
 * Tasks graded so far in the CURRENT pass.
 */
done: number, 
/**
 * Tasks in the current pass.
 */
total: number, 
/**
 * Passes so far — `pass / done` is the running rate.
 */
pass: number, 
/**
 * The task just graded.
 */
currentTask: string, 
/**
 * Whether it passed.
 */
lastOk: boolean, 
/**
 * Output tokens the model produced for this task. A near-zero value on a FAILED
 * task is the decline/wedge signature (a bare "PASS" is ~2 tokens) — this is the
 * LIVE signal a monitoring widget/persona needs to light a cell SUSPECT (harness
 * noise) vs a real wrong answer, in real time instead of post-hoc from the ledger.
 */
outputTokens: number, 
/**
 * Receiver-clock ms — staleness signal for readers (a row older than a task's
 * typical latency means the pass ended or died; the ledger row is the truth).
 */
updatedAtMs: number, 
/**
 * Live VRAM available (GB) at grade time — the resource-efficiency axis next to
 * accuracy and latency, sampled from the ONE per-machine authority. `null` when
 * VRAM is ungoverned (bare tests) — absence is honest, never a fabricated 0.
 */
vramFreeGb?: number, 
/**
 * The run_id producing THIS snapshot, when the pass carries a handle. Lets a
 * persona-only poll (no run_id arg) tell it's reading ITS run vs a prior one —
 * the stale-progress trap where a fresh detached run reads as instantly-complete
 * with the last run's numbers. `null` for a sync/handleless run.
 */
runId?: string, };
