// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much was forgotten, and what remains.
 */
export type ForgetContextResult = { 
/**
 * Engrams dropped (all tagged with the episode's context id).
 */
forgotten: number, 
/**
 * Engrams remaining in her store after the flash.
 */
engramCount: number, };
