// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIDecisionContext } from "./AIDecisionContext";
import type { GenerateResponseAdmissionPolicy } from "./GenerateResponseAdmissionPolicy";

/**
 * IPC request: ask the cognition service to assemble a response-prompt
 * and (in PR-2) run it through the local inference provider.
 */
export type GenerateResponseRequest = { 
/**
 * Reuses the gating context. Host callers provide the persona's
 * identity system prompt with `Current room members: ...` in
 * `context.system_prompt`.
 */
context: AIDecisionContext, 
/**
 * Optional model override. Defaults to the local-Qwen routing
 * sentinel when unset.
 */
model?: string, 
/**
 * Sampling temperature.
 */
temperature?: number, 
/**
 * Max tokens to generate.
 */
maxTokens?: number, 
/**
 * Hard cap on how long PR-2's async composer waits before
 * returning timeout.
 */
timeoutMs?: number, 
/**
 * Rust-owned admission policy for this generation. When omitted,
 * `evaluate_response` applies the local-generation defaults above.
 * Hosts that know tighter resource limits should pass them here;
 * they should not coordinate slots outside Rust.
 */
admission?: GenerateResponseAdmissionPolicy, };
