// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeGenerationRequest } from "./RecipeGenerationRequest";

/**
 * Orchestrator request — extends `RecipeGenerationRequest` with optional
 * per-call provider/model/temperature overrides. Carrier for what the
 * TS path passes via `genParams`. This IS the typed params of
 * `cognition/generate-recipe` (the whole `{ request, provider?, model?,
 * temperature? }` payload deserializes into it), so it carries the full wire
 * derive set + camelCase serde.
 */
export type GenerateRecipeOrchestratorParams = { request: RecipeGenerationRequest, provider?: string, model?: string, temperature?: number, };
