// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenomeEvictUnderPressureResult = { personaId: string, targetPressure: number, pressureBefore: number, pressureAfter: number, bytesFreed: number, };
