// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenomeEvictUnderPressureParams = { 
/**
 * Persona whose genome is evicted.
 */
personaId: string, 
/**
 * Target memory-pressure ratio to evict down to (default 0.75).
 */
targetPressure: number, };
