// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenomeCoverageReportParams = { 
/**
 * Persona whose coverage ledger is read.
 */
personaId: string, };
