// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InboxDrainFrameParams = { 
/**
 * Persona whose inbox is drained.
 */
personaId: string, 
/**
 * Coalescing window in milliseconds (default 80).
 */
windowMs: number, 
/**
 * Maximum messages to drain into one frame (default 16).
 */
maxItems: number, };
