// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `respond()` returns.
 *
 * `Silent` is a first-class outcome: the persona considered the message,
 * found nothing additive to add, and chose not to speak. The reason is
 * observable for trainability + the persona's own meta-cognitive trace.
 * Not the same as a failure.
 *
 * `Spoke` is the response that should be posted to the room.
 */
export type PersonaResponse = { "kind": "silent", persona_id: string, reason: string, 
/**
 * Relevance score that drove the decision. 0.0..1.0. Carried so
 * downstream telemetry can analyze the silence-rate by score
 * distribution.
 */
relevance_score: number, } | { "kind": "spoke", persona_id: string, 
/**
 * Cleaned visible speech to post to the room. `<think>` blocks
 * have been stripped; the visible response is what the user
 * sees in chat.
 */
text: string, 
/**
 * Model that produced the response (post-routing).
 */
model_used: string, 
/**
 * Duration of the inference call itself (not including
 * analysis or scoring — those are separate).
 */
inference_ms: number, 
/**
 * Total duration end-to-end (analysis + scoring + inference +
 * parsing + event emission).
 */
total_ms: number, 
/**
 * Number of `<think>` blocks extracted (for telemetry —
 * the actual content was emitted as events for hippocampus).
 */
think_blocks_emitted: number, };
