// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engram } from "../persona/Engram";

/**
 * The recalled engrams and their count.
 */
export type RecallEngramsResult = { engrams: Array<Engram>, count: number, };
