// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceClass } from "./ResourceClass";
import type { TargetSilicon } from "./TargetSilicon";
import type { ThroughputLeaseRevocationPolicy } from "./ThroughputLeaseRevocationPolicy";

export type ResourceAdmissionPolicy = { resourceClass: ResourceClass, targetSilicon: TargetSilicon, maxConcurrency: number, maxCostUnits: number, costUnits: number, leaseTtlMs: number, revocationPolicy: ThroughputLeaseRevocationPolicy, };
