// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-persona orchestration decision. The orchestrator produces one
 * of these for each persona in the room based on the SharedAnalysis +
 * persona specialty + (eventually) lever calls + recent contribution
 * history.
 *
 * `should_respond=false` is a first-class outcome — silence-with-reason
 * is the architecture's preferred answer when the persona has nothing
 * additive. The reason is stored for trainability + the persona's own
 * meta-cognitive trace.
 */
export type ResponderDecision = { personaId: string, shouldRespond: boolean, 
/**
 * 0.0..1.0. How relevant this persona's specialty is to the message
 * + analysis. Above the orchestrator's threshold = respond; below
 * = silent.
 */
relevanceScore: number, 
/**
 * Which keys from `SharedAnalysis.suggested_angles` matched this
 * persona's specialty. Becomes part of the render prompt so the
 * contribution is grounded in a specific angle. Empty when
 * `should_respond=false`.
 */
matchedAngles: Array<string>, 
/**
 * Human-readable explanation of the decision. Always populated
 * — for both selection and skip cases. Observable in logs +
 * the coordination stream.
 */
explanation: string, 
/**
 * Phase B: which persona leads the streaming chain-of-thought
 * (others see the lead's render in flight and build on it).
 * Phase A: the highest-relevance responder is is_lead=true; rest
 * are parallel renders.
 */
isLead?: boolean, };
