// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterInfo } from "../persona/AdapterInfo";

/**
 * Full adapter-set sync for one persona: replace, don't merge.
 */
export type SyncAdaptersRequest = { 
/**
 * Persona whose registry is being replaced.
 */
persona_id: string, 
/**
 * The complete adapter set to install (the registry is cleared first).
 */
adapters: Array<AdapterInfo>, };
