// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreatFrameKind } from "./ThreatFrameKind";

export type ThreatFrame = { frameId: string, kind: ThreatFrameKind, source: string, text: string, };
