// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreatFrameKind = "chat-message" | "tool-request" | "memory-write" | "federation-message" | "media-transcript" | "runtime-frame";
