// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisionDescribeOptions } from "./VisionDescribeOptions";

/**
 * Request shape for the `cognition/vision-describe` IPC.
 */
export type VisionDescribeRequest = { 
/**
 * Base64-encoded image bytes. The Rust adapter shapes this for the
 * destination provider's wire format (Anthropic native base64,
 * OpenAI image_url, llama.cpp mmproj).
 */
base64Data: string, 
/**
 * MIME type (e.g. `image/png`, `image/jpeg`).
 */
mimeType: string, options: VisionDescribeOptions, };
