// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvictionPolicy } from "./EvictionPolicy";
import type { PageRef } from "./PageRef";
import type { TierRole } from "./TierRole";

/**
 * Typed record emitted to the trace bus every time a page is evicted
 * from some tier. The reason carries the policy that fired (LRU,
 * LFU, etc.). Recurring evictions of the same page across turns are
 * the signal sentinel uses to upgrade the page's tier policy.
 *
 * Per GENOME-FOUNDRY-SENTINEL Part 2: "every evicted page emits an
 * EvictionRecord to the trace bus." PR-3 wires this through my just-
 * shipped artifact dispatch (#1339 + #1343); PR-1 ships the shape.
 */
export type EvictionRecord = { 
/**
 * The page that was evicted.
 */
page: PageRef, 
/**
 * Which tier evicted it.
 */
fromRole: TierRole, 
/**
 * Where the page went (Some) or whether it was dropped entirely
 * (None — only valid for Cold/Frozen during GC).
 */
toRole?: TierRole, 
/**
 * The policy that fired this eviction. Lets the trace bus
 * reconstruct *why* without re-running the policy.
 */
policyFired: EvictionPolicy, 
/**
 * Time spent on the eviction itself (selection + tier-write +
 * metadata update). Doesn't include the time the calling
 * page_in/page_out spent blocked on it — that's a separate
 * signal on the caller side.
 */
elapsedUs: number, };
