// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A gene's identity, as the two places a gene can live spell it: an adapter PATH on
 * this node (what the manifest, the serving daemon and the signature store key by),
 * or a REPO on the hub (what `genome/pull` takes). An enum, never a string that is
 * sometimes a path and sometimes a repo: the variant says which, and the stores keep
 * their own key types.
 */
export type GeneRef = { "at": "local", path: string, } | { "at": "hub", repo: string, };
