// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenomePushParams = { 
/**
 * The gene to publish, by its registered name (`genome/list` shows them).
 */
gene: string, 
/**
 * Target HF repo (`namespace/name`), e.g. `continuum-ai/ornith-code-asha`.
 */
repo: string, };
