// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenomeSharingResult = { 
/**
 * Whether this node currently participates (agreement recorded AND its
 * version matches the current covenant).
 */
agreed: boolean, 
/**
 * The covenant version the current terms carry.
 */
covenant_version: string, 
/**
 * The recorded consent receipt (`<version>@<unix-ms>`), when one exists.
 * A receipt with a stale version means the terms changed since agreement
 * — `agreed` reads false and re-agreement is required.
 */
receipt?: string, 
/**
 * The covenant text, VERBATIM — every surface renders this same text.
 */
covenant: string, 
/**
 * The HF account the `hf` CLI is authenticated as (the token holder the
 * commons publishes under), when authenticated. `None` = not logged in —
 * the settings surface shows "authenticate with `hf auth login`". The
 * TOKEN itself never rides any wire; status only.
 */
hf_account?: string, };
