// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenomeBootstrapResult = { 
/**
 * Genes registered this run.
 */
pulled: Array<string>, 
/**
 * Candidate repos skipped, each with its reason — counted, never silent.
 */
skipped: Array<string>, 
/**
 * True when the node already carries genes for this base — nothing to do.
 */
already_seeded: boolean, 
/**
 * False when the covenant is not accepted — the bootstrap waits for
 * consent instead of erroring (it runs automatically at serving-ready).
 */
consent: boolean, };
