// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenomePushParams = { 
/**
 * The gene to publish, by its registered name (`genome/list` shows them).
 */
gene: string, 
/**
 * Target HF repo (`namespace/name`), e.g. `continuum-ai/ornith-code-asha`.
 */
repo: string, 
/**
 * Direct parent alloy hashes for the lineage DAG — the genes this one forked
 * from/built on. Empty = a root gene (a lineage origin). Signed into provenance.
 */
parent_alloy_hashes: Array<string>, };
