// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenomeListGene } from "./GenomeListGene";

export type GenomeListResult = { 
/**
 * Every registered gene with its signature + fitness facts — the local
 * registry view (what the desktop settings/genome tab renders).
 */
genes: Array<GenomeListGene>, 
/**
 * Whether this node participates in the sharing commons (the opt-in).
 */
sharing_enabled: boolean, };
