// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenomeRecallGene = { 
/**
 * The gene's name (adapter alias — the id the page-in chain speaks).
 */
gene: string, 
/**
 * Combined recall score (0..1), the ranking key.
 */
score: number, 
/**
 * Distance term: similarity of the need to the gene's minted signature
 * (or its keyword fallback when unsigned).
 */
semantic: number, 
/**
 * Fitness term folded from eval receipts (neutral 0.5; >0.5 = measured
 * lift, <0.5 = measured harm; includes the UCB audition bonus).
 */
fitness: number, 
/**
 * Whether a minted signature answered (vs the match-text fallback).
 */
signed: boolean, };
