// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeachProgress } from "./TeachProgress";

export type GenomeTeachStatusResult = { 
/**
 * True once the run's ledger row exists (the detached run finished — check
 * `result.ok`). Always false when polled without a run_id (live-progress only).
 */
complete: boolean, 
/**
 * The terminal ledger row `{ok, result|error}` when complete, else null.
 */
result?: unknown, 
/**
 * Live progress of the currently-running teach — the mid-run scoreboard a progress
 * bar renders (done/total/currentTask/solved). Null until the first milestone fires;
 * check `updatedAtMs` for staleness on a long-finished run.
 */
progress?: TeachProgress, };
