// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobCreateResult } from "./JobCreateResult";

/**
 * Outcome envelope for `genome/job-create`. `success=true` carries `result`;
 * `success=false` carries `error` (+ `errorKind` when the failure came from the
 * adapter rather than the coordinator). See the module docs for why expected
 * domain failures are data, not a transport `Err`.
 */
export type JobCreateOutcome = { success: boolean, result?: JobCreateResult, error?: string, errorKind?: string, };
