// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneRef } from "./GeneRef";
import type { LoRAHyperparams } from "./fine_tuning/LoRAHyperparams";
import type { ScheduleParams } from "./fine_tuning/ScheduleParams";
import type { TrainingDataset } from "./fine_tuning/TrainingDataset";

/**
 * Wire shape for `genome/job-create` params. Mirrors [`TrainingJobRequest`]
 * verbatim (flattened), plus the optional `preferredProvider` hint the coordinator
 * honors — or rejects, surfacing the rejection as `success=false` rather than
 * silently routing elsewhere.
 */
export type JobCreateParams = { 
/**
 * Correlates the trigger's durable intent with the actual created handle.
 * Evidence only: provider creation is not made idempotent by this field.
 */
triggerDispatchId?: string, 
/**
 * Force a specific provider (e.g. `"openai"`, `"local-candle"`). Honored only
 * if that provider is in the capable set; otherwise the outcome is
 * `success=false` — never a silent fallback to a different provider.
 */
preferredProvider?: string, 
/**
 * Name of an on-disk dataset under the datasets root
 * (`~/.continuum/datasets/<name>/train.jsonl`, the chat `{messages}` JSONL
 * that `dataset/from-captures` / `dataset/from-turns` write). Loaded into the
 * request's `dataset` before adapter selection, so adapters always see a
 * populated dataset. Mutually exclusive with inlining `dataset` examples —
 * exactly one of the two must be provided.
 */
datasetName?: string, 
/**
 * Owning persona — the layer is paged into this persona's working
 * set when the matching skill activates.
 */
personaId: string, 
/**
 * Human-readable persona name for telemetry + alloy
 * attribution. Substrate-derived from the persona seed;
 * caller-passed for adapters that need it in the job metadata.
 */
personaName: string, 
/**
 * Base model the LoRA layer attaches to. Must match an entry in
 * the substrate's model registry; the adapter validates that
 * its provider hosts the base.
 */
baseModel: string, 
/**
 * What this layer is meant to encode — used as the skill key in
 * genome paging. e.g. "typescript-expertise", "kc-tech-history",
 * or a persona-named trait like "maya-voice".
 */
traitKind: string, 
/**
 * The curated dataset. Rust callers construct it directly; the
 * `genome/job-create` wire path may instead name an on-disk dataset
 * (`datasetName`), which the command loads into this field before the
 * request reaches any adapter — adapters always see a populated dataset.
 */
dataset: TrainingDataset, 
/**
 * A JSONL eval-set path (the `cognition/eval` `eval_set`) for a MANUAL
 * spot-check of this trait. It decides nothing: the automatic adoption
 * path ([`crate::modules::training_completion_sentinel`]) no longer runs
 * an eval copy of her mind (Joel, 2026-09-27: integrated, not parallel).
 * It registers the gene dormant and opens an in-room
 * [`GeneTrial`](crate::genome::gene_trial::GeneTrial), whose card
 * outcomes promote or retire it, whether or not this is set.
 */
evalSet?: string, 
/**
 * LoRA-specific hyperparams (rank, alpha, dropout, target
 * modules). `None` lets the adapter pick its provider defaults —
 * `Some` overrides them.
 */
lora?: LoRAHyperparams, 
/**
 * Training schedule (epochs, batch size, learning rate, sequence
 * length). `None` lets the adapter pick provider defaults.
 */
schedule?: ScheduleParams, 
/**
 * Where the resulting artifact should land on local disk.
 * `None` lets the adapter pick — usually
 * `~/.continuum/genome/<persona>/<trait_kind>/<job_uuid>.safetensors`.
 * Provider artifacts (OpenAI's `ft:gpt-4o-mini:...`) don't have a
 * local path; the field is `None` in their [`TrainingArtifact`].
 */
localArtifactDir?: string, 
/**
 * A checkpoint directory (a PEFT adapter plus its `state.json`) this job continues
 * from — set by the resume of a reboot-killed job (card 244757bc) so it loses
 * minutes, not the run. Absent on a fresh job.
 */
resumeFrom?: string, 
/**
 * The gene this job forks from (`Decision::Fork`): the child's lineage, stamped
 * into its signature at adoption. A trainer that can warm-start from it does; one
 * that cannot trains from the base and says so on its probe. Absent on a mint.
 */
parent?: GeneRef, };
