// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobHandle } from "./fine_tuning/JobHandle";

export type JobStatusParams = { 
/**
 * Handle returned by job-create; distinct from the kernel resource handle.
 */
jobHandle: JobHandle, 
/**
 * Continue an incomplete historical scan at the returned byte offset.
 */
historyOffset?: bigint, };
