// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvictionRecord } from "./EvictionRecord";
import type { PageRef } from "./PageRef";
import type { PersonaId } from "./PersonaId";
import type { TierRole } from "./TierRole";

/**
 * Typed event emitted when a persona's composition needs a page that
 * isn't already in its working set. Sentinel observes these to detect
 * patterns: a persona that page-faults on the same page across many
 * turns is a signal to either pre-fetch it or pin it higher.
 *
 * `from_role: None` means "true cold miss" — the page does not exist
 * in any tier yet (typically a fresh KV-cache entry or a never-loaded
 * MoE expert). `from_role: Some(role)` means "tier promotion" — the
 * page existed in `role` and got moved up.
 */
export type PageFault = { page: PageRef, 
/**
 * Where the page was before the fault. `None` for true cold
 * miss (page didn't exist yet).
 */
fromRole?: TierRole, 
/**
 * Where the page lives after the fault is serviced.
 */
toRole: TierRole, persona: PersonaId, 
/**
 * Time spent servicing the fault (tier lookup + transfer +
 * eviction-if-any). Drives sentinel's "is this page worth
 * pre-fetching" calculus.
 */
elapsedUs: number, 
/**
 * If servicing the fault required evicting another page, the
 * record of that eviction. Lets sentinel correlate cause +
 * effect across the trace bus in one record instead of joining
 * two separate event streams.
 */
evictionCost?: EvictionRecord, };
