// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";

/**
 * PR-2 stub for `Provenance`. The full shape (GENOME-FOUNDRY-
 * SENTINEL Part 1) carries creator, source_trace, source_artifact,
 * supersedes, adaptation_method, outcome_metrics, trust_score, and
 * license fields. PR-2 ships a typed minimum so the `TierStore::write`
 * signature compiles; the full shape is a separate Lane H PR that
 * replaces this stub.
 *
 * PR-2's stub carries:
 * - `artifact_id` — the content hash of the artifact this provenance
 *   describes. Required for the typed contract; matches the
 *   `ArtifactBlob.id` value passed alongside.
 * - `created_at_ms` — Unix-ms timestamp the provenance was attached.
 *   Required for ordering claims about the artifact across federation.
 *
 * When the full shape lands, downstream callers will be able to add
 * the remaining fields without changing the trait surface — this
 * type can grow fields without breaking callers that only set the
 * minimum.
 */
export type Provenance = { artifactId: ArtifactId, createdAtMs: number, };
