// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompositionRef } from "./CompositionRef";
import type { OutcomeWindow } from "./OutcomeWindow";
import type { TrajectoryHint } from "./TrajectoryHint";

/**
 * The persona's context for a recall call. Recall uses this for:
 * - `outcome_history` factor (recent_outcomes input)
 * - speculative weighting (conversation_trajectory)
 * - per-peer trust overrides (trust_overrides)
 * - skip-already-hot-artifacts (current_composition)
 */
export type RecallContext = { persona: string, 
/**
 * What composition is already hot for this persona. `None`
 * means the persona is starting fresh (cold composition).
 */
currentComposition?: CompositionRef, recentOutcomes: OutcomeWindow, conversationTrajectory: TrajectoryHint, 
/**
 * Per-peer trust adjustments from the persona's identity state.
 * Recall composes these with the artifact's `provenance_trust`
 * during scoring.
 */
trustOverrides: Array<[string, TrustClass]>, };
