// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bound on what the recall may touch. Lets a persona say "local
 * only" (e.g. for privacy-sensitive tasks) without per-call
 * federation-scope plumbing through every caller.
 */
export type RecallScope = { "kind": "local" } | { "kind": "localThenGrid", maxGridPulls: number, } | { "kind": "federation", peers: Array<string>, maxLatencyMs: number, };
