// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Protocol-compatible reference to an AIRC-substrate event/message.
 *
 * Per Joel 2026-05-13 (relayed by Codex): Continuum accepts AIRC data
 * by **proof/contract**, not by client identity. Any producer that
 * emits a valid envelope with these fields populated is acceptable;
 * the official `airc` CLI is not privileged. `transport = "airc"` names
 * the PROTOCOL; `client_name` is informational only (e.g., "airc-bash",
 * "airc-py", "third-party-emitter"). Admission Recipes in PR-2+ judge
 * the envelope's signature + provenance + trust metadata, not which
 * binary produced the bytes.
 *
 * Suggested field shape comes from Codex 2026-05-13 broadcast — see
 * AIRC log for full design discussion.
 */
export type AircMessageRef = { 
/**
 * Protocol identifier. Always `"airc"` for this variant; field exists
 * to support future cross-protocol references where the variant might
 * represent multiple wire protocols.
 */
transport: string, 
/**
 * AIRC room (channel) the message was posted to.
 */
room_id: string, 
/**
 * Stable AIRC message/event id within the room.
 */
message_id: string, 
/**
 * Sender pubkey or peer identity (the AIRC-whois identity, NOT a gh
 * login — per the gh-account-not-equal-identity rule from
 * `.airc/SAFETY.md` §Identity).
 */
sender_id: string, 
/**
 * When the sender claims they sent it (epoch ms UTC, signed by sender).
 */
sent_at_ms: number, 
/**
 * When the receiving persona observed it (epoch ms UTC, local clock).
 */
received_at_ms: number, 
/**
 * SHA-256 of the canonical content. Used for tamper detection +
 * cross-grid forensic re-verification.
 */
content_hash: string, 
/**
 * Detached signature over the canonical envelope. Verifiable against
 * `sender_id`'s public key. Required for the engram to admit via
 * non-trivial trust modes; PR-2+ Recipes will enforce.
 */
signature: string, 
/**
 * Pointers to additional proof material (e.g., forge-alloy contract
 * settlement signatures, room-rotation event signatures, attestation
 * chain references). Empty for plain messages.
 */
proof_refs: Array<string>, 
/**
 * Schema version of the envelope this reference describes. v1 starts
 * at `"v1"`. Forward-compatibility hinge.
 */
schema_version: string, 
/**
 * Informational client identity (e.g., "airc-bash", "airc-py",
 * "third-party-emitter"). Optional, NOT load-bearing for trust
 * decisions. Present so the polity can observe client-population
 * telemetry without admission ever depending on it.
 */
client_name: string | null, };
