// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of response prefix cleaning
 */
export type CleanedResponse = { 
/**
 * Cleaned text with prefixes stripped
 */
text: string, 
/**
 * Whether any cleaning was applied
 */
was_cleaned: boolean, 
/**
 * Extracted thinking/reasoning content from <thinking> or <think> tags
 */
thinking?: string, 
/**
 * Computation time in microseconds
 */
compute_time_us: number, };
