// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainActivity } from "./DomainActivity";

/**
 * Coverage report: what's covered, what's missing.
 */
export type CoverageReport = { 
/**
 * Domains with trained adapters
 */
covered: Array<DomainActivity>, 
/**
 * Domains with activity but no adapter
 */
gaps: Array<DomainActivity>, 
/**
 * Total interactions across all domains
 */
total_interactions: number, 
/**
 * Ratio: covered_interactions / total_interactions
 */
coverage_ratio: number, };
