// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaTurnFrameReplayRecord } from "./PersonaTurnFrameReplayRecord";

/**
 * Result of `persona/drain-turn-frame`: the replay record, or `None` on an empty drain.
 *
 * A NAMED wrapper around `Option<PersonaTurnFrameReplayRecord>` — the
 * command-schema validator ([`crate::sdk_codegen`]) rejects a bare `Option<T>`
 * output because an inline `T | null` has no named TS type to `export_to`, and
 * one such command panics the whole `command_registry()` walk. `record == None`
 * preserves the legacy contract: the drain window was empty (no-op).
 */
export type DrainTurnFrameResult = { record: PersonaTurnFrameReplayRecord | null, };
