// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional inputs to a spawn. All optional — the zero-arg call births ONE persona
 * with a random name and everything else derived from her id.
 */
export type PersonaSpawnParams = { 
/**
 * Explicit name for the (single) persona. Omit for a random name from the pool.
 * Ignored when `count > 1` — a batch is all-random (one name can't name many).
 */
name: string | null, 
/**
 * How many to spawn at once (grid capacity). Defaults to 1; clamped to
 * `[1, MAX_SPAWN]` so a runaway value can't birth an unbounded population.
 */
count: number | null, };
