// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `persona/allocate`.
 */
export type PersonaAllocateParams = { 
/**
 * Provider API-key env names present on this machine (e.g.
 * `ANTHROPIC_API_KEY`). A cloud persona whose key is absent is skipped;
 * empty ⇒ local-only allocation.
 */
availableApiKeys: Array<string>, };
