// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A read-friendly view of a persona's identity card, echoed after the edit.
 */
export type PersonaCardView = { personaId: string, agentName: string, gender: string, pronouns: string, avatarVrm: string | null, voiceSeed: string, role: string | null, profile: { [key in string]: string }, };
