// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One peer in the continuum's directory.
 */
export type PresenceDirectoryEntry = { 
/**
 * Display name from the published identity card; a provisional
 * `peer-xxxxxxxx` for a present-but-uncarded peer (unmistakable on
 * purpose — never silently wrong).
 */
name: string, peer_id: string, 
/**
 * Self-reported runtime origin (`"interactive"`, `"persona"`, `"claude"`, …).
 */
runtime: string, 
/**
 * Coarse kind from the identity card's `continuum_kind` integration
 * (`"human"` | `"persona"`), else derived: `interactive` runtime → human,
 * anything else → `"agent"`.
 */
kind: string, 
/**
 * ONLINE = heartbeat within the live presence window, OR resident on this
 * node (residency wins — see module doc).
 */
online: boolean, 
/**
 * Resident on THIS node (live service loop) — the `persona/roster` signal,
 * folded in so one read answers the panel.
 */
resident: boolean, 
/**
 * Last heartbeat, unix ms — the REAL recency stamp (the "9d ago" rows were
 * identity-creation dates being passed off as activity).
 */
last_seen_ms: number, 
/**
 * The node's stored portrait for this peer (`/avatars/<uuid>.png`,
 * rendered by `avatar/snapshot`'s Bevy pass). Carried HERE because the
 * presence stream's enrichment only rides changed-roster publishes, and
 * heartbeats are channel-scoped — a fossil roster never re-publishes, so
 * faces never landed (2026-08-31). The directory flows every poll.
 */
avatar_url?: string, };
