// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Factors contributing to priority
 */
export type PriorityFactors = { recency_score: number, mention_score: number, room_score: number, sender_score: number, voice_boost: number, };
