// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One item the source delivered, with the mechanic-grade rationale
 * flattened for the wire (content_preview, score, age_s, etc).
 */
export type RagInspectItem = { index: number, tokens: number, score: number, contentPreview: string, peerIdPrefix: string, lamport: number, ageS: number, };
