// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `persona/rag-inspect`. The persona name is the only
 * required input; everything else has defaults from the canonical
 * library `defaults_for`. Optional knobs let callers vary the
 * inspection profile (tighter window, deeper fetch, capture
 * trace).
 */
export type RagInspectParams = { 
/**
 * Which persona's RAG pipeline to introspect — her name or id (full or the
 * short form shown in rosters).
 */
persona: string, contextWindow?: number, aircFloor?: number, aircMax?: number, aircFetchLimit?: number, 
/**
 * Optional absolute path for the JSONL capture trace. When set,
 * the inspection records the full turn there so other AIs /
 * mechanic shop can replay it.
 */
tracePath?: string, 
/**
 * Optional override for the wall-clock timestamp the inspection
 * reasons against. Default: substrate's current wall-clock.
 * Set this for deterministic replay tests.
 */
nowMs?: number, 
/**
 * When true, chain through inference: assemble delivered items
 * into a prompt, call the persona's adapter, capture the
 * response into `modelResponse`. Default false (RAG-only).
 * Per [[inference-is-an-adapter-always-in-the-loop]] — closes
 * the introspection loop so AIs can answer "would I respond
 * as it requests?" in one command call.
 */
chainInference?: boolean, };
