// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The hold's state after this call.
 */
export type RosterHoldReport = { 
/**
 * Whether a hold now stands.
 */
active: boolean, 
/**
 * Allowed agent names while it stands (empty when inactive).
 */
only: Array<string>, 
/**
 * Unix ms when the hold lapses (0 when inactive).
 */
until_ms: number, 
/**
 * The recorded reason (empty when inactive).
 */
reason: string, 
/**
 * Human-readable summary of what this call did.
 */
detail: string, };
