// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Set, clear, or read the standing roster hold.
 */
export type RosterHoldParams = { 
/**
 * Agent names allowed to be hosted while the hold stands (e.g. ["Atlas"]).
 * Omit together with `clear` to just READ the current hold.
 */
only?: Array<string>, 
/**
 * How long the hold stands, in minutes (clamped to 1..=1440). Required
 * when `only` is given — an unbounded hold is a mystery outage waiting.
 */
minutes?: bigint, 
/**
 * Why — carried into every skip probe so a held-down fleet explains itself.
 */
reason?: string, 
/**
 * Remove any standing hold.
 */
clear: boolean, };
