#!/usr/bin/env npx tsx
/**
 * Sass Compilation Script
 *
 * Compiles .scss files in widgets/ to .styles.ts files that export CSS as a string.
 * This enables Sass in Shadow DOM widgets where CSS must be injected as a string.
 *
 * Usage:
 *   npx tsx scripts/compile-sass.ts [--watch]
 *
 * Structure:
 *   widgets/my-widget/styles/my-widget.scss
 *   → compiles to →
 *   widgets/my-widget/styles/my-widget.styles.ts
 *
 * The .styles.ts file exports:
 *   export const styles = `...compiled CSS...`;
 */

import * as sass from 'sass';
import * as fs from 'fs';
import * as path from 'path';

const WIDGETS_DIR = path.resolve(__dirname, '../widgets');
const SHARED_STYLES_DIR = path.join(WIDGETS_DIR, 'shared/styles');

interface CompileResult {
  source: string;
  output: string;
  success: boolean;
  error?: string;
}

/**
 * Find all .scss files in widgets directory (excluding partials that start with _)
 */
function findScssFiles(dir: string): string[] {
  const files: string[] = [];

  function walk(currentDir: string) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);

      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.isFile() && entry.name.endsWith('.scss') && !entry.name.startsWith('_')) {
        files.push(fullPath);
      }
    }
  }

  walk(dir);
  return files;
}

/**
 * Compile a single .scss file to both .styles.ts AND .css
 * - .styles.ts: For TypeScript imports (legacy widgets)
 * - .css: For HTTP fetch loading (external file pattern)
 */
function compileScssFile(scssPath: string): CompileResult {
  const stylesOutputPath = scssPath.replace(/\.scss$/, '.styles.ts');
  const cssOutputPath = scssPath.replace(/\.scss$/, '.css');

  try {
    // Compile SCSS with the shared styles directory as an import path
    const result = sass.compile(scssPath, {
      loadPaths: [SHARED_STYLES_DIR, path.dirname(scssPath)],
      style: 'compressed',
      sourceMap: false
    });

    // Generate TypeScript module that exports the CSS (for legacy imports)
    const tsContent = `/**
 * Auto-generated by compile-sass.ts
 * Source: ${path.basename(scssPath)}
 * DO NOT EDIT DIRECTLY - edit the .scss file instead
 */

export const styles = \`
${result.css}
\`;
`;

    fs.writeFileSync(stylesOutputPath, tsContent, 'utf-8');

    // Also write raw CSS file for HTTP fetch loading
    const cssContent = `/**
 * Auto-generated by compile-sass.ts
 * Source: ${path.basename(scssPath)}
 * DO NOT EDIT DIRECTLY - edit the .scss file instead
 */
${result.css}
`;
    fs.writeFileSync(cssOutputPath, cssContent, 'utf-8');

    return {
      source: scssPath,
      output: stylesOutputPath,
      success: true
    };
  } catch (error) {
    return {
      source: scssPath,
      output: stylesOutputPath,
      success: false,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}

/**
 * Main compilation function
 */
function compileSass(): void {
  console.log('🎨 Compiling SCSS files...\n');

  const scssFiles = findScssFiles(WIDGETS_DIR);

  if (scssFiles.length === 0) {
    console.log('  No .scss files found in widgets/');
    return;
  }

  let successCount = 0;
  let errorCount = 0;

  for (const scssFile of scssFiles) {
    const relativePath = path.relative(WIDGETS_DIR, scssFile);
    const result = compileScssFile(scssFile);

    if (result.success) {
      console.log(`  ✅ ${relativePath}`);
      successCount++;
    } else {
      console.log(`  ❌ ${relativePath}`);
      console.log(`     Error: ${result.error}`);
      errorCount++;
    }
  }

  console.log(`\n📊 Results: ${successCount} compiled, ${errorCount} errors`);

  if (errorCount > 0) {
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  const args = process.argv.slice(2);

  if (args.includes('--watch')) {
    console.log('👀 Watch mode not yet implemented. Running once...\n');
  }

  compileSass();
}

export { compileSass, compileScssFile, findScssFiles };
