// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionConfig } from "./CompactionConfig";

/**
 * Params for `plasticity/analyze`. `config` is a partial override (unspecified
 * fields fall back to `CompactionConfig::default()`); `targetSizeGb` is the
 * top-level convenience that merges into `config` when the latter omits it.
 */
export type AnalyzeParams = { 
/**
 * Path to the adapter directory containing `gate_gradients.json`.
 */
adapterPath: string, 
/**
 * Path to the base model artifact (`.gguf` file or a dir with `config.json`).
 * Architecture dims (hidden/intermediate/heads/context) are sourced from it —
 * a correct compaction plan requires the base model's real dimensions.
 */
modelPath: string, 
/**
 * CompactionConfig overrides (partial; unspecified fields use defaults).
 */
config: CompactionConfig, 
/**
 * Convenience: target compacted size in GB (used only when `config.targetSizeGb` is unset).
 */
targetSizeGb?: number, };
