// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionConfig } from "./CompactionConfig";

/**
 * Params for `plasticity/compact`.
 */
export type CompactParams = { 
/**
 * Path to the adapter directory containing `gate_gradients.json`.
 */
adapterPath: string, 
/**
 * Base model — a single `.safetensors` file OR a directory of
 * `model-NNNNN-of-NNNNN.safetensors` shards (auto-detected).
 */
modelPath: string, 
/**
 * Output path. Defaults to `<adapterPath>/compacted_model.safetensors`.
 */
outputPath?: string, 
/**
 * CompactionConfig overrides (partial; unspecified fields use defaults).
 */
config: CompactionConfig, 
/**
 * Convenience: target compacted size in GB (used only when `config.targetSizeGb` is unset).
 */
targetSizeGb?: number, };
