// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadPrecision } from "./HeadPrecision";

/**
 * Per-layer topology after compaction: which heads survived and at what precision.
 */
export type LayerTopology = { 
/**
 * Layer index in the original model
 */
layerIndex: number, 
/**
 * Number of active Q heads after compaction
 */
numHeads: number, 
/**
 * Number of active KV heads after compaction
 */
numKvHeads: number, 
/**
 * Which original Q head indices survived (ordered)
 */
retainedHeadIndices: Array<number>, 
/**
 * Which original KV head indices survived (ordered)
 */
retainedKvHeadIndices: Array<number>, 
/**
 * Per-retained-head precision assignment
 */
headPrecisions: Array<HeadPrecision>, 
/**
 * Per-retained-head utilization score (for debugging/display)
 */
headScores: Array<number>, };
