// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Memory budget breakdown — where bytes go in the compressed model.
 */
export type MemoryBudget = { 
/**
 * Embedding table bytes (token_embd + lm_head)
 */
embeddingBytes: number, 
/**
 * Attention projection bytes (Q, K, V, O across all layers)
 */
attentionBytes: number, 
/**
 * MLP bytes (gate, up, down across all layers)
 */
mlpBytes: number, 
/**
 * Norm + bias bytes (small, always F32)
 */
normBytes: number, 
/**
 * Total model weight bytes
 */
totalBytes: number, 
/**
 * KV cache estimate at full context (for headroom check)
 */
kvCacheMaxBytes: number, };
