// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary counts of head precision assignments across the whole model.
 */
export type PrecisionProfile = { removed: number, ternary: number, q2: number, q4: number, q8: number, bf16: number, };
