// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A head identified as saturated (candidate for mitosis/splitting).
 */
export type SaturatedHead = { layerIndex: number, headIndex: number, utilization: number, };
