#!/bin/bash
# Bluetooth Connection Monitor
# Logs all pairing attempts with full details

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="$SCRIPT_DIR/bluetooth-monitor.log"
EVIDENCE_DIR="$SCRIPT_DIR/bluetooth-evidence"
ALERT_ON_UNKNOWN=true

mkdir -p "$EVIDENCE_DIR"

log_event() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Capture current Bluetooth state
capture_bluetooth_state() {
    local timestamp=$(date +%s)
    local state_file="$EVIDENCE_DIR/bluetooth-state-$timestamp.txt"
    
    {
        echo "=== Bluetooth State Capture ==="
        echo "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        echo "=== Bluetooth Devices ==="
        system_profiler SPBluetoothDataType
        echo ""
        echo "=== Recent Bluetooth Logs (last 5 min) ==="
        log show --predicate 'subsystem == "com.apple.bluetooth"' --last 5m --style compact 2>/dev/null | tail -100
        echo ""
        echo "=== Bluetooth Preferences ==="
        defaults read /Library/Preferences/com.apple.Bluetooth 2>/dev/null || echo "Cannot read preferences"
    } > "$state_file"
    
    echo "$state_file"
}

# Monitor for connection attempts
monitor_connections() {
    log_event "Starting Bluetooth connection monitor..."
    log_event "Monitoring for unauthorized pairing attempts"
    log_event "Press Ctrl+C to stop"
    
    # Known legitimate devices (customize this list)
    KNOWN_DEVICES=(
        "C8:69:CD:59:EF:C4"  # Basement (2)
        "78:2B:64:9F:42:72"  # Ed phones
        "50:DE:06:8C:DC:62"  # family room
        "F4:21:CA:BF:6E:17"  # Joel Phone
        "48:E1:5C:8B:3F:FD"  # oled
        "5C:1B:F4:5A:7F:AC"  # police pods
    )
    
    # Stream Bluetooth logs in real-time
    log stream --predicate 'subsystem == "com.apple.bluetooth"' --style compact 2>/dev/null | while read -r line; do
        
        # Check for connection/pairing attempts
        if echo "$line" | grep -iE "connect|pair|request" > /dev/null; then
            
            # Extract device info if present
            device_id=$(echo "$line" | grep -oE '[0-9A-F]{2}(:[0-9A-F]{2}){5}|[A-Z0-9]{12}' | head -1)
            
            if [[ -n "$device_id" ]]; then
                # Check if device is known
                is_known=false
                for known in "${KNOWN_DEVICES[@]}"; do
                    if [[ "$device_id" == "$known" ]]; then
                        is_known=true
                        break
                    fi
                done
                
                if [[ "$is_known" == "false" ]]; then
                    log_event "⚠️  UNKNOWN DEVICE DETECTED: $device_id"
                    log_event "Log entry: $line"
                    
                    # Capture full state
                    state_file=$(capture_bluetooth_state)
                    log_event "State captured: $state_file"
                    
                    # Create incident report
                    incident_file="$EVIDENCE_DIR/incident-$device_id-$(date +%s).md"
                    cat > "$incident_file" << INCIDENT_EOF
# Bluetooth Connection Attempt - Unknown Device

**Timestamp**: $(date '+%Y-%m-%d %H:%M:%S')
**Device ID**: $device_id
**Status**: UNKNOWN/UNAUTHORIZED

## Log Entry
\`\`\`
$line
\`\`\`

## Known Legitimate Devices
$(printf '%s\n' "${KNOWN_DEVICES[@]}")

## Evidence Files
- State capture: $(basename "$state_file")
- Full system profile captured
- Bluetooth logs captured (last 5 minutes)

## Recommended Actions
1. Do NOT click "Connect"
2. Click "Ignore this device" if option available
3. Document the incident
4. Investigate device identity

---
Auto-generated by bluetooth-monitor.sh
INCIDENT_EOF
                    
                    log_event "Incident report: $incident_file"
                    
                    # Alert (macOS notification)
                    if [[ "$ALERT_ON_UNKNOWN" == "true" ]]; then
                        osascript -e "display notification \"Unknown Bluetooth device: $device_id\" with title \"🚨 Security Alert\" sound name \"Sosumi\"" 2>/dev/null
                    fi
                else
                    log_event "Known device activity: $device_id"
                fi
            fi
        fi
        
        # Log C08MRSEM2330 specifically (your persistent attacker)
        if echo "$line" | grep -i "C08MRSEM2330" > /dev/null; then
            log_event "🔴 ATTACKER DEVICE C08MRSEM2330 DETECTED"
            log_event "$line"
            
            state_file=$(capture_bluetooth_state)
            log_event "State captured: $state_file"
            
            osascript -e "display notification \"C08MRSEM2330 is trying to connect!\" with title \"🚨 KNOWN ATTACKER\" sound name \"Funk\"" 2>/dev/null
        fi
    done
}

# Capture current state on startup
log_event "=== Bluetooth Monitor Started ==="
initial_state=$(capture_bluetooth_state)
log_event "Initial state captured: $initial_state"

# Start monitoring
monitor_connections
