/**
 * Browser Structure Registry - Auto-generated on 2025-08-01T00:26:06.969Z
 * 
 * Contains browser-side daemon and command imports.
 * Generated by scripts/generate-structure.ts - DO NOT EDIT MANUALLY
 */

// Browser Daemon Imports
import { CommandDaemonBrowser } from '../daemons/command-daemon/browser/CommandDaemonBrowser';
import { ConsoleDaemonBrowser } from '../daemons/console-daemon/browser/ConsoleDaemonBrowser';
import { HealthDaemonBrowser } from '../daemons/health-daemon/browser/HealthDaemonBrowser';
import { SessionDaemonBrowser } from '../daemons/session-daemon/browser/SessionDaemonBrowser';
import { WidgetDaemonBrowser } from '../daemons/widget-daemon/browser/WidgetDaemonBrowser';

// Browser Command Imports
import { GetChatHistoryBrowserCommand } from '../commands/chat/get-chat-history/browser/GetChatHistoryBrowserCommand';
import { RoomEventBrowserCommand } from '../commands/chat/room-events/browser/RoomEventBrowserCommand';
import { SendMessageBrowserCommand } from '../commands/chat/send-message/browser/SendMessageBrowserCommand';
import { SendRoomEventBrowserCommand } from '../commands/chat/send-room-event/browser/SendRoomEventBrowserCommand';
import { ClickBrowserCommand } from '../commands/click/browser/ClickBrowserCommand';
import { CompileTypescriptBrowserCommand } from '../commands/compile-typescript/browser/CompileTypescriptBrowserCommand';
import { FileAppendBrowserCommand } from '../commands/file/append/browser/FileAppendBrowserCommand';
import { FileLoadBrowserCommand } from '../commands/file/load/browser/FileLoadBrowserCommand';
import { FileSaveBrowserCommand } from '../commands/file/save/browser/FileSaveBrowserCommand';
import { GetTextBrowserCommand } from '../commands/get-text/browser/GetTextBrowserCommand';
import { ListBrowserCommand } from '../commands/list/browser/ListBrowserCommand';
import { NavigateBrowserCommand } from '../commands/navigate/browser/NavigateBrowserCommand';
import { ProxyNavigateBrowserCommand } from '../commands/proxy-navigate/browser/ProxyNavigateBrowserCommand';
import { ScreenshotBrowserCommand } from '../commands/screenshot/browser/ScreenshotBrowserCommand';
import { ScrollBrowserCommand } from '../commands/scroll/browser/ScrollBrowserCommand';
import { TestErrorBrowserCommand } from '../commands/test-error/browser/TestErrorBrowserCommand';
import { TypeBrowserCommand } from '../commands/type/browser/TypeBrowserCommand';
import { WaitForElementBrowserCommand } from '../commands/wait-for-element/browser/WaitForElementBrowserCommand';

// Types
import type { DaemonEntry } from '../shared/DaemonBase';
import type { CommandEntry } from '../daemons/command-daemon/shared/CommandBase';

/**
 * Browser Environment Registry
 */
export const BROWSER_DAEMONS: DaemonEntry[] = [
  {
    name: 'CommandDaemon',
    className: 'CommandDaemonBrowser',
    daemonClass: CommandDaemonBrowser
  },
  {
    name: 'ConsoleDaemon',
    className: 'ConsoleDaemonBrowser',
    daemonClass: ConsoleDaemonBrowser
  },
  {
    name: 'HealthDaemon',
    className: 'HealthDaemonBrowser',
    daemonClass: HealthDaemonBrowser
  },
  {
    name: 'SessionDaemon',
    className: 'SessionDaemonBrowser',
    daemonClass: SessionDaemonBrowser
  },
  {
    name: 'WidgetDaemon',
    className: 'WidgetDaemonBrowser',
    daemonClass: WidgetDaemonBrowser
  }
];

export const BROWSER_COMMANDS: CommandEntry[] = [
  {
    name: 'chat/get-chat-history',
    className: 'GetChatHistoryBrowserCommand',
    commandClass: GetChatHistoryBrowserCommand
  },
  {
    name: 'chat/room-events',
    className: 'RoomEventBrowserCommand',
    commandClass: RoomEventBrowserCommand
  },
  {
    name: 'chat/send-message',
    className: 'SendMessageBrowserCommand',
    commandClass: SendMessageBrowserCommand
  },
  {
    name: 'chat/send-room-event',
    className: 'SendRoomEventBrowserCommand',
    commandClass: SendRoomEventBrowserCommand
  },
  {
    name: 'click',
    className: 'ClickBrowserCommand',
    commandClass: ClickBrowserCommand
  },
  {
    name: 'compile-typescript',
    className: 'CompileTypescriptBrowserCommand',
    commandClass: CompileTypescriptBrowserCommand
  },
  {
    name: 'file/append',
    className: 'FileAppendBrowserCommand',
    commandClass: FileAppendBrowserCommand
  },
  {
    name: 'file/load',
    className: 'FileLoadBrowserCommand',
    commandClass: FileLoadBrowserCommand
  },
  {
    name: 'file/save',
    className: 'FileSaveBrowserCommand',
    commandClass: FileSaveBrowserCommand
  },
  {
    name: 'get-text',
    className: 'GetTextBrowserCommand',
    commandClass: GetTextBrowserCommand
  },
  {
    name: 'list',
    className: 'ListBrowserCommand',
    commandClass: ListBrowserCommand
  },
  {
    name: 'navigate',
    className: 'NavigateBrowserCommand',
    commandClass: NavigateBrowserCommand
  },
  {
    name: 'proxy-navigate',
    className: 'ProxyNavigateBrowserCommand',
    commandClass: ProxyNavigateBrowserCommand
  },
  {
    name: 'screenshot',
    className: 'ScreenshotBrowserCommand',
    commandClass: ScreenshotBrowserCommand
  },
  {
    name: 'scroll',
    className: 'ScrollBrowserCommand',
    commandClass: ScrollBrowserCommand
  },
  {
    name: 'test-error',
    className: 'TestErrorBrowserCommand',
    commandClass: TestErrorBrowserCommand
  },
  {
    name: 'type',
    className: 'TypeBrowserCommand',
    commandClass: TypeBrowserCommand
  },
  {
    name: 'wait-for-element',
    className: 'WaitForElementBrowserCommand',
    commandClass: WaitForElementBrowserCommand
  }
];
