// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `mcp/tool-help`: the tool to describe (any accepted name form).
 */
export type McpToolHelpParams = { tool: string, };
