//! String templates for the files `generate/module` emits.
//!
//! Pure functions: input is `GenerateModuleParams`, output is the
//! rendered file contents. No I/O lives here — the caller in
//! [`super::GeneratorModule::generate_module_inner`] does the writes.
//! That keeps the templates testable in isolation and the I/O paths
//! easy to swap (e.g., a future "dry run" mode that prints rather than
//! writes).

use super::struct_name;
use super::types::GenerateModuleParams;

/// Render the canonical `mod.rs` template for a new module.
///
/// The output:
/// - is a compilable Rust file the moment the caller wires it into
///   the parent `modules/mod.rs`,
/// - declares a `pub struct <Name>Module` with `ServiceModule`
///   implemented,
/// - lists each declared command in `command_prefixes` AND in the
///   `handle_command` dispatch (as `Err`-returning stubs the author
///   fills in afterwards),
/// - subscribes to declared event globs.
pub fn mod_rs_template(params: &GenerateModuleParams) -> String {
    let name = &params.name;
    let description = &params.description;
    let struct_prefix = struct_name(name);
    let priority_variant = params.priority.as_variant_str();
    let command_prefixes = render_command_prefixes(name, &params.commands);
    let event_subscriptions = render_string_array(&params.events_subscribed);
    let command_dispatch_arms = render_command_dispatch_arms(&params.commands);
    let events_published_doc = render_published_events_doc(&params.events_published);

    format!(
        r#"//! {description}
//!
//! Auto-generated by `@continuum-modules/generator` via the
//! `generate/module` command. The author fills in real command
//! handlers in place of the `not yet implemented` stubs below.
//!
//! Commands provided: {commands_csv}
//! Events subscribed: {events_sub_csv}
//! Events published:  {events_pub_csv}
//!
//! See [docs/architecture/MODULE-ARCHITECTURE.md](../../../../../../docs/architecture/MODULE-ARCHITECTURE.md)
//! for the module pattern this scaffold follows.
{events_published_doc}

use async_trait::async_trait;
use serde_json::Value;

use crate::runtime::{{CommandResult, ModuleConfig, ModulePriority, ServiceModule}};

pub struct {struct_prefix}Module {{}}

impl {struct_prefix}Module {{
    pub fn new() -> Self {{
        Self {{}}
    }}
}}

impl Default for {struct_prefix}Module {{
    fn default() -> Self {{
        Self::new()
    }}
}}

#[async_trait]
impl ServiceModule for {struct_prefix}Module {{
    fn config(&self) -> ModuleConfig {{
        ModuleConfig {{
            name: "{name}",
            priority: ModulePriority::{priority_variant},
            command_prefixes: &[{command_prefixes}],
            event_subscriptions: &[{event_subscriptions}],
            needs_dedicated_thread: false,
            max_concurrency: 0,
            tick_interval: None,
        }}
    }}

    async fn initialize(
        &self,
        _ctx: &crate::runtime::ModuleContext,
    ) -> Result<(), String> {{
        Ok(())
    }}

    async fn handle_command(
        &self,
        command: &str,
        _params: Value,
    ) -> Result<CommandResult, String> {{
        match command {{
{command_dispatch_arms}
            other => Err(format!(
                "{{other}}: not handled by `{name}` module (auto-generated stub)"
            )),
        }}
    }}

    fn as_any(&self) -> &dyn std::any::Any {{
        self
    }}
}}
"#,
        description = description,
        struct_prefix = struct_prefix,
        name = name,
        priority_variant = priority_variant,
        command_prefixes = command_prefixes,
        event_subscriptions = event_subscriptions,
        command_dispatch_arms = command_dispatch_arms,
        events_published_doc = events_published_doc,
        commands_csv = csv_or_none(&params.commands),
        events_sub_csv = csv_or_none(&params.events_subscribed),
        events_pub_csv = csv_or_none(&params.events_published),
    )
}

/// Render the README the generator drops into the new module's
/// directory. Captures the same metadata as the mod.rs docstring, in
/// Markdown form, plus the explicit wire-up step the author still
/// needs to perform manually.
pub fn readme_template(params: &GenerateModuleParams) -> String {
    let name = &params.name;
    let description = &params.description;
    let struct_prefix = struct_name(name);

    let commands_md = render_md_list("Commands", &params.commands);
    let events_sub_md = render_md_list("Events subscribed", &params.events_subscribed);
    let events_pub_md = render_md_list("Events published", &params.events_published);

    format!(
        r#"# `{name}` module

{description}

Auto-generated by `@continuum-modules/generator`. See
[docs/architecture/MODULE-ARCHITECTURE.md](../../../../../../docs/architecture/MODULE-ARCHITECTURE.md)
for the module pattern.

## Contract

{commands_md}

{events_sub_md}

{events_pub_md}

## Author's next step

The scaffold compiles as soon as it's wired into the parent module:

```rust
// src/workers/continuum-core/src/modules/mod.rs
pub mod {name};
```

And registered at runtime startup:

```rust
runtime.register(Arc::new({struct_prefix}Module::new()));
```

After that, fill in real handlers in place of each command's
`not handled by ... (auto-generated stub)` arm in `mod.rs`.
"#,
        name = name,
        description = description,
        struct_prefix = struct_prefix,
        commands_md = commands_md,
        events_sub_md = events_sub_md,
        events_pub_md = events_pub_md,
    )
}

// ── helpers ──────────────────────────────────────────────────────────

/// Render the `command_prefixes` array literal. Strategy: emit each
/// declared command exactly (e.g., `"chat/send"`) AND the module's
/// `name/` prefix so future commands under the same prefix route
/// through this module without re-running the generator. If the
/// caller declares no commands, the prefix alone is enough.
fn render_command_prefixes(name: &str, commands: &[String]) -> String {
    let mut entries: Vec<String> = commands.iter().map(|c| format!("\"{c}\"")).collect();
    let prefix = format!("\"{name}/\"");
    if !entries.contains(&prefix) {
        entries.push(prefix);
    }
    entries.join(", ")
}

fn render_string_array(items: &[String]) -> String {
    items
        .iter()
        .map(|s| format!("\"{s}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_command_dispatch_arms(commands: &[String]) -> String {
    if commands.is_empty() {
        return String::new();
    }
    commands
        .iter()
        .map(|cmd| {
            format!(
                "            \"{cmd}\" => Err(\"{cmd}: not yet implemented in this scaffolded module\".to_string()),"
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_published_events_doc(events: &[String]) -> String {
    if events.is_empty() {
        return String::new();
    }
    let mut s = String::from("//!\n//! Documented published events (no runtime wiring; \n//! publishers emit at their own pace):\n");
    for e in events {
        s.push_str(&format!("//!   - `{e}`\n"));
    }
    s
}

fn render_md_list(title: &str, items: &[String]) -> String {
    if items.is_empty() {
        format!("## {title}\n\n_None declared._")
    } else {
        let mut s = format!("## {title}\n\n");
        for it in items {
            s.push_str(&format!("- `{it}`\n"));
        }
        s
    }
}

fn csv_or_none(items: &[String]) -> String {
    if items.is_empty() {
        "(none)".to_string()
    } else {
        items.join(", ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::modules::generator::types::PrioritySpec;

    fn sample_params() -> GenerateModuleParams {
        GenerateModuleParams {
            name: "demo".into(),
            description: "Sample module for template tests".into(),
            commands: vec!["demo/echo".into(), "demo/ping".into()],
            events_subscribed: vec!["data:demo_items:created".into()],
            events_published: vec!["demo:event:emitted".into()],
            priority: PrioritySpec::Normal,
            force: false,
        }
    }

    #[test]
    fn mod_rs_contains_struct_definition_and_trait_impl() {
        let s = mod_rs_template(&sample_params());
        assert!(s.contains("pub struct DemoModule"));
        assert!(s.contains("impl ServiceModule for DemoModule"));
        assert!(s.contains("ModulePriority::Normal"));
    }

    #[test]
    fn mod_rs_lists_each_declared_command_in_prefix_and_dispatch() {
        let s = mod_rs_template(&sample_params());
        assert!(
            s.contains("\"demo/echo\""),
            "echo command must appear in prefixes and dispatch"
        );
        assert!(
            s.contains("\"demo/ping\""),
            "ping command must appear in prefixes and dispatch"
        );
        assert!(
            s.contains("\"demo/echo\" => Err"),
            "stub dispatch arm must surface the unimplemented error"
        );
    }

    #[test]
    fn mod_rs_includes_module_name_prefix_in_command_prefixes() {
        let s = mod_rs_template(&sample_params());
        // The synthesized "demo/" prefix lets future commands under
        // this module route through it without re-running the
        // generator.
        assert!(
            s.contains("\"demo/\""),
            "module-name prefix must appear in command_prefixes: {s}"
        );
    }

    #[test]
    fn mod_rs_subscribes_to_declared_events() {
        let s = mod_rs_template(&sample_params());
        assert!(s.contains("\"data:demo_items:created\""));
    }

    #[test]
    fn mod_rs_documents_published_events_in_module_docstring() {
        let s = mod_rs_template(&sample_params());
        assert!(
            s.contains("Documented published events"),
            "published-events doc block must appear"
        );
        assert!(s.contains("`demo:event:emitted`"));
    }

    #[test]
    fn mod_rs_for_command_less_module_still_compiles_shape() {
        let mut p = sample_params();
        p.commands.clear();
        let s = mod_rs_template(&p);
        // Even with no commands, the prefix must be there so the
        // module is dispatchable for whatever the author adds later.
        assert!(s.contains("\"demo/\""));
        // The dispatch arm block is empty, and the catch-all stays.
        assert!(s.contains("other => Err"));
    }

    #[test]
    fn readme_lists_declared_contract() {
        let s = readme_template(&sample_params());
        assert!(s.contains("# `demo` module"));
        assert!(s.contains("- `demo/echo`"));
        assert!(s.contains("- `demo/ping`"));
        assert!(s.contains("- `data:demo_items:created`"));
        assert!(s.contains("- `demo:event:emitted`"));
        assert!(
            s.contains("pub mod demo;"),
            "README must spell out the wire-up step"
        );
        assert!(
            s.contains("DemoModule::new()"),
            "README must reference the actual struct name"
        );
    }

    #[test]
    fn readme_handles_empty_lists_gracefully() {
        let mut p = sample_params();
        p.commands.clear();
        p.events_subscribed.clear();
        p.events_published.clear();
        let s = readme_template(&p);
        assert!(
            s.contains("_None declared._"),
            "empty contract sections must render a 'None declared' note"
        );
    }
}
