// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `avatar/snapshot`.
 */
export type AvatarSnapshotParams = { 
/**
 * Persona identity (uniqueId) to render — selects the VRM model and the
 * output filename (`~/.continuum/avatars/<identity>.png`).
 */
identity: string, 
/**
 * Render width in pixels. Defaults to 480.
 */
width?: number, 
/**
 * Render height in pixels. Defaults to 480.
 */
height?: number, 
/**
 * Re-render even if a snapshot already exists on disk.
 */
force: boolean, };
