// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `avatar/snapshot`.
 */
export type AvatarSnapshotResult = { 
/**
 * HTTP path the rendered PNG is served at (`/avatars/<identity>.png`).
 */
path: string, 
/**
 * `true` when an existing on-disk snapshot was returned without re-rendering.
 */
cached: boolean, };
