//! Per-persona airc runtime — the substrate piece that makes a
//! persona a first-class airc citizen.
//!
//! ### Doctrine
//!
//! Per memory `personas-are-citizens-airc-is-identity-provider`: a
//! persona is NOT a continuum-internal queue row fronted by a
//! broker. It's a citizen on the substrate — same kind as Joel-at-
//! a-terminal, Claude-in-a-tab, OpenClaw, Hermes. Each persona
//! gets:
//!
//! - Its own `$AIRC_HOME` under `~/.continuum/personas/<name>/airc/`
//!   — NOT inside any other scope's airc home, to keep the citizen
//!   a peer rather than a sub-citizen of continuum's own scope.
//! - Its own Ed25519 identity, generated by airc-lib's
//!   `LocalIdentity::load_or_generate_as` (transitively, via
//!   `Airc::attach_as`). Continuum does not mint, store, or sign
//!   with persona keys — that's airc's job entirely.
//! - Its own `airc_lib::Airc` handle obtained via
//!   `Airc::attach_as(home, agent_name, socket)` — daemon-connected
//!   so the persona can `subscribe()` to live rooms and `say()` /
//!   `publish()` under its own peer_id.
//! - Membership in the same continuum room Joel publishes into
//!   (per "I expect your general room and theirs to be the same
//!   room").
//!
//! ### What this module IS
//!
//! - A lifecycle handle holding the persona's `Arc<airc_lib::Airc>`
//!   and the join handle of its inbound pump task.
//! - A `bootstrap` constructor that does the airc-side identity
//!   ceremony + room-join + inbound subscription, all through
//!   airc-lib's public surface (no shelling out to `airc init`).
//! - A `publish_text` helper delegating to `Airc::say` — the same
//!   shape `airc msg` uses, no continuum-side wrapping.
//!
//! ### What this module is NOT
//!
//! Per the anti-patterns the design workflow named for refusal:
//!
//! - NOT a "ChatService::sendAs(persona_id, text)" — there's no
//!   public method that takes a persona_id and routes internally.
//!   Whoever calls `publish_text` already HAS the persona's
//!   runtime handle. The "persona-id keyed dispatch" lives in the
//!   registry (one level up), not in this struct.
//! - NOT a translation layer from `TranscriptEvent` to a continuum-
//!   internal `ChatMessage` shape. Events surface in their native
//!   airc form for downstream consumers to dispatch on.
//! - NOT a holder of the persona's secret key. The keypair lives
//!   inside the `Airc` handle (delegating to airc-identity) — this
//!   struct only holds the Arc.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use airc_core::{EventId, PeerId, RoomId};
use airc_lib::{Airc, AircError, DEFAULT_HEARTBEAT_INTERVAL};

/// The room a FRESH citizen scope lands in (room-consolidation master
/// card daa01102, Joel: academy is THE default room — training,
/// benchmarks, and the commons all root there; `#general` was airc's
/// generic lobby, and citizens landing in it is the "disorganized
/// non-academy room stuff" the consolidation kills). Passed to
/// `Airc::current_room_landing_in` at bootstrap; an ESTABLISHED
/// persona's durable membership always wins, so changing this never
/// migrates a living citizen.
pub const CITIZEN_COMMONS_ROOM: &str = "academy";

/// Abort-on-drop guard for the continuum-owned heartbeat pump (#260): keeps
/// the airc `HeartbeatTask` teardown contract — dropping the runtime aborts
/// the pump so a torn-down persona ages out of the roster within the
/// presence window (honest "no longer here"), never beats past her death.
struct AbortOnDrop(tokio::task::JoinHandle<()>);

impl Drop for AbortOnDrop {
    fn drop(&mut self) {
        self.0.abort();
    }
}
use tokio::task::JoinHandle;
use tracing::{info, warn};
use uuid::Uuid;

/// How long a bootstrap-time "resumed — holding: <cards>" Busy availability
/// stays live on the board before it must be renewed by real activity.
/// Matches the manager-hat lease default (15 min): long enough that a
/// freshly woken persona reads as present through her first few cadence
/// cycles, short enough that a persona that dies right after boot ages off
/// the board instead of showing Busy forever.
const RESUME_AVAILABILITY_TTL_MS: u64 = 900_000;

/// Errors that can occur during persona airc-runtime bootstrap.
///
/// Each variant carries enough context for the operator to act —
/// pinning identity manually, fixing the daemon socket, etc. — per
/// the constitutional-design memory's "every error has a path
/// forward" doctrine.
#[derive(Debug, thiserror::Error)]
pub enum PersonaAircRuntimeError {
    #[error(
        "legacy persona home detected at {legacy:?} — Slice 4 of #142 moved \
         personas under `citizens/personas/<name>/airc/`. To migrate this \
         persona's identity AND keep its peer_id stable, run:\n\
         \n  mkdir -p {new_parent:?} && mv {legacy:?} {new:?}\n\n\
         Then re-run. Per [[no-fallbacks-ever]] the substrate refuses to \
         silently use the legacy path."
    )]
    LegacyLayoutDetected {
        legacy: PathBuf,
        new: PathBuf,
        new_parent: PathBuf,
    },
    #[error("failed to create persona airc home {0}: {1}")]
    HomeCreate(PathBuf, std::io::Error),
    #[error("airc-lib attach_as failed for persona {agent_name:?} at {home:?}: {source}")]
    Attach {
        agent_name: String,
        home: PathBuf,
        #[source]
        source: AircError,
    },
    #[error(
        "failed to resolve persona {agent_name:?}'s home room from her durable \
         subscription state: {source} — a persona's rooms come from HER OWN airc \
         home (fresh scopes land in the citizen commons, #academy — daa01102), \
         never from the operator's current room (#298)"
    )]
    HomeRoom {
        agent_name: String,
        #[source]
        source: AircError,
    },
    #[error(
        "failed to install command inbound pump for persona {agent_name:?}: {source} — \
         the persona's airc handle subscribe failed, so the persona would be \
         silently unaddressable for cross-grid commands. Per [[no-fallbacks-ever]] \
         the substrate refuses to declare the persona ready in this state."
    )]
    CommandPumpInstall {
        agent_name: String,
        #[source]
        source: AircError,
    },
    #[error(
        "failed to build the capability-grant authorizer for persona {agent_name:?}: \
         {source} — the persona could not stand up its grant verifier (own key / mesh / \
         durable watermark), so it could not safely honor presented grants. Per \
         [[no-fallbacks-ever]] the substrate refuses to declare the persona ready \
         rather than fall back to an unverified or non-durable grant path."
    )]
    GrantAuthorizerBuild {
        agent_name: String,
        #[source]
        source: crate::persona::command_inbound_pump::GrantAuthorizerBuildError,
    },
    #[error(
        "PersonaInstanceManagerModule::bootstrap_one for {agent_name:?} ran before \
         the substrate `CommandExecutor` was installed — boot ordering bug. \
         `start_server` must call `install_executor_on_all` BEFORE accepting any \
         `persona/instances/bootstrap` dispatch. Per [[no-fallbacks-ever]]: surfaces \
         as a typed bootstrap failure rather than a panic in the deleted \
         `executor()` global accessor (task #224)."
    )]
    ExecutorNotInstalled { agent_name: String },
}

/// One persona's live airc connection.
///
/// Holds the persona's `Arc<Airc>` (its grid presence — identity +
/// daemon connection + room membership) and the inbound pump task
/// handle. Drop this struct to shut the persona's airc presence
/// down cleanly.
pub struct PersonaAircRuntime {
    persona_id: Uuid,
    agent_name: String,
    home: PathBuf,
    airc: Arc<Airc>,
    default_room: RoomId,
    /// Bumped by [`Self::join_room`] whenever this citizen's room membership
    /// GROWS at runtime. The perception stream's rebuild cue (P0 20b44763):
    /// airc-lib's `subscribe_subscribed_filtered` snapshots the subscribed
    /// channel list ONCE at subscribe time, so a room joined after `prime()`
    /// (benchmark dispatch moving assignees into a fresh run room) never
    /// enters an existing stream — the run room is born deaf. Watchers of
    /// [`AircCitizen::membership_epoch`] re-open their stream when this moves.
    membership_epoch: tokio::sync::watch::Sender<u64>,
    inbound_handle: Option<JoinHandle<()>>,
    /// Per-persona command inbound pump (task #222). When `Some`,
    /// this persona's airc handle is wired to receive cross-grid
    /// `AircCommandRequest` envelopes — peer_b can dispatch
    /// `airc://<this-persona-uuid>/ai/generate` and the substrate
    /// answers via the substrate's CommandExecutor. `None` only on
    /// `from_attached` paths where the caller opted out of the pump
    /// (test/demo fixtures); production `bootstrap` always installs
    /// it — if subscribe fails we hard-error per
    /// `[[no-fallbacks-ever]]`, never declaring a silently-
    /// unaddressable persona ready.
    command_pump: Option<crate::persona::command_inbound_pump::PersonaCommandInboundPump>,
    /// The airc `Alive` heartbeat pump (`start_agent_heartbeat`). A persona is
    /// only PRESENT in another citizen's `room_roster` while it emits `Alive`
    /// heartbeats — airc's `active_agents` reduces heartbeat events, NOT `say()`
    /// messages. Holding this handle keeps the pump running for the persona's
    /// lifetime; dropping it on teardown aborts the pump, so the persona ages
    /// out of the roster within the presence window — the honest "no longer
    /// here" signal. `None` only on `from_attached` paths (tests/demo) that opt
    /// out of presence. Without it, co-resident personas never see each other in
    /// `[Present in this room]` — the roster-grounding-goes-dark bug.
    heartbeat: Option<AbortOnDrop>,
    /// Periodic re-publisher of this persona's airc identity CARD (name + role +
    /// bio + avatar), on the heartbeat cadence — BigMama's half of #262, adopted
    /// (cherry-pick 1225f2eee): the card is a one-shot emit at attach; a peer that
    /// joins the room LATER (a desktop reconnecting, a fresh grid peer) missed it
    /// and would render `peer-<uuid>` + default glyph forever. This task re-emits
    /// the card every cadence so any late arrival is grounded by name within a
    /// heartbeat window. `None` on `from_attached` (tests/demo). Held for the
    /// persona's lifetime; aborted on drop, like the heartbeat pump.
    identity_republish: Option<JoinHandle<()>>,
    /// Where this citizen's identity came from — resumed from disk
    /// vs freshly minted. Carried for the lifetime of the runtime so
    /// telemetry surfaces (list/get IPC, future status panels) can
    /// distinguish without re-deriving from disk. Per
    /// [[substrate-is-a-good-citizen-on-the-host]]: observability
    /// honest.
    source: crate::persona::identity_provider::PersonaIdentitySource,
}

/// Build the airc identity CARD a hosted persona publishes to its rooms, from her
/// durable [`PersonaCard`](crate::persona::card::PersonaCard) (the seed's identity).
///
/// continuum-core publishes this ON THE PERSONA'S BEHALF — a hosted persona can't
/// run `airc identity set` herself — so every peer's `RoomRosterSource`
/// (continuum#1650, the M5 desktop roster fold) renders her by NAME + role + bio +
/// avatar instead of a bare `peer-<uuid>` + default glyph.
///
/// `kind=persona` is NOT an airc `Identity` field (the struct has none); it rides
/// the `Alive` heartbeat's `runtime="persona"` tag. We ALSO mirror it into
/// `integrations["continuum_kind"]` for a consumer that reads the card directly,
/// alongside the persona id and the avatar ref (the avatar rides `integrations`
/// exactly as the desktop expects).
fn persona_identity_card(
    card: &crate::persona::card::PersonaCard,
    kind_label: &str,
) -> airc_core::identity::Identity {
    let mut integrations = std::collections::BTreeMap::new();
    integrations.insert(
        "continuum_persona_id".to_string(),
        card.persona_id.to_string(),
    );
    integrations.insert("continuum_kind".to_string(), kind_label.to_string());
    if let Some(vrm) = card.avatar_vrm.as_deref() {
        integrations.insert("avatar_vrm".to_string(), vrm.to_string());
    }
    airc_core::identity::Identity {
        name: card.agent_name.clone(),
        pronouns: card.pronouns().short(),
        // `RoleId` serializes snake_case ("helper"); empty when the seed predates
        // role threading — the persona is still named, just role-less on the wire.
        role: card
            .role
            .map(|r| r.as_str().to_string())
            .unwrap_or_default(),
        // The self-authored bio lives in the OPEN profile map; empty when unset.
        bio: card.profile.get("bio").cloned().unwrap_or_default(),
        integrations,
        // `status` (away) and `fingerprint` (pubkey-derived, computed by airc
        // tooling) are not authored here — Default leaves them empty.
        ..Default::default()
    }
}

impl PersonaAircRuntime {
    /// Bootstrap a persona's airc presence.
    ///
    /// Steps:
    ///
    /// 1. Resolve the persona's home under `continuum_root/personas/
    ///    <agent_name>/airc/` and create it if absent.
    /// 2. Call `Airc::attach_as(home, agent_name, daemon_socket)`.
    ///    Internally this runs the airc-lib identity ceremony
    ///    (generate or load Ed25519 keypair, write `identity.key`,
    ///    record the local_identity row) and attaches a daemon
    ///    client for live publish + subscribe. No shelling out.
    /// 3. Resolve her HOME room via
    ///    `Airc::current_room_landing_in(CITIZEN_COMMONS_ROOM)` — her
    ///    OWN durable subscription default; a fresh scope lands in the
    ///    citizen commons `#academy` (daa01102) instead of airc's
    ///    generic `#general` lobby. This makes the persona appear on
    ///    `airc peers` as an enrolled participant of HER room — never
    ///    the operator's (#298).
    /// 4. Install the per-persona command inbound pump
    ///    ([`PersonaCommandInboundPump`](crate::persona::command_inbound_pump))
    ///    so this persona's airc handle starts receiving cross-grid
    ///    `AircCommandRequest` envelopes. The pump dispatches each
    ///    envelope through the supplied `executor`, which is
    ///    typically the substrate's process-global
    ///    [`runtime::command_executor::executor()`](crate::runtime::command_executor::executor).
    ///    Per `[[no-fallbacks-ever]]`: if `subscribe()` fails inside
    ///    pump install, bootstrap returns
    ///    [`PersonaAircRuntimeError::CommandPumpInstall`] — the
    ///    substrate refuses to declare a silently-unaddressable
    ///    persona ready. Task #222 lands this; before that, a
    ///    persona's bootstrap returned Ok even though peer_b's
    ///    cross-grid dispatches would have timed out.
    ///
    /// Returns the runtime handle. On any failure surfaces a typed
    /// `PersonaAircRuntimeError` with an actionable remedy in the
    /// message — never a silent fallback.
    pub async fn bootstrap(
        persona_id: Uuid,
        agent_name: impl Into<String>,
        continuum_root: &Path,
        daemon_socket: PathBuf,
        source: crate::persona::identity_provider::PersonaIdentitySource,
        executor: Arc<crate::runtime::command_executor::CommandExecutor>,
    ) -> Result<Self, PersonaAircRuntimeError> {
        Self::bootstrap_as(
            crate::identity::IdentityKind::Persona,
            None,
            persona_id,
            agent_name,
            continuum_root,
            daemon_socket,
            source,
            executor,
        )
        .await
    }

    /// [`Self::bootstrap`] generalized over the citizen KIND — the operator
    /// self-peer (#27) boots the SAME runtime as a persona (identity keypair,
    /// daemon attach, transcript/roster readers) homed under its own kind dir
    /// (`citizens/humans/<label>/airc/`), so it can never be mistaken for a
    /// citizen by the persona resumer or the roster.
    pub async fn bootstrap_as(
        kind: crate::identity::IdentityKind,
        // Agent kinds REQUIRE a provider (citizens/agents/<provider>/<label>/);
        // every other kind passes None (citizen_path enforces the contract).
        provider: Option<&str>,
        persona_id: Uuid,
        agent_name: impl Into<String>,
        continuum_root: &Path,
        daemon_socket: PathBuf,
        source: crate::persona::identity_provider::PersonaIdentitySource,
        executor: Arc<crate::runtime::command_executor::CommandExecutor>,
    ) -> Result<Self, PersonaAircRuntimeError> {
        let agent_name = agent_name.into();
        // Slice 4 of #142: symmetric citizens/<kind>/<label>/airc/
        // layout. Use the shared helper so every actor kind shares
        // the same path schema.
        let home = crate::context::citizen_home_path(
            continuum_root,
            kind,
            provider,
            &agent_name,
        );

        // Migration: refuse to use the pre-Slice-4 layout. Hard-error
        // with the exact `mv` command per [[no-fallbacks-ever]].
        if let Some(legacy) = crate::context::legacy_home_path(
            continuum_root,
            kind,
            &agent_name,
        ) {
            if tokio::fs::try_exists(&legacy).await.unwrap_or(false) {
                let new_parent = home
                    .parent()
                    .map(|p| p.to_path_buf())
                    .unwrap_or_else(|| home.clone());
                return Err(PersonaAircRuntimeError::LegacyLayoutDetected {
                    legacy,
                    new: home.clone(),
                    new_parent,
                });
            }
        }

        tokio::fs::create_dir_all(&home)
            .await
            .map_err(|e| PersonaAircRuntimeError::HomeCreate(home.clone(), e))?;

        // ── #199 Slice 1b: supply persona_id AS the airc peer_id ─────────
        //
        // Continuum derives the persona's `agent_name` (and thus her home
        // dir) from `persona_id` BEFORE attach. By handing `persona_id` to
        // airc's identity mint (`attach_as_with_peer_id`), airc adopts it as
        // the peer_id on a FRESH mint, so `airc.peer_id() == persona_id ==
        // the seed her name was derived from` — coherent identity from birth
        // ([[airc-peer-id-is-random-stored-not-keypair-derived]]). A RESUMED
        // persona (key + row already on disk) loads her STORED peer_id and
        // the supplied id is ignored — never a rotation — so the living
        // personas keep their identity across this change.
        let airc = Airc::attach_as_with_peer_id(
            home.clone(),
            agent_name.clone(),
            daemon_socket,
            PeerId::from_uuid(persona_id),
        )
        .await
        .map_err(|source| PersonaAircRuntimeError::Attach {
            agent_name: agent_name.clone(),
            home: home.clone(),
            source,
        })?;

        // ── The persona_id == peer_id invariant (guardrail) ──────────────
        //
        // The substrate keys everything downstream of bootstrap (the command
        // inbound pump, roster presence, registry) by `runtime.persona_id()`,
        // which MUST equal the airc peer_id the pump's envelopes address. Post
        // Slice 1b a FRESH mint satisfies this by construction (we supplied
        // persona_id as the peer_id, so the reseat below is a proven no-op),
        // and a RESUMED persona already stored `persona_id == peer_id` at her
        // first mint, so it is a no-op there too. The reseat remains as the
        // guardrail: if a home's stored identity ever diverges from the
        // supplied id (manual tampering, a pre-Slice-1b legacy divergence),
        // the runtime keys by the ACTUAL cryptographic identity, never a
        // stale input. It fires at `debug!` — silent in the coherent case.
        // KIND → wire labels: the heartbeat's runtime tag and the card's
        // continuum_kind. "interactive" is the projection's one Human marker
        // (SenderKind::from_runtime) — the operator self-peer rendering as a
        // persona/agent was the who-panel's you-vs-joel confusion.
        let (runtime_label, kind_label) = match kind {
            crate::identity::IdentityKind::Human => ("interactive", "human"),
            crate::identity::IdentityKind::Agent => ("agent", "agent"),
            _ => ("persona", "persona"),
        };
        let peer_id_uuid = airc.peer_id().as_uuid();
        if persona_id != peer_id_uuid {
            tracing::debug!(
                input_persona_id = %persona_id,
                peer_id = %peer_id_uuid,
                agent_name = %agent_name,
                "PersonaAircRuntime::bootstrap: supplied persona_id diverges from the \
                 stored peer_id (a resumed home minted before Slice 1b) — keying by the \
                 cryptographic peer_id per the persona_id == peer_id invariant."
            );
        }
        let persona_id = peer_id_uuid;

        info!(
            persona_id = %persona_id,
            agent_name = %agent_name,
            peer_id = %airc.peer_id(),
            client_id = %airc.client_id(),
            home = %home.display(),
            "PersonaAircRuntime bootstrap: identity ready (persona_id == peer_id post-collapse)"
        );

        // Resolve the persona's HOME room from her OWN durable
        // subscription state — never from the operator's focus.
        //
        // Task #298 (Joel: "we can't launch with these hacked rooms"):
        // bootstrap used to join the room the OPERATOR's daemon happened
        // to have current (`airc room` discovery), so every persona born
        // on a machine was dumped into whatever coordination room the
        // human/agent CLI last focused — live-found with the whole
        // resident population squatting in a FINISHED ACTIVITY room,
        // because the operator scope happened to be parked there. (A room
        // is an activity with a done-condition, not a standing channel;
        // parking citizens in one whose activity ended is how a fleet
        // ends up with nothing to do and no way to say why.)
        // A persona is her own airc peer with her own home dir;
        // `current_room_landing_in` loads HER durable subscription set
        // (the same state `Airc::join` writes), returns her established
        // default, and on a FRESH scope lands her in the citizen
        // commons `#academy` (CITIZEN_COMMONS_ROOM, card daa01102 —
        // airc's own `current_room` lobby stays `#general`; continuum's
        // citizens root in the academy tree): subscribe, set default,
        // publish presence + identity card. Resumed personas keep their
        // real membership; only new minds land in the commons. The
        // operator's current-room pointer no longer exists on this path.
        let room = airc
            .current_room_landing_in(CITIZEN_COMMONS_ROOM)
            .await
            .map_err(|source| PersonaAircRuntimeError::HomeRoom {
                agent_name: agent_name.clone(),
                source,
            })?;

        info!(
            persona_id = %persona_id,
            agent_name = %agent_name,
            peer_id = %airc.peer_id(),
            joined_room = %room.channel.as_uuid(),
            room_name = %room.name,
            "PersonaAircRuntime bootstrap: joined room"
        );

        // Task #222: install the command inbound pump so this
        // persona becomes a real command-callable peer on the grid.
        // Per [[no-fallbacks-ever]]: subscribe failure is bootstrap
        // failure — we refuse to declare the persona ready while it
        // would silently ignore cross-grid command envelopes.
        let airc_arc = Arc::new(airc);
        let grant_authorizer =
            crate::persona::command_inbound_pump::build_grant_authorizer(&airc_arc, &home)
                .await
                .map_err(|source| PersonaAircRuntimeError::GrantAuthorizerBuild {
                    agent_name: agent_name.clone(),
                    source,
                })?;
        let command_pump = crate::persona::command_inbound_pump::PersonaCommandInboundPump::spawn(
            persona_id,
            Arc::clone(&airc_arc),
            executor,
            grant_authorizer,
        )
        .await
        .map_err(|source| PersonaAircRuntimeError::CommandPumpInstall {
            agent_name: agent_name.clone(),
            source,
        })?;

        info!(
            persona_id = %persona_id,
            agent_name = %agent_name,
            "PersonaAircRuntime bootstrap: command inbound pump installed — \
             persona is now addressable for cross-grid commands"
        );

        // airc#1222 spawn contract: attach_as → join → subscribe →
        // publish_identity. Now that the persona is attached, joined, and
        // subscribed (the pump above), publish its identity card so it is
        // grounded by NAME on the wire, not an anonymous peer-id. This is
        // the continuum half of the contract; it's what lets every peer's
        // RoomRosterSource (continuum#1650) resolve this persona's display
        // name from the IdentityPublished event this emits. Seeds from the
        // agent-name floor.
        //
        // WARN-and-continue, not fatal — asymmetric with the subscribe
        // failure above (which IS fatal): a deaf persona is useless, but an
        // anonymous-but-functional one is fine — it appears by peer-id in
        // rosters until its identity card propagates / is re-published.
        // Publish her FULL identity card (name + pronouns + role + bio +
        // avatar-in-integrations), not just the agent-name floor. `publish_identity`
        // alone seeds ONLY the name; M5's desktop roster needs the whole card
        // (display_name + kind + role + bio + avatar) to render "Kimi" with her face
        // instead of "peer-<uuid>" + default glyph. Source it from her durable
        // PersonaCard — the seed.json one directory up from the airc home
        // (citizens/personas/<name>/seed.json vs …/<name>/airc/). WARN-and-continue:
        // a card that didn't publish leaves her anonymous-but-functional, so fall
        // back to the name-floor publish so she is at least NAMED.
        let seed_path = home
            .parent()
            .map(|p| p.join("seed.json"))
            .unwrap_or_else(|| home.join("seed.json"));
        match crate::persona::seed::read_seed(&seed_path).await {
            Ok(seed) => {
                let identity = persona_identity_card(&seed.card(), kind_label);
                match airc_arc.set_local_identity_card(identity).await {
                    Ok(()) => info!(
                        persona_id = %persona_id,
                        agent_name = %agent_name,
                        "PersonaAircRuntime bootstrap: full identity card published \
                         (name + role + bio + avatar) — named for every peer's roster"
                    ),
                    Err(source) => warn!(
                        persona_id = %persona_id,
                        agent_name = %agent_name,
                        error = %source,
                        "PersonaAircRuntime bootstrap: set_local_identity_card failed — \
                         persona appears by peer-id until her card propagates"
                    ),
                }
            }
            Err(source) => {
                warn!(
                    persona_id = %persona_id,
                    agent_name = %agent_name,
                    seed = %seed_path.display(),
                    error = %source,
                    "PersonaAircRuntime bootstrap: seed read failed — publishing the \
                     name-floor card only (no role/bio/avatar)"
                );
                if let Err(source) = airc_arc.publish_identity().await {
                    warn!(
                        persona_id = %persona_id,
                        agent_name = %agent_name,
                        error = %source,
                        "PersonaAircRuntime bootstrap: name-floor publish_identity also \
                         failed — persona will appear by peer-id until it propagates"
                    );
                }
            }
        }

        // Presence contract: a persona is PRESENT in another citizen's
        // `room_roster` only while it emits `Alive` heartbeats — airc's
        // `active_agents` reduces heartbeat events, not `say()` messages.
        // Publishing the identity card alone (above) resolves the persona's
        // NAME but leaves it absent from `active_agents`, so co-resident
        // personas never see each other in the `[Present in this room]`
        // grounding block. Start the `Alive` pump (runtime "persona") so the
        // persona is a visible present citizen. WARN-and-continue, symmetric
        // with publish_identity: a persona that can't heartbeat is
        // live-but-roster-invisible — degraded, not dead — never a silent
        // fallback ([[fallbacks-are-illegal-fail-loud]]: the cause is named).
        // #260 honest presence: the beat carries LIVE availability derived
        // per tick from real serving state, not a spawn-time snapshot —
        // `away` while her lane is still loading (warming), `ready` once
        // /health answers. The interface must never show a green dot for a
        // mind that cannot yet answer (Joel: "online = able to respond").
        // Continuum owns this pump (airc's `start_agent_heartbeat` freezes
        // availability at spawn); the first beat fires immediately so she is
        // visible-as-warming from second one, and a beat is emitted on every
        // tick thereafter (same DEFAULT_HEARTBEAT_INTERVAL cadence).
        let heartbeat = {
            let hb_airc = airc_arc.clone();
            let hb_persona = persona_id;
            let hb_name = agent_name.clone();
            // NO birth stamp — renewal is earned ONLY by cognition, never by
            // booting. The grace stamp that used to sit here (one lease-length
            // per spawn, meant to cover the post-boot deaf window #412) made
            // convergence structurally impossible across restarts: every core
            // restart re-armed 30 minutes of "earned" renewals, and the renewal
            // loop below resurrected already-lapsed claims faster than the 180s
            // lapsed-claim sweeper could observe them — an entire overnight round
            // (2026-08-16) sat "actively held" with zero turns because of it.
            // Never-stamped ⇒ `idle_ms` is None ⇒ renewal denied ⇒ holds lapse
            // within one TTL of boot unless she actually thinks. A citizen who
            // wakes later can re-claim; a finished artifact gets swept and graded.
            let handle = tokio::spawn(async move {
                let mut ticker = tokio::time::interval(DEFAULT_HEARTBEAT_INTERVAL);
                let mut last: Option<airc_lib::AgentAvailabilityState> = None;
                // CLAIM RENEWAL RUNS ON ITS OWN, SLOWER CADENCE (Joel 2026-08-15:
                // "Heartbeat needs fix. That is no good"). Presence needs the 60s
                // pulse — roster liveness IS a fast question. A 30-minute claim
                // lease does not: renewing it every presence tick emitted ~30× the
                // events one lease needs, and that churn crossed the wire to EVERY
                // subscriber on every node. Renew at TTL/3 — derived from the one
                // lease constant, never a second magic number — which still gives a
                // healthy citizen three renewal opportunities per lease. The stamp
                // is only advanced on a fully-clean pass, so any roster-read or
                // per-card failure falls back to retrying on the NEXT 60s tick
                // (exactly the old cadence) until clean — degraded mode is the old
                // behavior, never a wider gap.
                let renewal_period = std::time::Duration::from_millis(
                    crate::modules::work::DEFAULT_CLAIM_TTL_MS / 3,
                );
                let mut last_clean_renewal: Option<std::time::Instant> = None;
                // Emit-on-transition for the renewal-denied probe: denial is a
                // STANDING condition (an idle citizen stays idle for hours) and
                // this loop ticks every 60s, so an unguarded probe here is the
                // same stream-flooding shape as the per-tick serving.plan probe
                // (#399 — measured 110 identical denial rows in 5 min across
                // the roster). One row when denial BEGINS, one implicit end
                // when renewals resume; the standing state stays queryable via
                // the work board's lease column.
                let mut renewal_denied = false;
                loop {
                    ticker.tick().await;
                    let serving = crate::inference::llama_server::current_serving();
                    let availability = if serving.ready {
                        airc_lib::AgentAvailabilityState::Ready
                    } else {
                        // Lane not up (cold boot, relaunch, squeeze): she can
                        // hear but cannot yet think — warming, not online.
                        airc_lib::AgentAvailabilityState::Away
                    };
                    if last != Some(availability) {
                        crate::probe!(
                            class = "persona.presence.availability",
                            persona_id = %hb_persona,
                            agent_name = %hb_name,
                            state = ?availability,
                            serving_ready = serving.ready,
                            "presence availability transitioned (derived from live serving state)"
                        );
                        last = Some(availability);
                    }
                    let coordination = airc_lib::CoordinationSignal {
                        availability: Some(availability),
                        ..Default::default()
                    };
                    if let Err(error) = hb_airc
                        .emit_agent_heartbeat_with_coordination(
                            airc_lib::HeartbeatKind::Alive,
                            runtime_label.to_string(),
                            None,
                            None,
                            None,
                            coordination,
                        )
                        .await
                    {
                        // WARN-and-continue: a persona that can't heartbeat is
                        // live-but-roster-invisible — degraded, not dead.
                        warn!(
                            persona_id = %hb_persona,
                            agent_name = %hb_name,
                            error = %error,
                            "persona heartbeat emit failed — presence degraded this tick"
                        );
                    }

                    // HER WORK STAYS HERS WHILE SHE BREATHES (2026-08-07).
                    //
                    // Claim leases are 30 min and `work/heartbeat` already existed —
                    // as a VERB THE MODEL HAD TO REMEMBER TO CALL, which no citizen
                    // ever did. Glass-boxed this night from live captures: citizens
                    // claimed cards successfully (`work/claim` → real claim_id), every
                    // lease then lapsed untouched, and their next briefing correctly
                    // read `[board] you hold 0 card(s)` with the SAME card re-offered
                    // under `[available work]`. So they reported "no open tasks" and
                    // passed — accurately describing a board that had quietly taken
                    // their work back. Six citizens, two machines, days of it.
                    //
                    // Presence and claim liveness were two channels answering one
                    // question, and they contradicted each other: this pump was
                    // emitting "I am alive" on the very ticks her holds were dying.
                    // Binding them is the fix — the substrate observes that she is
                    // working instead of asking her to announce it
                    // ([[commands-are-agency]]; Joel: "you've turned convenience into
                    // disability"). The verb stays for deliberate extension.
                    //
                    // Renewal is per-card WARN-and-continue: a failed renewal degrades
                    // to exactly the old lapse, and never takes down presence.
                    let renewal_due =
                        last_clean_renewal.map_or(true, |t| t.elapsed() >= renewal_period);
                    if !renewal_due {
                        continue;
                    }
                    // RENEWAL IS EARNED BY COGNITION, NOT BY BREATHING
                    // (2026-08-16). The presence-bound renewal above this
                    // comment's ancestor fixed #331 by overcorrecting: a
                    // citizen whose cognition had been silent for HOURS still
                    // renewed every minute, so a stalled round read as
                    // "actively held" forever and the lapsed-claim sweeper
                    // could never recover her finished artifact. The gate:
                    // no turn within one lease-length → skip renewal → the
                    // hold lapses naturally → the card becomes re-claimable
                    // and any written artifact gets graded. A turn that
                    // DEFERS on serving pressure still stamps the pulse —
                    // trying to think counts; only true silence lapses.
                    {
                        let now_ms = std::time::SystemTime::now()
                            .duration_since(std::time::UNIX_EPOCH)
                            .map(|d| d.as_millis() as u64)
                            .unwrap_or_default();
                        let idle = crate::persona::cognition_pulse::idle_ms(hb_persona, now_ms);
                        if !crate::persona::cognition_pulse::renewal_earned(
                            idle,
                            crate::modules::work::DEFAULT_CLAIM_TTL_MS,
                        ) {
                            if !renewal_denied {
                                renewal_denied = true;
                                // `idle` is None when she has NEVER thought this
                                // process — that is a state, not a duration, and
                                // stamping it u64::MAX printed a 584-million-year
                                // idle into the ledger (seen live 2026-08-21).
                                // [[unknown-is-not-a-quantity]]: the unknown gets a
                                // word, never a sentinel number.
                                crate::probe!(
                                    class = "persona.claim.renewal_skipped_idle",
                                    persona_id = %hb_persona,
                                    agent_name = %hb_name,
                                    idle = %idle
                                        .map(|ms| ms.to_string())
                                        .unwrap_or_else(|| "never-thought".to_string()),
                                    ttl_ms = crate::modules::work::DEFAULT_CLAIM_TTL_MS,
                                    "no cognition within one lease-length — renewals \
                                     DENIED from here until she thinks again; holds \
                                     lapse naturally so the work can be recovered"
                                );
                            }
                            continue;
                        }
                        if renewal_denied {
                            renewal_denied = false;
                            crate::probe!(
                                class = "persona.claim.renewal_resumed",
                                persona_id = %hb_persona,
                                agent_name = %hb_name,
                                "cognition resumed — claim renewals earned again"
                            );
                        }
                    }
                    match hb_airc
                        .work_roster_status(airc_lib::WorkRosterQuery::default())
                        .await
                    {
                        Ok(status) => {
                            let me = hb_airc.peer_id();
                            let mine = status
                                .rows
                                .into_iter()
                                .find(|r| r.peer == me)
                                .map(|r| r.active_claims)
                                .unwrap_or_default();
                            let mut renewed = 0usize;
                            let mut failed = 0usize;
                            for card in &mine {
                                let Some(claim_id) = card.claim_id else {
                                    continue;
                                };
                                if let Err(error) = hb_airc
                                    .heartbeat_work_claim(airc_lib::HeartbeatWorkClaim {
                                        card_id: card.card_id,
                                        claim_id,
                                        ttl_ms: crate::modules::work::DEFAULT_CLAIM_TTL_MS,
                                    })
                                    .await
                                {
                                    failed += 1;
                                    warn!(
                                        persona_id = %hb_persona,
                                        agent_name = %hb_name,
                                        card_id = %card.card_id.as_uuid(),
                                        error = %error,
                                        "claim renewal failed — this card can lapse out from \
                                         under her while she is still working it"
                                    );
                                } else {
                                    renewed += 1;
                                }
                            }
                            if renewed > 0 {
                                crate::probe!(
                                    class = "persona.claim.renewed",
                                    persona_id = %hb_persona,
                                    agent_name = %hb_name,
                                    renewed = renewed,
                                    held = mine.len(),
                                    ttl_ms = crate::modules::work::DEFAULT_CLAIM_TTL_MS,
                                    "held work-card claims renewed on the claim cadence (TTL/3)"
                                );
                            }
                            // Only a fully-clean pass earns the slow cadence; any
                            // failure retries on the next 60s presence tick.
                            if failed == 0 {
                                last_clean_renewal = Some(std::time::Instant::now());
                            }
                        }
                        Err(error) => {
                            warn!(
                                persona_id = %hb_persona,
                                agent_name = %hb_name,
                                error = %error,
                                "claim-renewal roster read failed — holds may lapse; retrying \
                                 on the next presence tick"
                            );
                        }
                    }
                }
            });
            info!(
                persona_id = %persona_id,
                agent_name = %agent_name,
                interval_s = DEFAULT_HEARTBEAT_INTERVAL.as_secs(),
                "PersonaAircRuntime bootstrap: dynamic-availability heartbeat pump started — \
                 presence tracks live serving state (away=warming, ready=able to respond)"
            );
            Some(AbortOnDrop(handle))
        };

        // Re-publish the identity card on the heartbeat cadence so it SURVIVES. The
        // card emit at attach is one-shot: a peer that joins the room AFTER this
        // persona attached (M5's desktop reconnecting, a fresh grid peer) missed it
        // and would render her by peer-id forever. `publish_identity()` re-emits the
        // already-set full card to every subscribed room; on the 60s cadence, any
        // late arrival is grounded within a heartbeat window. Handle held for the
        // persona's lifetime; dropped on teardown (mirrors the heartbeat pump).
        let identity_republish = {
            let airc = airc_arc.clone();
            let persona_id = persona_id;
            let agent_name = agent_name.clone();
            Some(tokio::spawn(async move {
                let mut ticker = tokio::time::interval(DEFAULT_HEARTBEAT_INTERVAL);
                // Skip the immediate tick — bootstrap already emitted the card.
                ticker.tick().await;
                loop {
                    ticker.tick().await;
                    if let Err(source) = airc.publish_identity().await {
                        warn!(
                            persona_id = %persona_id,
                            agent_name = %agent_name,
                            error = %source,
                            "PersonaAircRuntime: periodic identity re-publish failed \
                             (transient) — will retry next cadence"
                        );
                    }
                }
            }))
        };

        // Resume-visibility contract (Joel 2026-07-13: post-reboot the team
        // resumed correctly — woke, restored, yielded per cadence — but from
        // the outside that was indistinguishable from a stall, because a
        // persona's state has no surface other than speech). Status is a
        // PROJECTION, not a message: if this peer still holds work-card
        // claims, publish typed Busy availability naming them — the board /
        // HUD / work_queue_status then show "back and still on card X"
        // without a single chat line. WARN-and-continue like the identity
        // card: a persona whose availability didn't publish is degraded-
        // visible, not broken. No claims → nothing to announce (the quiet
        // Ready story needs per-room repo resolution — a later slice).
        match airc_arc
            .work_roster_status(airc_lib::WorkRosterQuery::default())
            .await
        {
            Ok(status) => {
                let me = airc_arc.peer_id();
                let claims: Vec<airc_lib::WorkCard> = status
                    .rows
                    .into_iter()
                    .find(|r| r.peer == me)
                    .map(|r| r.active_claims)
                    .unwrap_or_default();
                let mut repos: Vec<airc_lib::RepoId> =
                    claims.iter().map(|c| c.repo.clone()).collect();
                repos.sort();
                repos.dedup();
                for repo in repos {
                    let held: Vec<String> = claims
                        .iter()
                        .filter(|c| c.repo == repo)
                        .map(|c| format!("{} ({})", c.title, c.card_id))
                        .collect();
                    let report = airc_lib::ReportAgentAvailability {
                        repo: repo.clone(),
                        state: airc_lib::AgentAvailabilityState::Busy,
                        note: Some(format!("resumed — holding: {}", held.join("; "))),
                        ttl_ms: RESUME_AVAILABILITY_TTL_MS,
                    };
                    match airc_arc.report_agent_availability(report).await {
                        Ok(()) => info!(
                            persona_id = %persona_id,
                            agent_name = %agent_name,
                            repo = %repo,
                            cards = held.len(),
                            "PersonaAircRuntime bootstrap: resume availability published — \
                             board shows this persona back on its claimed work"
                        ),
                        Err(source) => warn!(
                            persona_id = %persona_id,
                            agent_name = %agent_name,
                            repo = %repo,
                            error = %source,
                            "PersonaAircRuntime bootstrap: resume availability publish failed — \
                             persona is live but the board cannot show it resumed its claims"
                        ),
                    }
                }
            }
            Err(source) => warn!(
                persona_id = %persona_id,
                agent_name = %agent_name,
                error = %source,
                "PersonaAircRuntime bootstrap: work roster read failed — cannot publish \
                 resume availability for held claims"
            ),
        }

        Ok(Self {
            persona_id,
            agent_name,
            home,
            airc: airc_arc,
            // The ACTUALLY-joined home room (from her durable subscription
            // state above) — before #298 this stored the passed-in operator
            // room, which could even diverge from the joined channel.
            default_room: RoomId::from_uuid(room.channel.as_uuid()),
            membership_epoch: tokio::sync::watch::channel(0u64).0,
            inbound_handle: None,
            command_pump: Some(command_pump),
            heartbeat,
            identity_republish,
            source,
        })
    }

    /// Join a room UNDER THIS CITIZEN'S IDENTITY at runtime and bump the
    /// membership epoch so her live perception stream re-opens with the
    /// enlarged channel snapshot (P0 20b44763). This — not `airc().join`
    /// directly — is the ONE runtime-join path for a living persona:
    /// airc-lib's `subscribe_subscribed_filtered` collects the channel list
    /// once at subscribe time, so a bare join grants durable membership to a
    /// room whose events her existing stream will never carry (measured
    /// 2026-08-15: three benchmark rounds, 12 addressed kickoffs each, zero
    /// turns — every per-run room was born deaf).
    pub async fn join_room(&self, name: &str) -> Result<(), AircError> {
        self.airc.join(name).await?;
        self.membership_epoch.send_modify(|e| *e += 1);
        Ok(())
    }

    /// Wrap an already-attached + already-joined `Arc<Airc>` into a
    /// `PersonaAircRuntime`. Skips the `bootstrap` join step —
    /// useful for the demo binary that joins by NAME (the canonical
    /// path) instead of by uuid-as-string (the bootstrap path's
    /// current shape — see #133-followup note on `bootstrap`).
    ///
    /// The caller is responsible for: (1) calling `attach_as` /
    /// `join` BEFORE handing the Arc in, (2) supplying the
    /// `RoomId` matching the room they joined.
    pub fn from_attached(
        persona_id: Uuid,
        agent_name: impl Into<String>,
        home: PathBuf,
        airc: Arc<Airc>,
        default_room: RoomId,
        source: crate::persona::identity_provider::PersonaIdentitySource,
    ) -> Self {
        // Slice 1B of #142: collapse persona_id := peer_id. Same
        // rationale as in `bootstrap` above. The input parameter is
        // retained for API continuity but its value is reseated to
        // the airc-lib peer_id (cryptographic ground truth).
        let peer_id_uuid = airc.peer_id().as_uuid();
        let agent_name = agent_name.into();
        if persona_id != peer_id_uuid {
            // Expected for fresh mints — see equivalent doc in
            // `bootstrap` above. `debug!` not `warn!` to avoid log
            // spam at every boot.
            tracing::debug!(
                input_persona_id = %persona_id,
                peer_id = %peer_id_uuid,
                agent_name = %agent_name,
                "PersonaAircRuntime::from_attached: persona_id parameter \
                 ignored — runtime collapses persona_id := peer_id per Slice \
                 1B of #142."
            );
        }
        Self {
            persona_id: peer_id_uuid,
            agent_name,
            home,
            airc,
            default_room,
            membership_epoch: tokio::sync::watch::channel(0u64).0,
            inbound_handle: None,
            // from_attached is sync + the pump install is async, so
            // we don't install at construction. Callers that want the
            // persona addressable for cross-grid commands invoke
            // `install_command_pump` separately. Bootstrap installs
            // automatically; this seam is for tests + demo binaries
            // that want fine-grained control.
            command_pump: None,
            // Presence is opt-out here for the same reason as the command pump:
            // `from_attached` is sync and `start_agent_heartbeat` is async. The
            // live `bootstrap` path always starts the pump; test/demo callers
            // that want roster presence start it themselves after construction.
            heartbeat: None,
            // from_attached is sync; the periodic card re-publisher (async spawn)
            // is a bootstrap-path concern. Test/demo callers don't need it.
            identity_republish: None,
            source,
        }
    }

    /// Install the command inbound pump on this runtime (task #222).
    /// `bootstrap` calls this automatically; `from_attached` callers
    /// invoke it explicitly when they want the persona to become
    /// addressable for cross-grid commands.
    ///
    /// Idempotency: if a pump is already installed, this aborts the
    /// existing one before installing the new — per
    /// `[[no-fallbacks-ever]]` the alternative (silently keep two
    /// pumps fighting over the broadcast receiver) is the wrong
    /// shape.
    pub async fn install_command_pump(
        &mut self,
        executor: Arc<crate::runtime::command_executor::CommandExecutor>,
    ) -> Result<(), PersonaAircRuntimeError> {
        if let Some(existing) = self.command_pump.take() {
            existing.abort();
        }
        let grant_authorizer =
            crate::persona::command_inbound_pump::build_grant_authorizer(&self.airc, &self.home)
                .await
                .map_err(|source| PersonaAircRuntimeError::GrantAuthorizerBuild {
                    agent_name: self.agent_name.clone(),
                    source,
                })?;
        let pump = crate::persona::command_inbound_pump::PersonaCommandInboundPump::spawn(
            self.persona_id,
            Arc::clone(&self.airc),
            executor,
            grant_authorizer,
        )
        .await
        .map_err(|source| PersonaAircRuntimeError::CommandPumpInstall {
            agent_name: self.agent_name.clone(),
            source,
        })?;
        self.command_pump = Some(pump);
        Ok(())
    }

    /// Whether this runtime currently has the command inbound pump
    /// installed. `true` after `bootstrap` (always) or after a
    /// successful `install_command_pump` call. Useful for tests +
    /// telemetry to confirm the persona is addressable.
    pub fn has_command_pump(&self) -> bool {
        self.command_pump.is_some()
    }

    /// The persona's stable continuum identifier.
    pub fn persona_id(&self) -> Uuid {
        self.persona_id
    }

    /// Where this citizen's identity came from — resumed vs minted.
    pub fn source(&self) -> crate::persona::identity_provider::PersonaIdentitySource {
        self.source
    }

    /// The persona's airc agent_name (matches what shows up in
    /// `airc peers` / `airc whois`).
    pub fn agent_name(&self) -> &str {
        &self.agent_name
    }

    /// The persona's airc home directory.
    pub fn home(&self) -> &Path {
        &self.home
    }

    /// The persona's `Arc<Airc>` handle. Cognition + outbound paths
    /// hold this Arc to reach the persona's grid presence — for
    /// `say`, `publish`, `subscribe`, `peer_id`, etc. Direct access
    /// is intentional: there's no continuum-side wrapper between a
    /// persona and its own airc handle.
    pub fn airc(&self) -> &Arc<Airc> {
        &self.airc
    }

    /// Convenience: publish a plain text message in the persona's
    /// default room, signed under the persona's identity. Equivalent
    /// to `self.airc().say(text)`. Exists so the common case reads
    /// cleanly at the call site.
    pub async fn say(&self, text: &str) -> Result<EventId, AircError> {
        self.airc.say(text).await
    }

    /// The default room the persona joined at bootstrap.
    pub fn default_room(&self) -> RoomId {
        self.default_room
    }
}

// AircCitizen + AircTranscriptReader impls — substrate's universal
// airc-handle interface, satisfied by the production runtime. Per
// [[personas-are-citizens-airc-is-identity-provider]] the trait IS the
// citizen surface; the concrete runtime is one impl among future
// peers (human, web, browser). See `persona::airc_citizen` for the
// trait definition + rationale.
#[async_trait::async_trait]
impl crate::persona::airc_source::AircTranscriptReader for PersonaAircRuntime {
    async fn page_recent(&self, limit: usize) -> Result<Vec<airc_lib::TranscriptEvent>, AircError> {
        // Route through the ONE kinds-filtered impl on `airc_lib::Airc`
        // (persona/airc_source.rs, #297) — never the raw inherent page.
        crate::persona::airc_source::AircTranscriptReader::page_recent(&*self.airc, limit).await
    }

    async fn page_recent_in(
        &self,
        room: Option<airc_core::RoomId>,
        limit: usize,
    ) -> Result<Vec<airc_lib::TranscriptEvent>, AircError> {
        // Explicit forward (#367) — inheriting the trait default here would
        // silently drop the turn-room scope (#262-class regression).
        crate::persona::airc_source::AircTranscriptReader::page_recent_in(&*self.airc, room, limit)
            .await
    }
}

#[async_trait::async_trait]
impl crate::persona::room_roster_source::AircRosterReader for PersonaAircRuntime {
    fn self_peer_id(&self) -> airc_core::PeerId {
        self.airc.peer_id()
    }

    async fn room_roster(
        &self,
        within: std::time::Duration,
        window: usize,
        room: Option<uuid::Uuid>,
    ) -> Result<Vec<airc_lib::RoomMember>, AircError> {
        crate::persona::room_roster_source::AircRosterReader::room_roster(
            self.airc.as_ref(),
            within,
            window,
            room,
        )
        .await
    }
}

#[async_trait::async_trait]
impl crate::persona::room_doctrine_source::AircDoctrineReader for PersonaAircRuntime {
    async fn room_doctrine(
        &self,
        room: Option<uuid::Uuid>,
    ) -> Result<Option<airc_core::doctrine::RoomDoctrinePublished>, AircError> {
        crate::persona::room_doctrine_source::AircDoctrineReader::room_doctrine(
            self.airc.as_ref(),
            room,
        )
        .await
    }
}

#[async_trait::async_trait]
impl crate::persona::wall_source::WallReader for PersonaAircRuntime {
    async fn wall_posts(&self) -> Result<Vec<airc_core::doctrine::WallPostPublished>, AircError> {
        // Whole board (all categories); the source filters/labels per post.
        self.airc.wall_posts(None).await
    }
}

#[async_trait::async_trait]
impl crate::persona::active_work_source::AircWorkReader for PersonaAircRuntime {
    /// This persona's claimed cards, read from airc's work roster and filtered to
    /// its own peer — grounding reflects what IT owns, board-wide (all rooms).
    async fn active_claims(&self) -> Result<Vec<airc_lib::WorkCard>, AircError> {
        let status = self
            .airc
            .work_roster_status(airc_lib::WorkRosterQuery::default())
            .await?;
        let me = self.airc.peer_id();
        Ok(status
            .rows
            .into_iter()
            .find(|r| r.peer == me)
            .map(|r| r.active_claims)
            .unwrap_or_default())
    }
}

#[async_trait::async_trait]
impl crate::persona::room_board_source::RoomBoardReader for PersonaAircRuntime {
    /// The current room's WHOLE work board — every card/column/owner. Delegates
    /// to the inner airc handle's single board fold (`work_board_complete` →
    /// snapshot), the same read the desktop-app kanban projector makes.
    async fn work_board(
        &self,
        room: Option<uuid::Uuid>,
    ) -> Result<airc_work::BoardSnapshot, AircError> {
        crate::persona::room_board_source::RoomBoardReader::work_board(self.airc.as_ref(), room)
            .await
    }

    /// Published display names for card owners — delegates to the inner airc
    /// handle's alias store. This is the LIVE persona path: without it, every
    /// teammate's card renders as an 8-hex prefix she cannot recognize or
    /// reach out to.
    async fn peer_names(
        &self,
        peers: &[airc_core::PeerId],
    ) -> std::collections::HashMap<airc_core::PeerId, String> {
        crate::persona::room_board_source::RoomBoardReader::peer_names(self.airc.as_ref(), peers)
            .await
    }
}

#[async_trait::async_trait]
impl crate::persona::airc_citizen::AircCitizen for PersonaAircRuntime {
    fn peer_id(&self) -> Uuid {
        self.airc.peer_id().as_uuid()
    }

    async fn subscribe_all_rooms(&self) -> Result<airc_lib::FilteredEventStream, AircError> {
        crate::persona::airc_citizen::subscribe_every_room(&self.airc).await
    }

    fn membership_epoch(&self) -> tokio::sync::watch::Receiver<u64> {
        self.membership_epoch.subscribe()
    }

    async fn say_in(&self, room_id: Uuid, text: &str) -> Result<EventId, AircError> {
        crate::persona::airc_citizen::publish_text_in_room(&self.airc, room_id, text).await
    }

    /// #170: delegate to airc-lib's ephemeral stream-chunk publish.
    async fn publish_stream_chunk(&self, chunk: &airc_lib::StreamChunk) -> Result<(), AircError> {
        self.airc.publish_stream_chunk(chunk).await.map(|_| ())
    }
}

impl Drop for PersonaAircRuntime {
    fn drop(&mut self) {
        if let Some(handle) = self.inbound_handle.take() {
            handle.abort();
        }
        if let Some(pump) = self.command_pump.take() {
            // Fire-and-forget abort. Drop is sync; the pump's async
            // `shutdown` (which awaits the JoinHandle) is what
            // explicit-shutdown callers use. Tokio reaps the
            // aborted task.
            pump.abort();
        }
        if let Some(handle) = self.identity_republish.take() {
            // Stop re-emitting the identity card once the persona leaves the grid.
            handle.abort();
        }
        // Arc<Airc> drops alongside the runtime; airc-lib handles
        // its own cleanup (daemon connection close, identity state
        // flush).
        warn!(
            persona_id = %self.persona_id,
            agent_name = %self.agent_name,
            "PersonaAircRuntime dropped — persona left the grid"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[tokio::test]
    async fn bootstrap_resolves_home_under_personas_directory() {
        // This unit test verifies path layout only — actual daemon
        // attach lives in an integration test that needs a running
        // airc daemon. The layout assertion catches the
        // [[personas-are-citizens-airc-is-identity-provider]] memory's
        // "do NOT nest persona homes inside another scope's airc home"
        // rule at compile-ish time.
        let temp = TempDir::new().expect("tempdir");
        let expected_home = crate::context::citizen_home_path(
            temp.path(),
            crate::identity::IdentityKind::Persona,
            None,
            "helper-ai-test",
        );
        // Slice 4 of #142: symmetric layout under
        // citizens/personas/<name>/airc/.
        assert_eq!(
            expected_home,
            temp.path()
                .join("citizens")
                .join("personas")
                .join("helper-ai-test")
                .join("airc")
        );
        assert!(!expected_home.exists());
    }

    /// Slice 4 of #142 migration safety claim: when bootstrap is
    /// called for a persona whose pre-Slice-4 home
    /// (`<root>/personas/<name>/airc/`) exists on disk, the
    /// substrate REFUSES to silently use it and returns
    /// `LegacyLayoutDetected` with the exact `mv` paths. This test
    /// fires the detection branch via a TempDir-seeded legacy path.
    ///
    /// Per [[no-fallbacks-ever]] + [[every-error-is-an-opportunity-
    /// to-battle-harden]]: the message is load-bearing safety; this
    /// is the rigging that catches a regression flipping the path
    /// components.
    #[tokio::test]
    async fn legacy_persona_layout_hard_errors_with_mv_command() {
        let tmp = TempDir::new().expect("tempdir");
        let root = tmp.path();

        // Seed the pre-Slice-4 legacy path for a persona named "maya".
        let legacy = root.join("personas").join("maya").join("airc");
        tokio::fs::create_dir_all(&legacy)
            .await
            .expect("seed legacy persona path");

        // Bootstrap a persona named "maya". The legacy detection
        // fires BEFORE airc-lib attach, so the test doesn't need a
        // running daemon.
        // Dummy executor — bootstrap fires the legacy-path detection
        // BEFORE pump install, so the executor is never touched.
        let dummy_registry = std::sync::Arc::new(crate::runtime::ModuleRegistry::new());
        let dummy_executor = std::sync::Arc::new(
            crate::runtime::command_executor::CommandExecutor::new(dummy_registry),
        );

        let result = PersonaAircRuntime::bootstrap(
            Uuid::new_v4(),
            "maya",
            root,
            PathBuf::from("/nonexistent/daemon.sock"),
            crate::persona::identity_provider::PersonaIdentitySource::FreshlyMinted,
            dummy_executor,
        )
        .await;

        // `PersonaAircRuntime` doesn't impl Debug (Arc<dyn ...>
        // fields), so we destructure without {:?} on the Ok variant.
        match result {
            Err(PersonaAircRuntimeError::LegacyLayoutDetected {
                legacy: l,
                new,
                new_parent,
            }) => {
                assert_eq!(l, legacy);
                assert_eq!(
                    new,
                    root.join("citizens")
                        .join("personas")
                        .join("maya")
                        .join("airc")
                );
                assert_eq!(
                    new_parent,
                    root.join("citizens").join("personas").join("maya")
                );
            }
            Err(other) => panic!(
                "expected LegacyLayoutDetected, got different error: {other} \
                 — legacy detection is broken"
            ),
            Ok(_) => panic!(
                "expected LegacyLayoutDetected, bootstrap succeeded — \
                 legacy detection is broken"
            ),
        }
    }
}
