//! WorkspaceMapSource — grounds a persona in the SHAPE of its workspace: the
//! root it acts in plus the real top-level directory layout, packaged as a
//! `[workspace-map]` standing-framing block.
//!
//! ### Why this source exists (the glass-box finding)
//!
//! Asha's biggest cluster of coder-eval failures was searching
//! `file_glob: "src/**/*.rs"` — which matches ZERO files here, because this
//! repo's Rust lives under `core/continuum-core/src/` and root `src/` is the
//! legacy TS tree. The decisive question (Joel): *given her exact prompt, with
//! no a-priori knowledge of the layout, could you or I have done better?* No —
//! her standing prompt carried identity + grid context + the room roster, but
//! **no map of where code lives**. The layout only ever appeared reactively, as
//! an echoed error in recall after a failed glob. A capable reasoner makes the
//! same `src/**/*.rs` guess from that prompt. That is a GROUNDING hole, not
//! stupidity — the same class as not knowing who else is in the room.
//!
//! This source closes it: the workspace layout is true world-state the persona
//! reasons over, exactly like the roster (WHO is present) and the doctrine (WHAT
//! the room is for). This adds WHERE things live. It is grounding, never
//! steering: we surface the real top-level directories and the path semantics of
//! the tools; we do NOT script steps or name which directory holds the answer.
//!
//! ### Ground truth, no drift
//!
//! The map is generated by the SAME machinery the code tools resolve against —
//! a [`FileEngine`] rooted at the process cwd, exactly as
//! [`ensure_engine`](crate::modules::code_commands::ensure_engine) builds the
//! persona's hands. So the directories named here are precisely the ones
//! `code/glob` / `code/list` will see; the map cannot describe a layout the tools
//! don't share. When airc-owned per-persona workspace isolation lands (#49), the
//! reader swaps to the leased root and every persona — including remote grid
//! peers with no local filesystem intuition — shares ONE consistent view.
//!
//! ### Doctrine alignment
//!
//! - [[substrate-is-a-good-citizen-on-the-host]]: a failed layout read returns
//!   an empty delivery — cognition stays up; no block rather than a panic.
//! - Persona-scoped at construction (defense in depth, same as roster/doctrine).
//! - [[solve-for-public-users]]: the map is the ACTUAL layout of whatever repo
//!   the core runs in — zero repo-specific prose, true for any checkout.
//! - [[no-hardcoded-heuristics-to-steer-cognition]]: we ground her in facts, we
//!   never tell her which directory to look in or what step to take next.

use std::path::PathBuf;
use std::sync::Arc;

use async_trait::async_trait;

use crate::code::types::FsEntryKind;
use crate::code::{FileEngine, PathSecurity};
use crate::persona::rag_budget::{
    ContinuationCursor, RagContext, RagDelivery, RagItem, RagSource, ResolutionPreference,
};

/// Source identifier — the deliberation faculty renders this delivery under a
/// `[workspace-map]` grounding block (header is the source id verbatim, same as
/// `room-roster` / `room-doctrine` in the brain path).
const SOURCE_ID: &str = "workspace-map";

/// Token estimate — the ONE canonical chars/4 estimator (`cognition::token_budget`),
/// shared by every RAG source so the replay ledger's numbers match. (Was a private
/// copy — converged.)
use crate::cognition::token_budget::estimate_prompt_tokens as estimate_tokens;

/// The real shape of the workspace: the root the tools act in, plus its
/// top-level directory names (the navigation structure a persona globs against).
#[derive(Debug, Clone, PartialEq)]
pub struct WorkspaceLayout {
    pub root: PathBuf,
    /// Non-hidden top-level directory names, sorted.
    pub top_level_dirs: Vec<String>,
}

/// Abstract reader over the workspace layout. Production rides on the same
/// [`FileEngine`] the code tools use ([`CwdWorkspaceLayoutReader`]); tests stub
/// it without touching the filesystem. Mirrors the `AircDoctrineReader` rail.
pub trait WorkspaceLayoutReader: Send + Sync {
    /// The current workspace root and its top-level directories, or an error
    /// string if the layout cannot be read (degrades to no block, never panics).
    fn layout(&self) -> Result<WorkspaceLayout, String>;
}

/// Reads the layout from the SAME machinery the persona's hands resolve against:
/// a [`FileEngine`] rooted at the process cwd (exactly what `ensure_engine`
/// roots at), top-level entries via `list_dir`. This is what guarantees the map
/// can never drift from what `code/glob` / `code/list` actually see.
pub struct CwdWorkspaceLayoutReader;

impl WorkspaceLayoutReader for CwdWorkspaceLayoutReader {
    fn layout(&self) -> Result<WorkspaceLayout, String> {
        let root = std::env::current_dir().map_err(|e| format!("workspace root unavailable: {e}"))?;
        let security =
            PathSecurity::new(&root).map_err(|e| format!("workspace security init failed: {e}"))?;
        // Identity here is the reader, not a persona — this engine only LISTS the
        // root; the persona's own per-caller engine handles reads/edits.
        let engine = FileEngine::new(SOURCE_ID, security);
        let listing = engine
            .list_dir(".", false)
            .map_err(|e| format!("workspace list failed: {e}"))?;
        let mut top_level_dirs: Vec<String> = listing
            .entries
            .into_iter()
            .filter(|e| e.kind == FsEntryKind::Directory)
            .map(|e| e.name)
            .collect();
        top_level_dirs.sort();
        Ok(WorkspaceLayout {
            root,
            top_level_dirs,
        })
    }
}

/// Render a [`WorkspaceLayout`] into the grounding block body. Pure (no I/O) so
/// the wording is unit-testable independent of the filesystem. Generic and
/// truthful: it states the real root, the real directories, and the path
/// semantics of the tools — it never names which directory holds the answer.
fn render_layout(layout: &WorkspaceLayout) -> String {
    let count = layout.top_level_dirs.len();
    let dirs = if layout.top_level_dirs.is_empty() {
        "(none)".to_string()
    } else {
        layout.top_level_dirs.join(", ")
    };
    // When the workspace HAS directories, explicitly refute the stale "workspace is
    // empty" confabulation (glass-boxed 2026-07-14: a persona kept RECALLING a past
    // "the workspace is empty" note and acting on it over this live ground truth,
    // never re-checking). The map is the authority on workspace state; a memory that
    // contradicts it is stale by definition. Silent when genuinely empty (never claim
    // non-empty falsely). [[empty-workspace-is-a-confabulation-not-infra]]
    let not_empty = if count > 0 {
        format!(
            "\nThis workspace is NOT empty: it has {count} top-level directories (above) \
             and many files. If a memory or earlier note says the workspace is empty, that \
             note is STALE — trust THIS live layout, and re-run code/list before concluding \
             anything is missing."
        )
    } else {
        String::new()
    };
    format!(
        "This workspace is a real checkout rooted at: {root}\n\
         Top-level directories (the actual layout — ground truth): {dirs}\n\
         Tool paths and globs are relative to this root. `**/` matches at ANY \
         depth — e.g. `**/*.rs` finds files anywhere, regardless of which \
         directory holds them. Do NOT assume source lives under one particular \
         top-level directory (such as `src/`); check this layout, or drill in \
         with code/list and code/tree.{not_empty}",
        root = layout.root.display(),
        dirs = dirs,
    )
}

/// Reads the layout from the persona's OWN citizen layer — the copy-on-write
/// workspace their hands actually act in (`<home>/citizens/peers/<peer>/
/// workspace`), the same root [`ensure_engine`](crate::modules::code_commands::ensure_engine)
/// gives an identified peer. This is the #49 swap the module header anticipated:
/// before it, the map named the core's cwd while the tools rooted at the citizen
/// layer — a root the persona could never `cd` to, and one that never reflected
/// files the persona itself created. Now the map's root == the tools' root, and
/// it updates as the persona shapes its own workspace.
///
/// Read-only: resolves the layer PATH (no CoW provisioning — that's the hands'
/// job on first write). If the layer isn't provisioned yet, it falls back to the
/// shared base (the core cwd the layer will clone), whose top-level layout is
/// identical — so the map is truthful either way, never empty, never a panic.
pub struct CitizenLayerWorkspaceLayoutReader {
    peer: String,
}

impl WorkspaceLayoutReader for CitizenLayerWorkspaceLayoutReader {
    fn layout(&self) -> Result<WorkspaceLayout, String> {
        let layer = crate::modules::code_commands::citizen_layer_path(&self.peer)
            .map_err(|e| format!("citizen layer path unavailable: {e}"))?;
        // Not yet provisioned → the shared base (cwd) has the same top-level
        // layout the layer will clone; grounding stays truthful, never empty.
        let root = if layer.is_dir() {
            layer
        } else {
            std::env::current_dir().map_err(|e| format!("workspace root unavailable: {e}"))?
        };
        let security =
            PathSecurity::new(&root).map_err(|e| format!("workspace security init failed: {e}"))?;
        let engine = FileEngine::new(SOURCE_ID, security);
        let listing = engine
            .list_dir(".", false)
            .map_err(|e| format!("workspace list failed: {e}"))?;
        let mut top_level_dirs: Vec<String> = listing
            .entries
            .into_iter()
            .filter(|e| e.kind == FsEntryKind::Directory)
            .map(|e| e.name)
            .collect();
        top_level_dirs.sort();
        Ok(WorkspaceLayout {
            root,
            top_level_dirs,
        })
    }
}

/// WorkspaceMapSource — persona-bound, reads the layout from any
/// [`WorkspaceLayoutReader`].
pub struct WorkspaceMapSource {
    persona_id: uuid::Uuid,
    reader: Arc<dyn WorkspaceLayoutReader>,
}

impl WorkspaceMapSource {
    pub fn new(persona_id: uuid::Uuid, reader: Arc<dyn WorkspaceLayoutReader>) -> Self {
        Self { persona_id, reader }
    }

    /// Construct with the production cwd-rooted reader (operator scope / tests).
    pub fn from_cwd(persona_id: uuid::Uuid) -> Self {
        Self::new(persona_id, Arc::new(CwdWorkspaceLayoutReader))
    }

    /// Construct rooted at the persona's own citizen layer — the live persona
    /// wiring, so the map matches the root the persona's hands act in (#49 swap).
    pub fn for_peer_layer(persona_id: uuid::Uuid) -> Self {
        Self::new(
            persona_id,
            Arc::new(CitizenLayerWorkspaceLayoutReader {
                peer: persona_id.to_string(),
            }),
        )
    }

    /// Fit the rendered map to `budget` tokens. The map is small (a root path +
    /// a directory list) and never approaches the standing-framing budget in
    /// practice; truncation exists only to honor the budget contract. Same shape
    /// as the doctrine source: truncate with a marker, or emit no block when the
    /// budget can't carry the marker plus real content.
    fn fit_body(body: &str, budget: u32) -> Option<String> {
        if budget == 0 {
            return None;
        }
        if estimate_tokens(body) <= budget {
            return Some(body.to_string());
        }
        const MARKER: &str = "\n…[workspace map truncated]";
        let marker_chars = MARKER.chars().count();
        let max_chars = (budget as usize).saturating_mul(4).saturating_sub(4);
        if max_chars <= marker_chars {
            return None;
        }
        let char_budget = max_chars - marker_chars;
        let mut out: String = body.chars().take(char_budget).collect();
        out.push_str(MARKER);
        Some(out)
    }
}

#[async_trait]
impl RagSource for WorkspaceMapSource {
    fn source_id(&self) -> &'static str {
        SOURCE_ID
    }

    async fn deliver(
        &self,
        ctx: &RagContext,
        budget: u32,
        resolution: ResolutionPreference,
    ) -> RagDelivery {
        let empty = |res| RagDelivery {
            source_id: SOURCE_ID.to_string(),
            items: Vec::new(),
            tokens_used: 0,
            continuation: None,
            resolution_used: res,
        };

        // Persona-scoped (defense in depth, same shape as the roster/doctrine).
        if ctx.persona_id != self.persona_id {
            return empty(ResolutionPreference::Placeholder);
        }

        let layout = match self.reader.layout() {
            Ok(layout) => layout,
            Err(err) => {
                tracing::warn!(
                    error = %err,
                    persona_id = %self.persona_id,
                    "workspace_map: layout read failed — empty delivery, cognition stays up"
                );
                return empty(ResolutionPreference::Placeholder);
            }
        };

        let body = render_layout(&layout);
        let Some(content) = Self::fit_body(&body, budget) else {
            return empty(resolution);
        };
        let tokens = estimate_tokens(&content);

        tracing::debug!(
            persona_id = %self.persona_id,
            budget,
            dirs = layout.top_level_dirs.len(),
            tokens,
            "workspace_map: deliver"
        );

        RagDelivery {
            source_id: SOURCE_ID.to_string(),
            items: vec![RagItem {
                content,
                tokens,
                metadata: serde_json::json!({
                    "root": layout.root.display().to_string(),
                    "top_level_dirs": layout.top_level_dirs,
                }),
            }],
            tokens_used: tokens,
            // One current layout snapshot per turn; no pagination.
            continuation: None,
            resolution_used: resolution,
        }
    }

    async fn deliver_continuation(
        &self,
        _ctx: &RagContext,
        _cursor: ContinuationCursor,
        _budget: u32,
    ) -> Option<RagDelivery> {
        // The layout is a single current snapshot; any cursor is stale.
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use uuid::Uuid;

    fn persona() -> Uuid {
        Uuid::parse_str("00000000-0000-0000-0000-000000000aaa").unwrap()
    }

    fn ctx() -> RagContext {
        RagContext::for_persona(persona(), 1_000_000)
    }

    fn layout(dirs: &[&str]) -> WorkspaceLayout {
        WorkspaceLayout {
            root: PathBuf::from("/repo"),
            top_level_dirs: dirs.iter().map(|s| s.to_string()).collect(),
        }
    }

    struct StubReader {
        layout: Result<WorkspaceLayout, String>,
    }

    impl StubReader {
        fn ok(dirs: &[&str]) -> Self {
            Self {
                layout: Ok(layout(dirs)),
            }
        }
        fn err() -> Self {
            Self {
                layout: Err("disk gone".to_string()),
            }
        }
    }

    impl WorkspaceLayoutReader for StubReader {
        fn layout(&self) -> Result<WorkspaceLayout, String> {
            self.layout.clone()
        }
    }

    // what this catches: the layout surfaces as a delivery the brain renders into
    // the [workspace-map] grounding block — and it names the REAL top-level dirs,
    // so a reasoner can avoid the `src/**/*.rs` guess that matched nothing.
    #[tokio::test]
    async fn layout_surfaces_with_real_dirs() {
        let reader = Arc::new(StubReader::ok(&["apps", "core", "docs", "src"]));
        let source = WorkspaceMapSource::new(persona(), reader);
        let delivery = source.deliver(&ctx(), 512, ResolutionPreference::Raw).await;
        assert_eq!(delivery.items.len(), 1);
        let content = &delivery.items[0].content;
        // Both `core` and `src` are present — the exact ambiguity that tripped
        // the eval. The map names both; it never says which holds the code.
        assert!(content.contains("core"));
        assert!(content.contains("src"));
        assert!(content.contains("/repo"));
        // The generic path-semantics rule that lets her avoid assuming `src/`.
        assert!(content.contains("**/"));
        assert_eq!(delivery.items[0].metadata["top_level_dirs"][1], "core");
        // Explicitly refutes the recalled "workspace is empty" confabulation with a
        // concrete count, so live ground truth beats a stale memory.
        assert!(content.contains("NOT empty"), "refutes the empty-belief: {content}");
        assert!(content.contains("4 top-level directories"), "states the count: {content}");
    }

    // what this catches: we do NOT steer — the block never tells her which
    // directory holds the source (no "Rust is under core/" prose). It states the
    // layout and the tool semantics; the reasoning is hers.
    #[tokio::test]
    async fn grounds_without_steering() {
        let reader = Arc::new(StubReader::ok(&["core", "src"]));
        let source = WorkspaceMapSource::new(persona(), reader);
        let delivery = source.deliver(&ctx(), 512, ResolutionPreference::Raw).await;
        let content = delivery.items[0].content.to_lowercase();
        assert!(
            !content.contains("rust is under") && !content.contains("rust lives"),
            "must not name where code lives — that is steering, not grounding: {content}"
        );
    }

    // what this catches: a layout read failure degrades to empty, never panics —
    // cognition stays up if the filesystem is momentarily unreadable.
    #[tokio::test]
    async fn read_error_returns_empty_no_panic() {
        let source = WorkspaceMapSource::new(persona(), Arc::new(StubReader::err()));
        let delivery = source.deliver(&ctx(), 512, ResolutionPreference::Raw).await;
        assert!(delivery.items.is_empty());
        assert_eq!(delivery.resolution_used, ResolutionPreference::Placeholder);
    }

    // what this catches: cross-persona ctx gets nothing (defense in depth).
    #[tokio::test]
    async fn cross_persona_ctx_returns_empty() {
        let source = WorkspaceMapSource::new(persona(), Arc::new(StubReader::ok(&["core"])));
        let alien = Uuid::parse_str("00000000-0000-0000-0000-000000000bbb").unwrap();
        let delivery = source
            .deliver(
                &RagContext::for_persona(alien, 1_000_000),
                512,
                ResolutionPreference::Raw,
            )
            .await;
        assert!(delivery.items.is_empty());
        assert_eq!(delivery.resolution_used, ResolutionPreference::Placeholder);
    }

    // what this catches: an empty workspace (no dirs) still renders a valid block
    // that says "(none)" rather than an empty/garbled list.
    #[tokio::test]
    async fn empty_layout_renders_none() {
        let source = WorkspaceMapSource::new(persona(), Arc::new(StubReader::ok(&[])));
        let delivery = source.deliver(&ctx(), 512, ResolutionPreference::Raw).await;
        assert_eq!(delivery.items.len(), 1);
        assert!(delivery.items[0].content.contains("(none)"));
    }

    // what this catches: an absurdly tiny budget never overspends — either no
    // block, or a block that fits the budget (same contract as the doctrine).
    #[tokio::test]
    async fn tiny_budget_never_overspends() {
        let reader = Arc::new(StubReader::ok(&["apps", "core", "docs", "src", "tools"]));
        for budget in [1u32, 2, 3, 5, 8, 20, 50] {
            let source = WorkspaceMapSource::new(persona(), reader.clone());
            let delivery = source
                .deliver(&ctx(), budget, ResolutionPreference::Raw)
                .await;
            assert!(
                delivery.tokens_used <= budget,
                "budget {budget}: overspent ({} > {budget})",
                delivery.tokens_used
            );
        }
    }

    // what this catches: the production cwd reader actually reads the real
    // process workspace and returns a non-empty, sorted directory list — the
    // same machinery the code tools resolve against (drift-proofing).
    #[test]
    fn cwd_reader_reads_real_workspace() {
        let layout = CwdWorkspaceLayoutReader
            .layout()
            .expect("cwd layout must read");
        assert!(
            !layout.top_level_dirs.is_empty(),
            "a real checkout has top-level directories"
        );
        let mut sorted = layout.top_level_dirs.clone();
        sorted.sort();
        assert_eq!(layout.top_level_dirs, sorted, "dirs must be sorted");
    }

    // what this catches: the citizen-layer reader roots at the persona's OWN
    // workspace when it exists (the #49 swap — map root == the tools' root), and
    // falls back to the shared base (cwd) when the layer isn't provisioned yet —
    // truthful either way, never empty, never a panic. Here the peer has no layer
    // (random id under a temp home), so the fallback path must yield the real cwd
    // layout rather than erroring.
    #[test]
    fn citizen_layer_reader_falls_back_to_base_when_unprovisioned() {
        let reader = CitizenLayerWorkspaceLayoutReader {
            peer: "00000000-0000-0000-0000-0000000000ff".to_string(),
        };
        let layout = reader.layout().expect("unprovisioned layer falls back to base cwd");
        assert!(
            !layout.top_level_dirs.is_empty(),
            "fallback to base cwd yields the real checkout layout, never empty"
        );
    }
}
