// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServingPlan } from "./ServingPlan";

/**
 * Result for `serving/plan` — the current decision, or `null` before the first
 * plan is computed. A named wrapper (the typed registry requires a named Result
 * type; a bare `Option<T>` has no importable TS dependency).
 */
export type ServingPlanResult = { 
/**
 * The serving decision for this host, or `None` before the daemon's first
 * plan recompute.
 */
plan?: ServingPlan, };
