// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a region's work is ORIENTED toward — the static class the orientation
 * budget groups regions by (docs/architecture/BEING-SOCIETY-GOVERNOR.md, rail R2).
 *
 * Like [`ComputeClass`], this is **declared metadata**, NOT a runtime read of the
 * region's output: it tells the governor which budget class a tick draws time from,
 * never what the region should think. Grouping by it is mechanical (the no-heuristics
 * line stays uncrossed — the governor allocates *time*, the region stays causal).
 */
export type Orientation = "reactive" | "self-directed" | "speciation";
