// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reserved: streaming result. **Returning a Stream result today is a
 * runtime error.** The variant exists so the enum's shape is fixed
 * before handlers begin migrating; the wire protocol (frame format,
 * correlation IDs, backpressure, cancellation) is the open piece.
 *
 * When the protocol lands, `correlation_id` will tie incoming stream
 * frames to this stream so the consumer can match. The struct is
 * `#[non_exhaustive]` so adding fields later is non-breaking for
 * external code; internal code uses [`StreamPlaceholder::new`] to
 * construct rather than the field-init shorthand.
 */
export type StreamPlaceholder = { 
/**
 * Correlation ID a future wire protocol will use to tie incoming
 * stream frames to this stream handle. Today: unused; reserved.
 */
correlation_id: string, };
