/**
 * Auto-generated by compile-sass.ts
 * Source: grid-status-section.scss
 * DO NOT EDIT DIRECTLY - edit the .scss file instead
 */

export const styles = `
:host{display:block;padding:8px 10px;font-size:11px;color:var(--content-primary, #e0e0e0)}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;cursor:pointer}.header:hover{opacity:.85}.summary{display:flex;align-items:center;gap:6px}.status-dot{width:7px;height:7px;border-radius:50%;flex-shrink:0}.summary-text{font-weight:600;color:var(--content-primary, #e0e6ed)}.open-arrow{font-size:10px;color:var(--content-secondary, #8a92a5)}.transports{display:flex;gap:6px;margin-bottom:6px}.transport-badge{padding:1px 5px;border-radius:3px;font-size:9px;font-weight:700;font-family:var(--font-mono, monospace);text-transform:uppercase;letter-spacing:.3px}.transport-active{background:rgba(0,255,136,.12);color:rgba(0,255,136,.9);border:1px solid rgba(0,255,136,.2)}.transport-inactive{background:rgba(100,100,100,.1);color:var(--content-secondary, #8a92a5);border:1px solid rgba(100,100,100,.15)}.node-list{display:flex;flex-direction:column;gap:3px}.node-row{display:flex;align-items:center;gap:6px;padding:2px 0}.node-name{flex:1;font-size:10px;color:var(--content-primary, #e0e6ed);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.node-latency{font-size:10px;font-family:var(--font-mono, monospace);color:var(--content-secondary, #8a92a5)}.node-gpu{font-size:9px;color:rgba(0,212,255,.7);font-family:var(--font-mono, monospace)}.empty-state{text-align:center;color:var(--content-secondary, #777);font-style:italic;padding:12px 0}
`;
