// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `web/fetch`.
 */
export type WebFetchParams = { 
/**
 * The URL to fetch and read (http/https).
 */
url: string, 
/**
 * Max characters of readable text to return. Default 6000, clamped to [200, 12000].
 */
max_chars?: number, };
