// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `web/search`.
 */
export type WebSearchParams = { 
/**
 * What to search the web for.
 */
query: string, 
/**
 * Max results. Default 8, clamped to [1, 20].
 */
count?: number, 
/**
 * Which backend to use: "brave" (best — needs a free BRAVE_API_KEY) or
 * "duckduckgo" (keyless, works with zero setup). Omit to auto-pick the best
 * available: keyed if a key is configured, else the keyless one.
 */
adapter?: string, };
