// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inputs to `desktop`.
 */
export type DesktopParams = { 
/**
 * URL to open. Omit for the default local web client
 * (`CONTINUUM_DESKTOP_URL`, else the localhost dev URL).
 */
url?: string, 
/**
 * Re-open / focus even when a session for this URL is already active. Default
 * false — an active session is a no-op, so we never spawn a duplicate window.
 */
focus?: boolean, };
