// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandsHelpParams = { 
/**
 * The command to explain, e.g. `code/read`. OMIT it to get an INDEX of every
 * command you can call (name + one-line description) — your starting point when
 * you don't yet know which tool to use.
 */
name?: string, };
