// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoraProviderCapabilities } from "./LoraProviderCapabilities";

/**
 * Result of `ai/lora/capabilities`.
 */
export type AiLoraCapabilitiesResult = { providers: Array<LoraProviderCapabilities>, };
