// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoraAdapterView } from "./LoraAdapterView";

/**
 * Result of `ai/lora/list`.
 */
export type AiLoraListResult = { adapters: Array<LoraAdapterView>, count: number, };
