// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderInfo } from "./ProviderInfo";

/**
 * Result of `ai/providers/list`.
 */
export type AiProvidersListResult = { 
/**
 * Provider ids currently available (registered + reachable).
 */
available: Array<string>, 
/**
 * Full per-provider info.
 */
providers: Array<ProviderInfo>, 
/**
 * Convenience count of `available`.
 */
count: number, };
