// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One provider's LoRA capability descriptor.
 */
export type LoraProviderCapabilities = { provider: string, 
/**
 * Debug-rendered [`LoRACapabilities`](crate::ai::adapter::LoRACapabilities)
 * (`None` | `SingleAdapter` | `MultiLayerPaging { .. }`).
 */
capabilities: string, };
