// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "../model_registry/Capability";
import type { CostPer1kTokens } from "./CostPer1kTokens";

/**
 * Model information — ALL fields REQUIRED.
 * The adapter knows its model. No optionals, no defaults, no guessing.
 * If an adapter can't provide a field, it's not ready to register.
 */
export type ModelInfo = { id: string, name: string, provider: string, 
/**
 * What this model can do. ONE capability vocabulary across the whole
 * substrate: [`crate::model_registry::Capability`]. There is no second
 * enum and no bool mirror — modality routing (vision/audio bridge),
 * tool-use gating, and embedding/image-gen support all read this set.
 * (#55 / #65 capability collapse — ModelCapability + ModalitySet deleted.)
 */
capabilities: Array<Capability>, contextWindow: number, maxOutputTokens: number, costPer1kTokens: CostPer1kTokens, 
/**
 * Measured or estimated inference speed on current hardware.
 * Used by RAG budget and slot coordination.
 */
tokensPerSecond: number, supportsStreaming: boolean, supportsTools: boolean, };
