// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Routing observability info
 */
export type RoutingInfo = { provider: string, isLocal: boolean, routingReason: string, adaptersApplied: Array<string>, modelMapped?: string, modelRequested?: string, };
