// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage metrics
 */
export type UsageMetrics = { inputTokens: number, outputTokens: number, totalTokens: number, estimatedCost?: number, };
