// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-out envelope: the substrate's "dispatch this command on your
 * peer" shape. Serialized as JSON in the airc frame body.
 */
export type AircCommandRequest = { path: string, kind: string, env?: string, params: unknown, };
