// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AircCommandResponse } from "./AircCommandResponse";

/**
 * Server→client WS frame.
 *
 * `id` mirrors the request's correlation id so the client can resolve the
 * matching pending promise.
 *
 * Not `Eq`: the `State` variant carries a [`StateEnvelope`] whose `payload`
 * is a `serde_json::Value` (only `PartialEq`). `PartialEq` is what the tests
 * and any dedup need; `Eq` was never load-bearing here.
 */
export type WsServerMessage = { "type": "response", id: number, response: AircCommandResponse, } | { "type": "state" } & StateEnvelope | { "type": "stream_delta", room_id: string, sender_id: string, stream_id: string, seq: number, token: string, done: boolean, };
