// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatusInfo } from "./AgentStatusInfo";

/**
 * Result of `agent/list` — the live set of tracked agents. A named wrapper so the
 * wire type is a struct, not a bare `Array<T>`.
 */
export type AgentStatusList = { 
/**
 * Every agent the runtime is currently tracking (running + not-yet-evicted).
 */
agents: Array<AgentStatusInfo>, };
