// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inputs to `agent/start`.
 */
export type AgentStartParams = { 
/**
 * The task for the agent to accomplish (free-form natural language).
 */
task: string, 
/**
 * Absolute path to the workspace the agent operates in.
 */
working_dir: string, 
/**
 * Model name to drive the agent loop, e.g. `deepseek-chat`,
 * `claude-sonnet-4-5-20250929`, `gpt-4`. Must match an available provider.
 */
model: string, 
/**
 * Maximum build/test/fix iterations before the agent gives up (default 50).
 */
max_iterations: number, };
