// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the caller grades when the solve returns. Two genuinely different contracts,
 * so it is an enum on the wire, never a magic string ([[strings-to-enums]]).
 */
export type Deliverable = "answer" | "workspace";
