// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeRunParams = { 
/**
 * The recipe row's `name` in the `recipes` collection.
 */
name: string, 
/**
 * Invocation arguments, readable by steps as `$args.*`. The recipe's own
 * pipeline decides which are required — an unresolved reference fails
 * loudly, naming itself.
 */
args?: unknown, };
