// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaContext } from "./PersonaContext";
import type { Signal } from "./Signal";

/**
 * Wire envelope for `cognition/respond`: the host's raw event
 * ([`Signal`]) plus the per-persona stable context ([`PersonaContext`]).
 *
 * The legacy `handle_command` arm read these as two separate top-level
 * params (`signal` + `personaContext`); this struct deserializes the
 * same `{ signal, personaContext }` payload in one step. No `recipe`
 * field — recipes are JSON data the host walks, not something the
 * cognition layer projects; an old-shape caller that still sends a
 * `recipe` key has it ignored (serde drops unknown fields), matching
 * the arm's documented "extra `recipe` field ignored" behavior.
 */
export type RespondRequest = { 
/**
 * The host's raw pre-cognition event.
 */
signal: Signal, 
/**
 * The persona's stable per-turn context (identity, model, caps,
 * history, room). Field serializes as `personaContext` on the wire.
 */
personaContext: PersonaContext, };
