// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaItemLite } from "../cognition/MediaItemLite";
import type { SignalKind } from "./SignalKind";
import type { SignalOriginator } from "./SignalOriginator";

/**
 * Input to the cognition layer — the host's raw event, pre-cognition.
 * Open enough that ANY domain (chat, voice, video, code, game, AR)
 * emits the same shape.
 */
export type Signal = { 
/**
 * Hint about the signal's nature. The pipeline executor uses it
 * for routing decisions.
 */
kind: SignalKind, 
/**
 * Text payload of the signal. Empty when purely media-driven
 * (video frame, scene-graph blob without commentary).
 */
text: string, 
/**
 * Attached media (images, audio, video frames, scene-graph blobs).
 * Empty for pure-text signals.
 */
media: Array<MediaItemLite>, 
/**
 * Who emitted the signal.
 */
originator: SignalOriginator, 
/**
 * Wall-clock time the signal was created (ms since UNIX_EPOCH).
 */
timestampMs: number, 
/**
 * Optional message / event ID. Used for joining captures with
 * host-side records (chat message ID, frame number, etc.).
 */
messageId?: string, };
