// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `nav/close` — close one of the calling citizen's open activity
 * tabs (a persona home today; content tabs when they land). Rooms don't
 * close — the room set is membership, not tab state.
 */
export type NavCloseParams = { 
/**
 * The open activity to close (the tab's target ref).
 */
target: string, };
