// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `nav/select` — the citizen's focus after the switch.
 */
export type NavSelectResult = { 
/**
 * The current tab after the select (the target, echoed as the stored ref).
 */
current: string, 
/**
 * The previously-focused tab the citizen left, when there was one — the
 * room whose read cursor the markRead sibling advanced.
 */
previous?: string, };
