// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `code/run` — the ground truth of what running the code produced.
 */
export type CodeRunResult = { 
/**
 * Process exit code; `None` if the process was killed (timeout / signal).
 */
exitCode?: number, 
/**
 * Whether exit_code == Some(0) — the at-a-glance "did it run clean?".
 */
ok: boolean, 
/**
 * Captured stdout (full — the model owns how much it reads, we don't truncate).
 */
stdout: string, 
/**
 * Captured stderr (the traceback she needs to see to self-correct).
 */
stderr: string, 
/**
 * Wall-clock duration of the run in milliseconds.
 */
durationMs: number, 
/**
 * True if the run was killed by the safety timeout rather than exiting on its own.
 */
timedOut: boolean, };
