// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitApplyResult = { 
/**
 * What happened: applied, or checked-clean.
 */
message: string, };
