// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitDiffParams = { 
/**
 * Show STAGED changes (`--cached`) instead of unstaged working-tree changes.
 */
staged: boolean, };
