// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeNode } from "./ChangeNode";

/**
 * History query result.
 */
export type HistoryResult = { success: boolean, nodes: Array<ChangeNode>, total_count: number, error?: string, };
