// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShellExecutionStatus } from "./ShellExecutionStatus";

/**
 * Response from `code/shell-poll`.
 *
 * Returns new output since the last poll (cursor-based).
 * Call repeatedly until `finished` is true.
 */
export type ShellPollResponse = { execution_id: string, status: ShellExecutionStatus, 
/**
 * New stdout lines since last poll.
 */
new_stdout: Array<string>, 
/**
 * New stderr lines since last poll.
 */
new_stderr: Array<string>, 
/**
 * Exit code (present when finished).
 */
exit_code?: number, 
/**
 * True when the execution is no longer running.
 */
finished: boolean, };
