// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceKind } from "./ResourceKind";

/**
 * What a consumer reports it is holding right now — its self-declared
 * footprint, reconciled by the daemon against the hardware scan. `detail` is
 * human/grid-facing ("qwen3-coder-30b weights", "render target pool").
 */
export type ConsumerFootprint = { kind: ResourceKind, bytes: number, detail: string, };
