// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceKind } from "./ResourceKind";

/**
 * Why a lease operation failed. Fail-loud — the authority never silently
 * over-grants or silently no-ops a missing lease.
 */
export type LeaseError = { "error": "insufficientCapacity", kind: ResourceKind, requested: number, available: number, } | { "error": "duplicateLease", lease_id: string, } | { "error": "missingLease", lease_id: string, } | { "error": "expiredLease", lease_id: string, };
