// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReclaimStatus } from "./ReclaimStatus";

/**
 * The consumer's confirmed answer: how many bytes it actually freed, and the
 * disposition. The authority trusts `freed_bytes` only after the matching
 * lease `release` lands — this is the report, the ledger mutation is separate.
 */
export type ReclaimOutcome = { freedBytes: number, status: ReclaimStatus, detail?: string, };
