// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReclaimReason } from "./ReclaimReason";
import type { ResourceKind } from "./ResourceKind";

/**
 * The ask: free at least `target_bytes` of `kind` by `deadline_ms`. Patient —
 * `deadline_ms` is a real grace window the consumer may use to finish an
 * in-flight frame / inference before releasing.
 */
export type ReclaimRequest = { kind: ResourceKind, targetBytes: number, deadlineMs: number, reason: ReclaimReason, };
