// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three physical resource axes one machine (or one container) hands out.
 * Ports/handles can join later; these are the memory/disk axes the authority
 * must account for first (the ones that OOM or ENOSPC a node).
 */
export type ResourceKind = "vram" | "ram" | "disk";
