// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Empty input contract shared across the `resources/*` read verbs — each reports the
 * machine's live state and takes no parameters. One contract rather than a placeholder
 * struct per verb (compression principle), mirroring `system::SystemQuery`.
 */
export type ResourcesQuery = Record<symbol, never>;
