// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingProvider } from "./EmbeddingProvider";

/**
 * Embedding model configuration
 */
export type EmbeddingModel = { name: string, dimensions: number, provider: EmbeddingProvider, maxTokens: number | null, };
