// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-collection migration status
 */
export type MigrationStatus = "pending" | "inprogress" | "completed" | "failed" | "paused";
