// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventClassChannelStrategy } from "./EventClassChannelStrategy";
import type { EventClassUnknownSchemaPolicy } from "./EventClassUnknownSchemaPolicy";

/**
 * Caller-supplied event-class declaration. All optional fields fill with
 * conservative defaults (no broadcast, no airc cost).
 */
export type EventClassConfig = { 
/**
 * Distribute this event class through the airc transport in addition
 * to the local + WebSocket transports?
 *
 * `false` (default) — local + WebSocket only. Zero airc cost.
 * `true`  — also durable on the airc log; reaches cross-machine
 *           subscribers via the AircEventTransport (L1-2).
 */
broadcast: boolean, 
/**
 * How the event-name + payload map to an airc channel when broadcast
 * is `true`. Defaults to `Local` when `broadcast: false`, otherwise
 * required (validation throws on missing-when-broadcast).
 */
channel?: EventClassChannelStrategy, 
/**
 * Wire-format schema version. Subscribers fail loud on unknown
 * versions per `on_unknown_schema`. Bump when the payload shape
 * changes incompatibly.
 */
schemaVersion: string, 
/**
 * Action when a subscriber receives an event whose declared
 * `schemaVersion` doesn't match its build. Default `Fail`.
 */
onUnknownSchema?: EventClassUnknownSchemaPolicy, 
/**
 * Optional human-readable description for `grid/show-event-classes`
 * and similar introspection. Not load-bearing at runtime.
 */
description?: string, };
