// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Budget limits — any field None means unlimited
 */
export type BudgetLimits = { 
/**
 * e.g. 3600 (1 hour)
 */
maxTimeSecs?: number | undefined, 
/**
 * e.g. 5.00
 */
maxCostUsd?: number, 
/**
 * e.g. 1_000_000
 */
maxTokens?: number | undefined, 
/**
 * Full pipeline loop iterations (NOT agent turns)
 */
maxIterations?: number, };
