// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When a sentinel's terminal state should wake up the owning persona's
 * consciousness. Mirrors the TS `EscalationCondition` union; ts-rs
 * emits the same string literals.
 */
export type EscalationCondition = "error" | "timeout" | "unfamiliar" | "approval_needed" | "complete";
