// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EscalationRule } from "./EscalationRule";

/**
 * Escalation metadata captured at sentinel start. The substrate
 * dispatcher in [`super::escalation`] reads this on completion to
 * route the terminal event into the persona's inbox + memory.
 *
 * Pre-#225 this was the wire payload of the TS `sentinel/escalate`
 * command. Now everything is in-process Rust; the field set is the
 * same so existing call sites compile unchanged.
 */
export type SentinelEscalation = { 
/**
 * Owning persona for inbox delivery
 */
parentPersonaId?: string, 
/**
 * SentinelEntity ID for execution history persistence
 */
entityId?: string, 
/**
 * Human-readable name for escalation messages
 */
sentinelName: string, 
/**
 * Caller-supplied escalation rules. `None` -> dispatcher uses
 * [`default_escalation_rules`]. The wire shape is typed (not
 * `Value` pass-through) now that TS no longer owns the schema.
 */
escalationRules?: Array<EscalationRule>, };
