// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `memory/remember`. Flat + CLI-friendly — the substrate assembles the record.
 */
export type MemoryRememberParams = { 
/**
 * The authoring agent's persona id — its airc peer id. Also the corpus key and the
 * `agent_peer_id` provenance (agent = its own peer).
 */
persona_id: string, 
/**
 * The lesson to remember. Free text; serde escapes it into the record.
 */
content: string, 
/**
 * Project / room scope — becomes the recall `room_id`, a tag, and part of context.
 */
scope: string, 
/**
 * The agent session/conversation that produced the lesson. Traceability; `None` for a
 * migrated `.md` engram.
 */
session?: string, 
/**
 * Importance (0..1). A deliberate remember defaults slightly above neutral.
 */
importance: number, };
