// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaRef } from "../identity/PersonaRef";

/**
 * Params for `memory/consolidate`. Flat + CLI-friendly.
 */
export type MemoryConsolidateParams = { 
/**
 * The persona whose received lessons to consolidate — its airc peer id / corpus key.
 */
persona_id: PersonaRef, 
/**
 * Display name carried into training provenance. Defaults to the persona id.
 */
persona_name?: string, 
/**
 * The base model the lesson-gene trains on. The operator names it for this explicit
 * command; the autonomic tick will resolve it from the serving snapshot instead.
 */
base_model: string, 
/**
 * Resume watermark: consolidate ONLY shared lessons with a timestamp strictly
 * after this (rfc3339, lexicographically ordered). Omit to consolidate all (the
 * explicit first run). The autonomic tick persists [`ConsolidateResult::latest_consolidated_ts`]
 * and passes it back here next cycle. A partial timestamp group may be retried;
 * this watermark does not provide exactly-once delivery into the trigger.
 */
since_timestamp?: string, };
