// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaRef } from "../identity/PersonaRef";

/**
 * Params for `memory/share`. Flat + CLI-friendly — the substrate assembles the shared record.
 */
export type MemoryShareParams = { 
/**
 * The RECIPIENT agent's persona id (airc peer id) — the corpus that receives the lesson.
 */
to_persona_id: PersonaRef, 
/**
 * The SHARING agent's persona id (airc peer id) — recorded as shared-by provenance.
 */
from_persona_id: PersonaRef, 
/**
 * The lesson to share. Free text; serde escapes it into the record.
 */
content: string, 
/**
 * Project / room scope — becomes the recall `room_id`, a tag, and part of context.
 */
scope: string, 
/**
 * The sharing agent's session/conversation the lesson came from. Traceability.
 */
session?: string, 
/**
 * Importance (0..1). Defaults slightly above neutral.
 */
importance: number, };
