// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OAuth 2.0 provider configuration.
 *
 * Each provider needs at minimum: `client_id`, `auth_url`, `token_url`, `scopes`,
 * and a `redirect_port` for the temporary localhost callback server.
 */
export type OAuthClientConfig = { 
/**
 * Unique provider identifier, e.g. `"github"`, `"google"`, `"huggingface"`.
 */
provider_id: string, 
/**
 * OAuth application client ID.
 */
client_id: string, 
/**
 * OAuth application client secret. `None` for public (PKCE-only) clients.
 */
client_secret?: string, 
/**
 * Authorization endpoint URL.
 */
auth_url: string, 
/**
 * Token endpoint URL.
 */
token_url: string, 
/**
 * Space-separated OAuth scopes.
 */
scopes: string, 
/**
 * localhost port for the temporary redirect-URI catcher (e.g. `47200`).
 */
redirect_port: number, 
/**
 * Optional token revocation endpoint URL.
 */
revoke_url?: string, };
