// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Memory pressure severity. Each level implies all lower levels.
 */
export type PressureLevel = "normal" | "warning" | "high" | "critical";
