// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleMemoryReport } from "./ModuleMemoryReport";
import type { PressureLevel } from "./PressureLevel";

/**
 * Complete memory pressure snapshot — published via watch channel.
 */
export type PressureSnapshot = { 
/**
 * Current pressure level
 */
level: PressureLevel, 
/**
 * Memory pressure ratio (0.0 - 1.0) = used / total
 */
pressure: number, 
/**
 * Normalized pressure (0.0 - 1.0) mapped to action zone.
 * 0.0 = at/below 80% (no concern), 1.0 = at/above 95% (emergency).
 */
normalized_pressure: number, 
/**
 * Process RSS in bytes
 */
rss_bytes: number, 
/**
 * Total physical RAM
 */
total_bytes: number, 
/**
 * Available RAM
 */
available_bytes: number, 
/**
 * Swap used in bytes
 */
swap_used_bytes: number, 
/**
 * Per-module memory breakdown (empty if no reporters registered)
 */
modules: Array<ModuleMemoryReport>, 
/**
 * Timestamp (ms since epoch)
 */
timestamp_ms: number, 
/**
 * Consecutive polls at this level (for hysteresis — don't react to single spikes)
 */
consecutive_at_level: number, };
