// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuSnapshot } from "../gpu/GpuSnapshot";
import type { CpuStats } from "./CpuStats";
import type { DiskPressureSnapshot } from "./DiskPressureSnapshot";
import type { MemoryStats } from "./MemoryStats";
import type { ProcessStats } from "./ProcessStats";

/**
 * Full system resource snapshot — returned by `system/resources` IPC command.
 */
export type SystemResourceSnapshot = { 
/**
 * CPU statistics
 */
cpu: CpuStats, 
/**
 * Memory statistics
 */
memory: MemoryStats, 
/**
 * Live GPU device stats (device-wide `used = total_bytes - free_bytes`,
 * the same system-wide framing as cpu/memory). `None` on a host with no
 * live `GpuMonitor` attached — sourced from the ONE already-detected
 * monitor (`gpu::monitor::detect()`), never a second probe. The Positron
 * SYS gauge reads this next to cpu+mem.
 */
gpu?: GpuSnapshot, 
/**
 * The volume holding the substrate's home — pressure tier, bytes, and every
 * tracked cache class the disk reporters weighed. `None` only before the disk
 * monitor's first poll. Added 2026-09-18: the 5090 sat at 0 bytes free reading
 * `Normal` and no command surface could have shown it.
 */
disk?: DiskPressureSnapshot, 
/**
 * Top processes (optional, only when requested)
 */
processes?: ProcessStats, 
/**
 * Timestamp of this snapshot (ms since epoch)
 */
timestamp_ms: number, 
/**
 * System uptime in seconds
 */
uptime_seconds: number, };
