// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inputs to `interface/capture`.
 */
export type CaptureParams = { 
/**
 * Which surface to capture: `"web"`, `"ios"`, or `"android"`.
 */
target: string, 
/**
 * Web only: the URL / local dev-server address to load
 * (e.g. `"http://localhost:5173"` or a `file://` path).
 */
url?: string, 
/**
 * Web only: viewport width in CSS px (default 1280).
 */
width?: number, 
/**
 * Web only: viewport height in CSS px (default 800).
 */
height?: number, 
/**
 * Mobile only: device identifier (iOS udid / Android adb serial). Omit to use
 * the single booted simulator / attached device.
 */
device?: string, };
