// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Avatar art style categories.
 */
export type AvatarStyle = "anime" | "stylized" | "cartoon" | "pixel" | "realistic" | "minimalist";
