// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeightedGesture } from "./WeightedGesture";

/**
 * Per-state gesture configuration. Future: LoRA adapters output personalized configs.
 */
export type CognitiveAnimationConfig = { 
/**
 * Gestures available during the Evaluating state.
 */
evaluating: Array<WeightedGesture>, 
/**
 * Gestures available during the Generating state.
 */
generating: Array<WeightedGesture>, 
/**
 * Seconds between gesture re-rolls while state persists.
 */
rerollIntervalSecs: number, };
