// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of `vector/backfill` — the per-collection tally of an embedding
 * backfill pass: how many records were embedded, already had a vector, or
 * failed.
 */
export type VectorBackfillStats = { collection: string, 
/**
 * Records examined.
 */
total: number, 
/**
 * Records freshly embedded this pass.
 */
processed: number, 
/**
 * Records skipped because they already had an embedding.
 */
skipped: number, 
/**
 * Records the embedder produced no signal for, or whose write failed.
 */
failed: number, 
/**
 * Wall-clock duration of the pass, in milliseconds.
 */
elapsedMs: number, };
