// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of `vector/stats` — how many records in a collection carry an
 * embedding, the vector dimensionality, and the in-memory cache occupancy.
 */
export type VectorStats = { collection: string, 
/**
 * Total records in the collection.
 */
totalRecords: number, 
/**
 * Records that carry a non-empty embedding.
 */
recordsWithVectors: number, 
/**
 * Dimensionality of the embeddings (0 if none indexed).
 */
vectorDimensions: number, 
/**
 * Vectors currently held in the in-memory similarity cache.
 */
cachedVectors: number, 
/**
 * RFC-3339 timestamp this snapshot was computed.
 */
lastUpdated: string, };
