// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `vector/index`.
 */
export type VectorIndexParams = { 
/**
 * The collection holding the record.
 */
collection: string, 
/**
 * The record id to attach the embedding to.
 */
id: string, 
/**
 * The embedding to store on the record's `embedding` field.
 */
embedding: Array<number>, 
/**
 * Storage handle. Defaults to "main" (the shared DB). Accepts the legacy
 * `dbPath` field name as an alias.
 */
handle?: string, };
