// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `vector/backfill`.
 */
export type VectorBackfillParams = { 
/**
 * The collection to backfill embeddings for.
 */
collection: string, 
/**
 * The record field whose text gets embedded.
 */
textField: string, 
/**
 * How many records to embed per batch. Defaults to 100.
 */
batchSize: number, 
/**
 * Optional embedding model override. Defaults to the configured embedder.
 */
model?: string, 
/**
 * Optional record filter (same shape as `data/list` filters). Restricts which
 * records get backfilled.
 */
filter?: Record<string, unknown>, 
/**
 * Storage handle. Defaults to "main" (the shared DB). Accepts the legacy
 * `dbPath` field name as an alias.
 */
handle?: string, };
