// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityKind } from "./IdentityKind";
import type { IdentitySource } from "./IdentitySource";

/**
 * The substrate's universal actor identity, ORM-backed.
 *
 * One row per active actor instance. Foreign-keyable from every
 * other entity that needs to record "which citizen did this" —
 * engram authorship, work-card claims, capture-sink scopes,
 * audit trails.
 *
 * Pattern A of `#[derive(Entity)]` per #1519: `id` is both the
 * primary key AND the airc peer_id. The macro pulls in BaseEntity
 * columns (`createdAt`, `updatedAt`, `version`) automatically;
 * the struct only declares the kind-specific fields.
 */
export type Identity = { 
/**
 * Primary key AND airc peer_id. The substrate makes no
 * distinction — your airc cryptographic identity IS your
 * substrate identity. Other entities FK on this.
 */
id: string, 
/**
 * What kind of actor this identity belongs to. Indexed so
 * queries like "show me all live Persona identities" or
 * "count active Claude sessions" stay O(log N).
 */
kind: IdentityKind, 
/**
 * Human-readable label. For personas this is the persona
 * name (Maya, Niko, ...). For Claude/Codex sessions it's a
 * session identifier (e.g., "Claude-Opus-4.7-2026-06-04T..."
 * — runtime decides shape). For humans it's the operator's
 * chosen handle. Indexed for query-by-name workflows
 * (`airc whois <name>` and similar).
 */
agentName: string, 
/**
 * Absolute path to this identity's airc home dir on disk.
 * Carries the keypair (`identity.key`) and the airc state DB.
 * String (not PathBuf) because PathBuf doesn't have native
 * SQLite affinity; convert at the use site.
 */
homePath: string, 
/**
 * The room this identity defaults to subscribing to at
 * bootstrap. For personas it's the spawned-into room
 * (continuum's default_room). For Claude/Codex it's the
 * room their work coordinates in. Indexed for "show me
 * every identity in room X" queries.
 */
defaultRoom: string, 
/**
 * Whether this identity was rehydrated from disk or minted
 * fresh during this bootstrap. Indexed for telemetry —
 * "what fraction of citizens are fresh this hour?" is a
 * meaningful operator question.
 */
source: IdentitySource, 
/**
 * For `IdentityKind::Agent` rows, names the SPECIFIC external
 * AI provider — "claude", "codex", "gemini", "hermes",
 * "openclaw", future. Lowercase by convention (Joel 2026-06-04
 * "Use always lowercase"). `None` for non-Agent kinds.
 *
 * Why a `String` and not a sub-enum: extensibility. Adding a
 * new provider should NOT churn the IdentityKind enum or
 * require enum-as-JSON migration. The substrate routes
 * agent-provider-specific logic through this string at the
 * few sites that need it (tool-use harness, model-tier
 * metadata).
 *
 * The directory layout for Agent kinds carries the provider:
 * `citizens/agents/<provider>/<label>/airc/`. Non-Agent kinds
 * use `citizens/<kind>/<label>/airc/` (no provider segment).
 */
agentProvider?: string, };
