// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a CALLER writes when it means "that persona" — a full UUID, an 8-char
 * short-id, or a name (`"Asha"`). Deliberately NOT an identity.
 *
 * ## Why this is a separate type from [`PeerId`]
 *
 * Both were `String`, so nothing stopped an unresolved reference being stored,
 * compared, or handed to a subsystem as though it were an identity — and that is
 * not hypothetical. `PersonaWorkspaceRegistry::resolve_persona` exists precisely
 * to close "the loose-`String` id boundary … the defect class that fed a dead id
 * to a doomed eval" (its own words), and when this type was introduced it had
 * **one** production caller against 55 `persona_id: String` fields. The check was
 * right and almost nothing called it — the nastiest shape a check can have.
 *
 * A name is not an identity: it is ambiguous (two personas can share one), it is
 * mutable, and it is only meaningful against a live roster. So the two roles get
 * two types, and the ONLY bridge between them is resolution:
 *
 * ```ignore
 * let id: PeerId = registry.resolve_persona(&params.persona)?;  // the one door
 * ```
 *
 * Params carry a `PersonaRef`. Everything downstream carries a [`PeerId`]. Passing
 * an unresolved reference where an identity belongs is now a type error rather
 * than a runtime surprise three subsystems away.
 *
 * Wire shape is unchanged — `#[serde(transparent)]` over the string a caller
 * already sends, so no client, recipe, or stored payload has to change.
 */
export type PersonaRef = string;
