/**
 * Message Factory - Strict Message Creation
 *
 * Creates a fully-populated `ChatMessageEntity`. Caller MUST supply real
 * `roomId` and `senderId` UUIDs. The previous version accepted the string
 * aliases `'general'` / `'claude'` / `'owner'` and silently substituted
 * deterministic UUIDs from `DEFAULT_ROOMS` / `DEFAULT_USERS` — that's
 * exactly the antipattern that produced the ghost General tab and split
 * messages across "real" and "deterministic" room IDs. Joel: "the UUID
 * should be GENERATED BY THE SYSTEM AND GLOBALLY UNIQUE."
 *
 * Resolve a uniqueId → UUID at the call site via
 * `Commands.execute('data/list', { collection: ROOMS, filter: { uniqueId } })`
 * and pass the resolved UUID into the factory. The factory does not do
 * lookups itself (sync API; lookups are async + DB-bound; the layer above
 * already has both).
 */

import { ChatMessageEntity } from '../entities/ChatMessageEntity';
import type { UUID } from '../../core/types/CrossPlatformUUID';
import { generateUUID } from '../../core/types/CrossPlatformUUID';
import type { UserType } from '../entities/UserEntity';

export interface CreateMessageOptions {
  text: string;
  roomId: UUID;
  senderId: UUID;
  senderName: string;
  senderType: UserType;
  status?: 'sending' | 'sent' | 'failed';
  priority?: 'low' | 'normal' | 'high' | 'urgent';
}

/**
 * Build a `ChatMessageEntity` from already-resolved IDs and labels.
 * Generates a fresh `id` (uuidv4) and timestamp; everything else comes
 * from the caller.
 */
export function createMessage(opts: CreateMessageOptions): ChatMessageEntity {
  const message = new ChatMessageEntity();
  message.id = generateUUID();
  message.content = { text: opts.text, attachments: [] };
  message.roomId = opts.roomId;
  message.senderId = opts.senderId;
  message.senderName = opts.senderName;
  message.senderType = opts.senderType;
  message.status = opts.status ?? 'sent';
  message.priority = opts.priority ?? 'normal';
  message.timestamp = new Date();
  message.reactions = [];
  return message;
}

/**
 * Stub kept ONLY so `tests/integration/ai-chat-participation.test.ts` still
 * compiles. The previous implementation silently wrote to a deterministic
 * "owner" UUID that didn't match the seeded user, so the test was always
 * broken at the persistence layer. Throws loudly if anyone actually invokes
 * it — the test needs to resolve the real roomId + senderId first via
 * `data/list { uniqueId: ... }` before calling `createMessage` directly.
 *
 * @deprecated Resolve real UUIDs and call `createMessage` instead.
 */
export function createHumanMessage(_text: string): never {
  throw new Error(
    'createHumanMessage was removed: it routed messages to a deterministic ' +
    'UUID that did not match the seeded Owner user. Resolve the real ' +
    "owner's UUID via data/list { collection: USERS, filter: { uniqueId: 'owner' } } " +
    'and call createMessage(opts) with the resolved ids.'
  );
}

/**
 * @deprecated See {@link createHumanMessage}.
 */
export function createAIMessage(_text: string): never {
  throw new Error(
    'createAIMessage was removed: it routed messages to a deterministic ' +
    'UUID that did not match any seeded persona. Resolve the persona\'s ' +
    "real UUID via data/list { collection: USERS, filter: { uniqueId: ... } } " +
    'and call createMessage(opts) with the resolved ids.'
  );
}
