// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The before/after pixel delta of the patch — the fraction of the (re-)observed
 * frame the CSS actually moved. The wire mirror of `@continuum/perception`'s
 * `Delta`; present when the adapter's session computed it cheaply, absent
 * otherwise (never fabricated).
 */
export type HotEditDelta = { 
/**
 * Pixels that changed between the pre-patch and post-patch frames.
 */
pixelsChanged: number, 
/**
 * Total pixels compared.
 */
totalPixels: number, 
/**
 * `pixels_changed / total_pixels`, 0..1. Mismatched frame sizes read as 1
 * (a layout-scale change).
 */
ratio: number, };
