// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much detail a look returns for each frame — the persona's fidelity knob.
 * `Thumbnail` is the cheap default (the ~480w ambient look, shared with the warm
 * band); `Full` is the raw frame for looking closely. A specific pixel size is a
 * governor concern (the attention-priced resolution field, #173), not something a
 * persona names — so the persona surface offers only these two intents.
 */
export type LookDetail = "thumbnail" | "full";
