// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step a persona takes on a live page. A closed set: the eye-node maps each onto the
 * `DomSurface` driver (Playwright), and a surface that cannot perform one refuses it
 * loudly rather than skipping it. Selectors are CSS selectors, aimed at the element tree an
 * observation returns.
 */
export type PerceptionAction = { "kind": "click", selector: string, } | { "kind": "type", selector: string, text: string, } | { "kind": "press", key: string, } | { "kind": "hover", selector: string, } | { "kind": "goto", url: string, } | { "kind": "hotPatchCss", css: string, };
