// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProbeBox } from "./ProbeBox";

/**
 * One node of THE STRUCTURE a persona reasons over — a DOM element, a scene-graph
 * node, a layout box. Surface-neutral: identity, geometry, text, a few attrs.
 * Recursive (`children`), so the whole tree is one value. The wire mirror of
 * `@continuum/perception`'s internal `ProbeNode`; the provider maps one onto the
 * other at the boundary.
 */
export type ProbeNode = { 
/**
 * Element tag / node type (`div`, `button`; a scene node's payload kind).
 */
tag: string, 
/**
 * Accessibility role, when the surface exposes one (`button`, `heading`).
 */
role?: string, 
/**
 * Accessible / display name — the human-meaningful label (a scene node's id).
 */
name?: string, 
/**
 * Visible text directly on this node (not its descendants).
 */
text?: string, 
/**
 * Projected 2D bounds in the rendered frame.
 */
box?: ProbeBox, 
/**
 * A curated set of load-bearing attributes (`id`, `class`, `href`; for a scene
 * node: `position`, `scale`, `kind`).
 */
attrs?: { [key in string]: string }, 
/**
 * The CRAFT FACTS a design grade measures — a DECLARED subset of computed
 * style (color, background-color, font-size/-weight/-family, margin,
 * padding, display, overflow, z-index). DOM surfaces fill it; surfaces
 * with no style system (a scene graph) omit it. Additive + optional, so
 * every adapter that predates it stays wire-compatible.
 */
style?: { [key in string]: string }, 
/**
 * Child nodes, in document/scene order.
 */
children: Array<ProbeNode>, };
