// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One measured-craft criterion over the whole observed tree.
 */
export type StyleCheck = { 
/**
 * Human-readable statement — rendered on the scorecard.
 */
description: string, } & ({ "kind": "rhythm", 
/**
 * The spacing scale's base steps in px (e.g. [8.0] for an 8px grid).
 */
scalePx: Array<number>, 
/**
 * How far a gap may sit from the scale (px).
 */
tolerancePx: number, 
/**
 * Minimum measurable sibling gaps for the criterion to be attestable.
 */
minGaps: number, } | { "kind": "hierarchy", } | { "kind": "noHorizontalOverflow", viewportWidth: number, 
/**
 * Sub-pixel/scrollbar forgiveness (px).
 */
tolerancePx: number, });
