// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A card's lifecycle state — mirrors airc's `CardState`
 * variant-for-variant. positron owns this copy so the contract library
 * stays free of an `airc-work` dependency; the continuum projector maps
 * airc `CardState` → this at the seam.
 */
export type KanbanCardState = "open" | "claimed" | "in_progress" | "blocked" | "review" | "merged" | "closed";
