// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A member's **loadout** — the model backing this roster slot, as the
 * display facts a tile renders (`model · size · ctx`). Neutral and
 * OPTIONAL the same way `vitals` is: an AI member's substrate MAY attach
 * it; positron carries it, never interprets it. Every field is
 * `Option` — an honest absent when the substrate hasn't resolved it
 * yet, never a fabricated capability ([[fallbacks-are-illegal-fail-loud]]).
 *
 * Distinct from `vitals` on purpose: vitals are fast-moving normalized
 * `0..=100` METERS (the live cognition pulse); a loadout is a slow-moving
 * CAPABILITY LABEL (what the member is running). A number-that-is-a-meter
 * and a number-that-is-a-token-count are different data with different
 * render rules, so they ride different fields, not one overloaded map.
 */
export type Loadout = { 
/**
 * The served model id, verbatim from the binding (`"devstral-24b"` /
 * `"claude-opus-4-8"` / …). `None` = the member reports no bound model
 * (unresolved) — an honest unknown, never a placeholder name.
 */
model?: string, 
/**
 * Total parameter count of the served model, RAW (e.g. `24_000_000_000`
 * for a 24B model) — the app formats the unit (`24B` / `671B` / `300M`).
 * Sourced from the model registry row's GGUF-hydrated
 * `parameter_count` (#74); NEVER sniffed from the model NAME
 * ([[models-are-infinite-decide-on-capability-not-name]]). `None` when
 * the row is unhydrated (a `0` count) — honest-absent, not `0B`. `u64`
 * → `number` (param counts are < 2^53, so no bigint drift, #120).
 */
params?: number, 
/**
 * The EFFECTIVE served context window in tokens (`32768` → the app
 * renders `32k`). The live binding's window (#50 single-sourced it),
 * not the model row's nominal max, so a re-home to a smaller window
 * reads true. `None`/`Some(0)` collapse to absent. `u32` → `number`.
 */
context_window?: number, };
