// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavTargetKind } from "./NavTargetKind";

/**
 * One open tab — an activity the citizen currently has open. `id` is the
 * airc ref (room id / content id / persona id) the nav idiom routes on;
 * `unread` is derived from `last_read` at projection time so the renderer
 * draws a badge without recomputing it.
 */
export type NavTab = { 
/**
 * The airc ref this tab opens (room/content/persona id, as a string so a
 * content ref that isn't a Uuid still fits).
 */
id: string, 
/**
 * Human-facing title (room name, document title, persona display name).
 */
title: string, 
/**
 * What kind of thing this tab points at — drives icon + route.
 */
kind: NavTargetKind, 
/**
 * Unread count since `last_read` for this tab's room (0 for non-room
 * tabs, or a fully-read room). Derived at projection, not stored twice.
 */
unread: number, 
/**
 * The activity **purpose** of what this tab opens (`"chat"`, `"foundry"`,
 * …) — the recipe-defined nature resolved through the room-purpose seam
 * ([[room-purpose-is-per-recipe-not-an-enum]]). A renderer draws it as the
 * tab/room's description line and MAY facet on it. Empty = unresolved —
 * an honest unknown, never a fabricated purpose. `#[serde(default)]` so a
 * tab serialized before this field folds as empty, never dropped.
 */
purpose: string, 
/**
 * The PARENT activity's ref, when this activity nests under another —
 * a solve room under its benchmark run room, a design review under its
 * project (#2632: the rail is a tree, not a list). Empty = top-level.
 * Renderers group children under their parent; the raw ref stays a
 * tooltip/copy affordance, never the reading line.
 */
parent_ref: string, 
/**
 * Humanized label for the reading line (`django-10914 · Atlas`) when the
 * raw title is a substrate identifier. Empty = use `title` as-is.
 * Display labels humanize; URIs address; UUIDs identify — three jobs,
 * never conflated (Joel, 2026-08-30).
 */
display_label: string, 
/**
 * Whether the citizen has this activity OPEN — selected it at least once
 * (`nav/select`) and not closed it (`nav/close`) — as opposed to merely
 * present in the room set. The rail lists the SET; the tab strip renders
 * only the opened ones (caught live 2026-09-03: 49 identical tabs, one per
 * room the daemon knew). The current tab is always opened.
 */
opened: boolean, };
