// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavBookmark } from "./NavBookmark";
import type { NavTab } from "./NavTab";

/**
 * The citizen's navigation state — open tabs, the current one, per-room read
 * cursors, and bookmarks. The single define-once nav model every surface
 * (desktop panels / phone tabs / terminal keys / persona menu) renders in its
 * own idiom, and the web additionally projects onto the URL.
 */
export type NavViewState = { 
/**
 * Whose nav state this is (the scope's citizen). Per-user, unlike the
 * per-room chat/wall/kanban views.
 */
user_id: string, 
/**
 * The active tab/room ref, or `None` when nothing is open (a fresh
 * citizen with an empty workspace — a valid view, not an error).
 */
current_tab?: string, 
/**
 * Open tabs, in the citizen's arrangement order.
 */
open_tabs: Array<NavTab>, 
/**
 * Per-room last-read cursor (room ref → last-read timestamp, ms). THE
 * keystone dual-consumer row: human unread badge + persona RAG cursor.
 */
last_read: Record<string, number>, 
/**
 * Pinned quick-nav targets.
 */
bookmarks: Array<NavBookmark>, };
