// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricSeriesView } from "./MetricSeriesView";

/**
 * The node's live resource view — what the SYS gauge draws.
 */
export type SystemMetricsViewState = { 
/**
 * The series, in display order (cpu, mem, gpu…). A resource the node
 * doesn't have (no GPU) is ABSENT, never a fabricated flat line.
 */
series: Array<MetricSeriesView>, 
/**
 * Sample cadence in milliseconds — lets a renderer label the window span
 * ("last 3 min") from the data instead of hardcoding it.
 */
sample_interval_ms: number, };
