//! Per-persona airc runtime — the substrate piece that makes a
//! persona a first-class airc citizen.
//!
//! ### Doctrine
//!
//! Per memory `personas-are-citizens-airc-is-identity-provider`: a
//! persona is NOT a continuum-internal queue row fronted by a
//! broker. It's a citizen on the substrate — same kind as Joel-at-
//! a-terminal, Claude-in-a-tab, OpenClaw, Hermes. Each persona
//! gets:
//!
//! - Its own `$AIRC_HOME` under `~/.continuum/personas/<name>/airc/`
//!   — NOT inside any other scope's airc home, to keep the citizen
//!   a peer rather than a sub-citizen of continuum's own scope.
//! - Its own Ed25519 identity, generated by airc-lib's
//!   `LocalIdentity::load_or_generate_as` (transitively, via
//!   `Airc::attach_as`). Continuum does not mint, store, or sign
//!   with persona keys — that's airc's job entirely.
//! - Its own `airc_lib::Airc` handle obtained via
//!   `Airc::attach_as(home, agent_name, socket)` — daemon-connected
//!   so the persona can `subscribe()` to live rooms and `say()` /
//!   `publish()` under its own peer_id.
//! - Membership in the same continuum room Joel publishes into
//!   (per "I expect your general room and theirs to be the same
//!   room").
//!
//! ### What this module IS
//!
//! - A lifecycle handle holding the persona's `Arc<airc_lib::Airc>`
//!   and the join handle of its inbound pump task.
//! - A `bootstrap` constructor that does the airc-side identity
//!   ceremony + room-join + inbound subscription, all through
//!   airc-lib's public surface (no shelling out to `airc init`).
//! - A `publish_text` helper delegating to `Airc::say` — the same
//!   shape `airc msg` uses, no continuum-side wrapping.
//!
//! ### What this module is NOT
//!
//! Per the anti-patterns the design workflow named for refusal:
//!
//! - NOT a "ChatService::sendAs(persona_id, text)" — there's no
//!   public method that takes a persona_id and routes internally.
//!   Whoever calls `publish_text` already HAS the persona's
//!   runtime handle. The "persona-id keyed dispatch" lives in the
//!   registry (one level up), not in this struct.
//! - NOT a translation layer from `TranscriptEvent` to a continuum-
//!   internal `ChatMessage` shape. Events surface in their native
//!   airc form for downstream consumers to dispatch on.
//! - NOT a holder of the persona's secret key. The keypair lives
//!   inside the `Airc` handle (delegating to airc-identity) — this
//!   struct only holds the Arc.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use airc_core::{EventId, RoomId};
use airc_lib::{Airc, AircError};
use tokio::task::JoinHandle;
use tracing::{info, warn};
use uuid::Uuid;

/// Errors that can occur during persona airc-runtime bootstrap.
///
/// Each variant carries enough context for the operator to act —
/// pinning identity manually, fixing the daemon socket, etc. — per
/// the constitutional-design memory's "every error has a path
/// forward" doctrine.
#[derive(Debug, thiserror::Error)]
pub enum PersonaAircRuntimeError {
    #[error(
        "persona-home auto-migration refused for {agent_name:?}: legacy at \
         {legacy:?} AND a non-empty destination already exists at {new:?}. \
         Both paths contain state — the substrate refuses to clobber the \
         destination per [[no-fallbacks-ever]]. Inspect both directories \
         and either:\n  \
         (a) keep the destination and `rm -rf {legacy:?}` if the legacy \
         dir is stale, OR\n  \
         (b) keep the legacy dir, `rm -rf {new:?}`, and re-run to let the \
         migration complete."
    )]
    LegacyMigrationConflict {
        agent_name: String,
        legacy: PathBuf,
        new: PathBuf,
    },
    #[error(
        "persona-home auto-migration failed for {agent_name:?}: could not \
         move {legacy:?} → {new:?}: {source}"
    )]
    LegacyMigrationIoError {
        agent_name: String,
        legacy: PathBuf,
        new: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to create persona airc home {0}: {1}")]
    HomeCreate(PathBuf, std::io::Error),
    #[error("airc-lib attach_as failed for persona {agent_name:?} at {home:?}: {source}")]
    Attach {
        agent_name: String,
        home: PathBuf,
        #[source]
        source: AircError,
    },
    #[error("failed to join room {room_id} as persona {agent_name:?}: {source}")]
    Join {
        agent_name: String,
        room_id: Uuid,
        #[source]
        source: AircError,
    },
}

/// One persona's live airc connection.
///
/// Holds the persona's `Arc<Airc>` (its grid presence — identity +
/// daemon connection + room membership) and the inbound pump task
/// handle. Drop this struct to shut the persona's airc presence
/// down cleanly.
pub struct PersonaAircRuntime {
    persona_id: Uuid,
    agent_name: String,
    home: PathBuf,
    airc: Arc<Airc>,
    default_room: RoomId,
    inbound_handle: Option<JoinHandle<()>>,
    /// Where this citizen's identity came from — resumed from disk
    /// vs freshly minted. Carried for the lifetime of the runtime so
    /// telemetry surfaces (list/get IPC, future status panels) can
    /// distinguish without re-deriving from disk. Per
    /// [[substrate-is-a-good-citizen-on-the-host]]: observability
    /// honest.
    source: crate::persona::identity_provider::PersonaIdentitySource,
}

impl PersonaAircRuntime {
    /// Bootstrap a persona's airc presence.
    ///
    /// Steps:
    ///
    /// 1. Resolve the persona's home under `continuum_root/personas/
    ///    <agent_name>/airc/` and create it if absent.
    /// 2. Call `Airc::attach_as(home, agent_name, daemon_socket)`.
    ///    Internally this runs the airc-lib identity ceremony
    ///    (generate or load Ed25519 keypair, write `identity.key`,
    ///    record the local_identity row) and attaches a daemon
    ///    client for live publish + subscribe. No shelling out.
    /// 3. Resolve the room by its UUID via `default_room.as_uuid()`
    ///    and call `Airc::join(...)`. This makes the persona appear
    ///    on `airc peers` as an enrolled participant of the room.
    /// 4. (Inbound pump is wired in a follow-up; this bootstrap
    ///    returns the handle ready for that wiring.)
    ///
    /// Returns the runtime handle. On any failure surfaces a typed
    /// `PersonaAircRuntimeError` with an actionable remedy in the
    /// message — never a silent fallback.
    pub async fn bootstrap(
        persona_id: Uuid,
        agent_name: impl Into<String>,
        continuum_root: &Path,
        daemon_socket: PathBuf,
        default_room: RoomId,
        default_room_name: Option<String>,
        source: crate::persona::identity_provider::PersonaIdentitySource,
    ) -> Result<Self, PersonaAircRuntimeError> {
        let agent_name = agent_name.into();
        // Slice 4 of #142: symmetric citizens/<kind>/<label>/airc/
        // layout. Use the shared helper so every actor kind shares
        // the same path schema.
        let home = crate::context::citizen_home_path(
            continuum_root,
            crate::identity::IdentityKind::Persona,
            None,
            &agent_name,
        );

        // Migration: pre-Slice-4 layout `<root>/personas/<name>/airc/`
        // → Slice-4+ `<root>/citizens/personas/<name>/airc/`. The
        // mapping is 1:1 unambiguous and the operation is an atomic
        // rename on the same filesystem, so the substrate handles it
        // here instead of refusing to boot.
        //
        // The prior behavior was to `return Err(LegacyLayoutDetected
        // { ... })` with the exact `mv` command in the message; that
        // surfaces correctly to the operator (Joel hit it earlier
        // today migrating Paige) but forces the human into the loop
        // for an operation the substrate already knows how to do.
        //
        // Auto-migration is NOT a `[[no-fallbacks-ever]]` violation
        // — it's not a silent capability fallback; it's an explicit,
        // logged, idempotent schema migration. The migration is
        // visible via a `boot_status("persona-home", Degraded,
        // "migrated <name>: legacy → citizens/")` line so the
        // operator sees the action.
        //
        // The Degraded kind (not Ok) is intentional: the substrate
        // is reporting that this boot had to fix something. Next
        // boot — with the migration already done — falls through to
        // Ok via the persona's normal "home exists, attach" path
        // without printing anything (no boot_status call when
        // there's nothing notable to report).
        //
        // Safety: if the NEW path already has content (operator did
        // a partial manual migration), we refuse to clobber and
        // surface a typed error. Same `[[no-fallbacks-ever]]`
        // discipline as before; just narrowed to the genuinely
        // ambiguous case.
        if let Some(legacy) = crate::context::legacy_home_path(
            continuum_root,
            crate::identity::IdentityKind::Persona,
            &agent_name,
        ) {
            if tokio::fs::try_exists(&legacy).await.unwrap_or(false) {
                migrate_legacy_persona_home(&legacy, &home, &agent_name).await?;
            }
        }

        tokio::fs::create_dir_all(&home)
            .await
            .map_err(|e| PersonaAircRuntimeError::HomeCreate(home.clone(), e))?;

        let airc = Airc::attach_as(home.clone(), agent_name.clone(), daemon_socket)
            .await
            .map_err(|source| PersonaAircRuntimeError::Attach {
                agent_name: agent_name.clone(),
                home: home.clone(),
                source,
            })?;

        // ── Slice 1B of #142: collapse persona_id := peer_id ─────────────
        //
        // Per [[persona-identity-derives-from-source-id]] +
        // [[airc-is-the-session-not-a-feature]]: the substrate has ONE
        // unique identifier per actor — the airc peer_id (Ed25519
        // keypair Uuid). The continuum-side `persona_id` originally
        // minted via `Uuid::new_v4()` pre-bootstrap is the historical
        // artifact; airc-lib is the source of cryptographic truth.
        //
        // Post-bootstrap, the runtime stores `persona_id` as the
        // peer_id. Callers using `runtime.persona_id()` as a registry
        // key are then safe to also reach for `ctx.identity().id`
        // (= peer_id) from the Context trait without divergence.
        //
        // The input `persona_id` parameter is retained for API
        // continuity (callers shouldn't break) but its value is
        // logged-then-discarded. Divergence is at `debug!` level —
        // for fresh mints the divergence is the NORMAL case
        // (`ResumeOrMintProvider::mint_fresh_intent` allocates
        // `Uuid::new_v4()` before the keypair is generated, so the
        // two Uuids are statistically guaranteed to differ for every
        // fresh persona). Logging it at `warn!` would spam operators
        // at every boot. A future API cleanup drops the parameter
        // entirely and removes this branch.
        let peer_id_uuid = airc.peer_id().as_uuid();
        if persona_id != peer_id_uuid {
            tracing::debug!(
                input_persona_id = %persona_id,
                peer_id = %peer_id_uuid,
                agent_name = %agent_name,
                "PersonaAircRuntime::bootstrap: persona_id parameter ignored — \
                 runtime collapses persona_id := peer_id per Slice 1B of #142. \
                 Expected for fresh mints; a future API cleanup drops the parameter."
            );
        }
        let persona_id = peer_id_uuid;

        info!(
            persona_id = %persona_id,
            agent_name = %agent_name,
            peer_id = %airc.peer_id(),
            client_id = %airc.client_id(),
            home = %home.display(),
            "PersonaAircRuntime bootstrap: identity ready (persona_id == peer_id post-collapse)"
        );

        // Join the default room. From the daemon's perspective the
        // persona is now an enrolled participant — `airc peers`
        // from another scope MUST list this peer_id.
        //
        // CRITICAL: `Airc::join(name)` calls `ChannelName::new(name)`
        // which DERIVES a channel UUID from the name. If we pass the
        // UUID-as-string of the operator's channel, that string gets
        // interpreted as a name and produces a DIFFERENT channel.
        // The persona then sits in the derived channel while the
        // operator publishes into the canonical one — they never
        // see each other. Joining by NAME (e.g. "continuum") lands
        // both in the same channel. PR #1511 integration test caught
        // this; demo binary in slice 11 reshaped via `from_attached`
        // explicitly to work around the same hazard.
        let join_target = match default_room_name.as_deref() {
            Some(name) => name.to_string(),
            None => {
                tracing::warn!(
                    persona_id = %persona_id,
                    agent_name = %agent_name,
                    room_id = %default_room.as_uuid(),
                    "PersonaAircRuntime bootstrap: no default_room_name supplied — \
                     falling back to joining by UUID-as-string, which derives a NEW \
                     channel. Persona will likely land in the wrong room. Resolve: \
                     ensure AircModule discovers default_room_name (via `airc room` \
                     output's `room: <name>` line) and threads it through here.",
                );
                default_room.as_uuid().to_string()
            }
        };
        let room = airc
            .join(&join_target)
            .await
            .map_err(|source| PersonaAircRuntimeError::Join {
                agent_name: agent_name.clone(),
                room_id: default_room.as_uuid(),
                source,
            })?;

        info!(
            persona_id = %persona_id,
            agent_name = %agent_name,
            peer_id = %airc.peer_id(),
            joined_room = %room.channel.as_uuid(),
            room_name = %room.name,
            "PersonaAircRuntime bootstrap: joined room"
        );

        Ok(Self {
            persona_id,
            agent_name,
            home,
            airc: Arc::new(airc),
            default_room,
            inbound_handle: None,
            source,
        })
    }

    /// Wrap an already-attached + already-joined `Arc<Airc>` into a
    /// `PersonaAircRuntime`. Skips the `bootstrap` join step —
    /// useful for the demo binary that joins by NAME (the canonical
    /// path) instead of by uuid-as-string (the bootstrap path's
    /// current shape — see #133-followup note on `bootstrap`).
    ///
    /// The caller is responsible for: (1) calling `attach_as` /
    /// `join` BEFORE handing the Arc in, (2) supplying the
    /// `RoomId` matching the room they joined.
    pub fn from_attached(
        persona_id: Uuid,
        agent_name: impl Into<String>,
        home: PathBuf,
        airc: Arc<Airc>,
        default_room: RoomId,
        source: crate::persona::identity_provider::PersonaIdentitySource,
    ) -> Self {
        // Slice 1B of #142: collapse persona_id := peer_id. Same
        // rationale as in `bootstrap` above. The input parameter is
        // retained for API continuity but its value is reseated to
        // the airc-lib peer_id (cryptographic ground truth).
        let peer_id_uuid = airc.peer_id().as_uuid();
        let agent_name = agent_name.into();
        if persona_id != peer_id_uuid {
            // Expected for fresh mints — see equivalent doc in
            // `bootstrap` above. `debug!` not `warn!` to avoid log
            // spam at every boot.
            tracing::debug!(
                input_persona_id = %persona_id,
                peer_id = %peer_id_uuid,
                agent_name = %agent_name,
                "PersonaAircRuntime::from_attached: persona_id parameter \
                 ignored — runtime collapses persona_id := peer_id per Slice \
                 1B of #142."
            );
        }
        Self {
            persona_id: peer_id_uuid,
            agent_name,
            home,
            airc,
            default_room,
            inbound_handle: None,
            source,
        }
    }

    /// The persona's stable continuum identifier.
    pub fn persona_id(&self) -> Uuid {
        self.persona_id
    }

    /// Where this citizen's identity came from — resumed vs minted.
    pub fn source(&self) -> crate::persona::identity_provider::PersonaIdentitySource {
        self.source
    }

    /// The persona's airc agent_name (matches what shows up in
    /// `airc peers` / `airc whois`).
    pub fn agent_name(&self) -> &str {
        &self.agent_name
    }

    /// The persona's airc home directory.
    pub fn home(&self) -> &Path {
        &self.home
    }

    /// The persona's `Arc<Airc>` handle. Cognition + outbound paths
    /// hold this Arc to reach the persona's grid presence — for
    /// `say`, `publish`, `subscribe`, `peer_id`, etc. Direct access
    /// is intentional: there's no continuum-side wrapper between a
    /// persona and its own airc handle.
    pub fn airc(&self) -> &Arc<Airc> {
        &self.airc
    }

    /// Convenience: publish a plain text message in the persona's
    /// default room, signed under the persona's identity. Equivalent
    /// to `self.airc().say(text)`. Exists so the common case reads
    /// cleanly at the call site.
    pub async fn say(&self, text: &str) -> Result<EventId, AircError> {
        self.airc.say(text).await
    }

    /// The default room the persona joined at bootstrap.
    pub fn default_room(&self) -> RoomId {
        self.default_room
    }
}

// AircCitizen + AircTranscriptReader impls — substrate's universal
// airc-handle interface, satisfied by the production runtime. Per
// [[personas-are-citizens-airc-is-identity-provider]] the trait IS the
// citizen surface; the concrete runtime is one impl among future
// peers (human, web, browser). See `persona::airc_citizen` for the
// trait definition + rationale.
#[async_trait::async_trait]
impl crate::persona::airc_source::AircTranscriptReader for PersonaAircRuntime {
    async fn page_recent(
        &self,
        limit: usize,
    ) -> Result<Vec<airc_lib::TranscriptEvent>, AircError> {
        self.airc.page_recent(limit).await
    }
}

#[async_trait::async_trait]
impl crate::persona::airc_citizen::AircCitizen for PersonaAircRuntime {
    fn peer_id(&self) -> Uuid {
        self.airc.peer_id().as_uuid()
    }

    async fn subscribe(&self) -> Result<airc_lib::EventStream, AircError> {
        self.airc.subscribe().await
    }

    async fn say(&self, text: &str) -> Result<EventId, AircError> {
        self.airc.say(text).await
    }
}

impl Drop for PersonaAircRuntime {
    fn drop(&mut self) {
        if let Some(handle) = self.inbound_handle.take() {
            handle.abort();
        }
        // Arc<Airc> drops alongside the runtime; airc-lib handles
        // its own cleanup (daemon connection close, identity state
        // flush).
        warn!(
            persona_id = %self.persona_id,
            agent_name = %self.agent_name,
            "PersonaAircRuntime dropped — persona left the grid"
        );
    }
}

/// Move a persona's legacy `<root>/personas/<name>/airc/` tree to
/// the post-Slice-4 `<root>/citizens/personas/<name>/airc/` location.
///
/// Idempotency / safety contract:
///
/// - Caller has already verified `legacy` exists.
/// - If `new` already exists AND is empty (or doesn't exist at all),
///   we create `new`'s parent, then `rename` the legacy dir into
///   place. This is atomic on the same filesystem and preserves the
///   persona's identity.key + admission_state.sqlite + every other
///   piece of airc state intact.
/// - If `new` already exists AND is non-empty, we refuse — both
///   paths have content and the substrate can't safely pick a
///   winner. Surface [`LegacyMigrationConflict`] with the exact
///   operator-actionable recovery commands.
///
/// Emits a `boot_status("persona-home", Degraded, "migrated <name>:
/// legacy → citizens/")` line so the operator sees the action
/// happened. Per [[reliable-startup-substrate-refuses-to-lie]]: the
/// substrate took action AND told the operator; that's the
/// substrate-purist alternative to the prior "refuse with mv
/// command in error message" shape.
///
/// [`LegacyMigrationConflict`]: PersonaAircRuntimeError::LegacyMigrationConflict
async fn migrate_legacy_persona_home(
    legacy: &std::path::Path,
    new: &std::path::Path,
    agent_name: &str,
) -> Result<(), PersonaAircRuntimeError> {
    use crate::runtime::boot_status::{boot_status, BootStatusKind};

    // Destination check. `new` is `<root>/citizens/personas/<name>/airc/`;
    // a previous partial migration could have populated it. We only
    // proceed when the destination is absent OR exists-but-empty.
    let dest_exists = tokio::fs::try_exists(new).await.unwrap_or(false);
    if dest_exists {
        let mut entries = match tokio::fs::read_dir(new).await {
            Ok(rd) => rd,
            Err(source) => {
                return Err(PersonaAircRuntimeError::LegacyMigrationIoError {
                    agent_name: agent_name.to_string(),
                    legacy: legacy.to_path_buf(),
                    new: new.to_path_buf(),
                    source,
                });
            }
        };
        let has_content = entries
            .next_entry()
            .await
            .map(|opt| opt.is_some())
            .unwrap_or(true);
        if has_content {
            return Err(PersonaAircRuntimeError::LegacyMigrationConflict {
                agent_name: agent_name.to_string(),
                legacy: legacy.to_path_buf(),
                new: new.to_path_buf(),
            });
        }
        // Empty destination: remove it so `rename` doesn't trip on
        // "target exists" on platforms that require absent target.
        tokio::fs::remove_dir(new).await.map_err(|source| {
            PersonaAircRuntimeError::LegacyMigrationIoError {
                agent_name: agent_name.to_string(),
                legacy: legacy.to_path_buf(),
                new: new.to_path_buf(),
                source,
            }
        })?;
    }

    // Ensure the destination's parent exists. `new` here is the
    // `airc/` leaf — its parent is `<root>/citizens/personas/<name>/`,
    // and that parent's parent is `<root>/citizens/personas/`. The
    // standard `create_dir_all` walks every missing component.
    if let Some(parent) = new.parent() {
        tokio::fs::create_dir_all(parent).await.map_err(|source| {
            PersonaAircRuntimeError::LegacyMigrationIoError {
                agent_name: agent_name.to_string(),
                legacy: legacy.to_path_buf(),
                new: new.to_path_buf(),
                source,
            }
        })?;
    }

    tokio::fs::rename(legacy, new).await.map_err(|source| {
        PersonaAircRuntimeError::LegacyMigrationIoError {
            agent_name: agent_name.to_string(),
            legacy: legacy.to_path_buf(),
            new: new.to_path_buf(),
            source,
        }
    })?;

    // Best-effort cleanup of the legacy parent directories left
    // empty after the rename (the persona's old `<root>/personas/<name>/`
    // wrapper, then `<root>/personas/` itself if it's empty). Both
    // calls degrade gracefully on "directory not empty" because
    // remove_dir refuses non-empty dirs — perfect for the "did
    // anyone else have content here?" check without a stat race.
    if let Some(old_persona_parent) = legacy.parent() {
        let _ = tokio::fs::remove_dir(old_persona_parent).await;
        if let Some(old_kind_dir) = old_persona_parent.parent() {
            let _ = tokio::fs::remove_dir(old_kind_dir).await;
        }
    }

    boot_status(
        "persona-home",
        BootStatusKind::Degraded,
        &format!(
            "migrated {agent_name}: {legacy} → {new}",
            legacy = legacy.display(),
            new = new.display(),
        ),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[tokio::test]
    async fn bootstrap_resolves_home_under_personas_directory() {
        // This unit test verifies path layout only — actual daemon
        // attach lives in an integration test that needs a running
        // airc daemon. The layout assertion catches the
        // [[personas-are-citizens-airc-is-identity-provider]] memory's
        // "do NOT nest persona homes inside another scope's airc home"
        // rule at compile-ish time.
        let temp = TempDir::new().expect("tempdir");
        let expected_home = crate::context::citizen_home_path(
            temp.path(),
            crate::identity::IdentityKind::Persona,
            None,
            "helper-ai-test",
        );
        // Slice 4 of #142: symmetric layout under
        // citizens/personas/<name>/airc/.
        assert_eq!(
            expected_home,
            temp.path()
                .join("citizens")
                .join("personas")
                .join("helper-ai-test")
                .join("airc")
        );
        assert!(!expected_home.exists());
    }

    /// Card e9f50a36 (slice A2): when a persona's pre-Slice-4 home
    /// (`<root>/personas/<name>/airc/`) exists on disk, the
    /// substrate auto-migrates it to the post-Slice-4 layout
    /// instead of refusing to boot. This test verifies the
    /// migration result on disk: legacy gone, new exists, the
    /// persona's seed file moved intact.
    ///
    /// Per [[reliable-startup-substrate-refuses-to-lie]]: the
    /// substrate took action AND told the operator (boot_status
    /// `persona-home: ⚠ migrated ...` line). The operator's manual
    /// `mv` step is no longer load-bearing for a 1:1-unambiguous
    /// schema migration.
    #[tokio::test]
    async fn migrate_moves_legacy_persona_home_into_citizens_layout() {
        let tmp = TempDir::new().expect("tempdir");
        let root = tmp.path();

        let legacy = root.join("personas").join("maya").join("airc");
        let new = root
            .join("citizens")
            .join("personas")
            .join("maya")
            .join("airc");
        tokio::fs::create_dir_all(&legacy)
            .await
            .expect("seed legacy persona path");
        // Drop a sentinel file so we can assert the rename moved
        // content, not just created the destination.
        tokio::fs::write(legacy.join("identity.key"), b"test-key-bytes")
            .await
            .expect("seed legacy identity.key");

        migrate_legacy_persona_home(&legacy, &new, "maya")
            .await
            .expect("auto-migration must succeed for the standard case");

        assert!(!legacy.exists(), "legacy path must be gone after migration");
        assert!(new.exists(), "new citizens/ path must exist");
        let migrated_key = tokio::fs::read(new.join("identity.key"))
            .await
            .expect("seed file must have moved with the rename");
        assert_eq!(
            migrated_key, b"test-key-bytes",
            "seed file content must be preserved across migration"
        );
    }

    /// Safety branch: when BOTH the legacy AND the new paths have
    /// content (operator did a partial manual migration, or someone
    /// restored a backup into citizens/ alongside the old layout),
    /// the substrate refuses to clobber and surfaces a typed
    /// `LegacyMigrationConflict` with the exact recovery commands.
    ///
    /// Per [[no-fallbacks-ever]]: auto-migration is only safe when
    /// there's exactly one source of truth. Two non-empty paths is
    /// the genuinely-ambiguous case where human judgment is the only
    /// correct resolution.
    #[tokio::test]
    async fn migrate_refuses_when_both_paths_have_content() {
        let tmp = TempDir::new().expect("tempdir");
        let root = tmp.path();

        let legacy = root.join("personas").join("maya").join("airc");
        let new = root
            .join("citizens")
            .join("personas")
            .join("maya")
            .join("airc");
        tokio::fs::create_dir_all(&legacy)
            .await
            .expect("seed legacy");
        tokio::fs::write(legacy.join("identity.key"), b"legacy-key")
            .await
            .expect("seed legacy identity");
        tokio::fs::create_dir_all(&new).await.expect("seed new");
        tokio::fs::write(new.join("identity.key"), b"new-key")
            .await
            .expect("seed new identity");

        let result = migrate_legacy_persona_home(&legacy, &new, "maya").await;

        match result {
            Err(PersonaAircRuntimeError::LegacyMigrationConflict {
                agent_name,
                legacy: returned_legacy,
                new: returned_new,
            }) => {
                assert_eq!(agent_name, "maya");
                assert_eq!(returned_legacy, legacy);
                assert_eq!(returned_new, new);
            }
            Err(other) => panic!(
                "expected LegacyMigrationConflict, got: {other} — \
                 the safety branch is broken"
            ),
            Ok(_) => panic!(
                "expected LegacyMigrationConflict, migration succeeded — \
                 substrate would have clobbered legitimate state in the new path"
            ),
        }

        // Both source files must still be intact (no clobber).
        let legacy_content = tokio::fs::read(legacy.join("identity.key"))
            .await
            .expect("legacy must be untouched");
        assert_eq!(legacy_content, b"legacy-key");
        let new_content = tokio::fs::read(new.join("identity.key"))
            .await
            .expect("new must be untouched");
        assert_eq!(new_content, b"new-key");
    }

    /// Idempotency branch: when the new path exists but is empty
    /// (operator created the parent skeleton then ran the substrate
    /// before any state landed in citizens/), the substrate removes
    /// the empty placeholder and proceeds with the rename. This
    /// avoids surprising the operator with a conflict on a path
    /// they never populated.
    #[tokio::test]
    async fn migrate_proceeds_when_new_path_exists_but_is_empty() {
        let tmp = TempDir::new().expect("tempdir");
        let root = tmp.path();

        let legacy = root.join("personas").join("maya").join("airc");
        let new = root
            .join("citizens")
            .join("personas")
            .join("maya")
            .join("airc");
        tokio::fs::create_dir_all(&legacy).await.expect("seed legacy");
        tokio::fs::write(legacy.join("identity.key"), b"keep-me")
            .await
            .expect("seed legacy identity");
        tokio::fs::create_dir_all(&new).await.expect("seed empty new");

        migrate_legacy_persona_home(&legacy, &new, "maya")
            .await
            .expect("empty destination must allow migration to proceed");

        assert!(!legacy.exists(), "legacy must be gone");
        let key = tokio::fs::read(new.join("identity.key"))
            .await
            .expect("legacy content must have landed in new");
        assert_eq!(key, b"keep-me");
    }
}
