//! Per-persona airc runtime — the substrate piece that makes a
//! persona a first-class airc citizen.
//!
//! ### Doctrine
//!
//! Per memory `personas-are-citizens-airc-is-identity-provider`: a
//! persona is NOT a continuum-internal queue row fronted by a
//! broker. It's a citizen on the substrate — same kind as Joel-at-
//! a-terminal, Claude-in-a-tab, OpenClaw, Hermes. Each persona
//! gets:
//!
//! - Its own `$AIRC_HOME` under `~/.continuum/personas/<name>/airc/`
//!   — NOT inside any other scope's airc home, to keep the citizen
//!   a peer rather than a sub-citizen of continuum's own scope.
//! - Its own Ed25519 identity, generated by airc-lib's
//!   `LocalIdentity::load_or_generate_as` (transitively, via
//!   `Airc::attach_as`). Continuum does not mint, store, or sign
//!   with persona keys — that's airc's job entirely.
//! - Its own `airc_lib::Airc` handle obtained via
//!   `Airc::attach_as(home, agent_name, socket)` — daemon-connected
//!   so the persona can `subscribe()` to live rooms and `say()` /
//!   `publish()` under its own peer_id.
//! - Membership in the same continuum room Joel publishes into
//!   (per "I expect your general room and theirs to be the same
//!   room").
//!
//! ### What this module IS
//!
//! - A lifecycle handle holding the persona's `Arc<airc_lib::Airc>`
//!   and the join handle of its inbound pump task.
//! - A `bootstrap` constructor that does the airc-side identity
//!   ceremony + room-join + inbound subscription, all through
//!   airc-lib's public surface (no shelling out to `airc init`).
//! - A `publish_text` helper delegating to `Airc::say` — the same
//!   shape `airc msg` uses, no continuum-side wrapping.
//!
//! ### What this module is NOT
//!
//! Per the anti-patterns the design workflow named for refusal:
//!
//! - NOT a "ChatService::sendAs(persona_id, text)" — there's no
//!   public method that takes a persona_id and routes internally.
//!   Whoever calls `publish_text` already HAS the persona's
//!   runtime handle. The "persona-id keyed dispatch" lives in the
//!   registry (one level up), not in this struct.
//! - NOT a translation layer from `TranscriptEvent` to a continuum-
//!   internal `ChatMessage` shape. Events surface in their native
//!   airc form for downstream consumers to dispatch on.
//! - NOT a holder of the persona's secret key. The keypair lives
//!   inside the `Airc` handle (delegating to airc-identity) — this
//!   struct only holds the Arc.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use airc_core::{EventId, RoomId};
use airc_lib::{Airc, AircError};
use tokio::task::JoinHandle;
use tracing::{info, warn};
use uuid::Uuid;

/// Errors that can occur during persona airc-runtime bootstrap.
///
/// Each variant carries enough context for the operator to act —
/// pinning identity manually, fixing the daemon socket, etc. — per
/// the constitutional-design memory's "every error has a path
/// forward" doctrine.
#[derive(Debug, thiserror::Error)]
pub enum PersonaAircRuntimeError {
    #[error(
        "legacy persona home detected at {legacy:?} — Slice 4 of #142 moved \
         personas under `citizens/personas/<name>/airc/`. To migrate this \
         persona's identity AND keep its peer_id stable, run:\n\
         \n  mkdir -p {new_parent:?} && mv {legacy:?} {new:?}\n\n\
         Then re-run. Per [[no-fallbacks-ever]] the substrate refuses to \
         silently use the legacy path."
    )]
    LegacyLayoutDetected {
        legacy: PathBuf,
        new: PathBuf,
        new_parent: PathBuf,
    },
    #[error("failed to create persona airc home {0}: {1}")]
    HomeCreate(PathBuf, std::io::Error),
    #[error("airc-lib attach_as failed for persona {agent_name:?} at {home:?}: {source}")]
    Attach {
        agent_name: String,
        home: PathBuf,
        #[source]
        source: AircError,
    },
    #[error("failed to join room {room_id} as persona {agent_name:?}: {source}")]
    Join {
        agent_name: String,
        room_id: Uuid,
        #[source]
        source: AircError,
    },
}

/// One persona's live airc connection.
///
/// Holds the persona's `Arc<Airc>` (its grid presence — identity +
/// daemon connection + room membership) and the inbound pump task
/// handle. Drop this struct to shut the persona's airc presence
/// down cleanly.
pub struct PersonaAircRuntime {
    persona_id: Uuid,
    agent_name: String,
    home: PathBuf,
    airc: Arc<Airc>,
    default_room: RoomId,
    inbound_handle: Option<JoinHandle<()>>,
    /// Where this citizen's identity came from — resumed from disk
    /// vs freshly minted. Carried for the lifetime of the runtime so
    /// telemetry surfaces (list/get IPC, future status panels) can
    /// distinguish without re-deriving from disk. Per
    /// [[substrate-is-a-good-citizen-on-the-host]]: observability
    /// honest.
    source: crate::persona::identity_provider::PersonaIdentitySource,
}

impl PersonaAircRuntime {
    /// Bootstrap a persona's airc presence.
    ///
    /// Steps:
    ///
    /// 1. Resolve the persona's home under `continuum_root/personas/
    ///    <agent_name>/airc/` and create it if absent.
    /// 2. Call `Airc::attach_as(home, agent_name, daemon_socket)`.
    ///    Internally this runs the airc-lib identity ceremony
    ///    (generate or load Ed25519 keypair, write `identity.key`,
    ///    record the local_identity row) and attaches a daemon
    ///    client for live publish + subscribe. No shelling out.
    /// 3. Resolve the room by its UUID via `default_room.as_uuid()`
    ///    and call `Airc::join(...)`. This makes the persona appear
    ///    on `airc peers` as an enrolled participant of the room.
    /// 4. (Inbound pump is wired in a follow-up; this bootstrap
    ///    returns the handle ready for that wiring.)
    ///
    /// Returns the runtime handle. On any failure surfaces a typed
    /// `PersonaAircRuntimeError` with an actionable remedy in the
    /// message — never a silent fallback.
    pub async fn bootstrap(
        persona_id: Uuid,
        agent_name: impl Into<String>,
        continuum_root: &Path,
        daemon_socket: PathBuf,
        default_room: RoomId,
        default_room_name: Option<String>,
        source: crate::persona::identity_provider::PersonaIdentitySource,
    ) -> Result<Self, PersonaAircRuntimeError> {
        let agent_name = agent_name.into();
        // Slice 4 of #142: symmetric citizens/<kind>/<label>/airc/
        // layout. Use the shared helper so every actor kind shares
        // the same path schema.
        let home = crate::context::citizen_home_path(
            continuum_root,
            crate::identity::IdentityKind::Persona,
            None,
            &agent_name,
        );

        // Migration: refuse to use the pre-Slice-4 layout. Hard-error
        // with the exact `mv` command per [[no-fallbacks-ever]].
        if let Some(legacy) = crate::context::legacy_home_path(
            continuum_root,
            crate::identity::IdentityKind::Persona,
            &agent_name,
        ) {
            if tokio::fs::try_exists(&legacy).await.unwrap_or(false) {
                let new_parent = home
                    .parent()
                    .map(|p| p.to_path_buf())
                    .unwrap_or_else(|| home.clone());
                return Err(PersonaAircRuntimeError::LegacyLayoutDetected {
                    legacy,
                    new: home.clone(),
                    new_parent,
                });
            }
        }

        tokio::fs::create_dir_all(&home)
            .await
            .map_err(|e| PersonaAircRuntimeError::HomeCreate(home.clone(), e))?;

        let airc = Airc::attach_as(home.clone(), agent_name.clone(), daemon_socket)
            .await
            .map_err(|source| PersonaAircRuntimeError::Attach {
                agent_name: agent_name.clone(),
                home: home.clone(),
                source,
            })?;

        // ── Slice 1B of #142: collapse persona_id := peer_id ─────────────
        //
        // Per [[persona-identity-derives-from-source-id]] +
        // [[airc-is-the-session-not-a-feature]]: the substrate has ONE
        // unique identifier per actor — the airc peer_id (Ed25519
        // keypair Uuid). The continuum-side `persona_id` originally
        // minted via `Uuid::new_v4()` pre-bootstrap is the historical
        // artifact; airc-lib is the source of cryptographic truth.
        //
        // Post-bootstrap, the runtime stores `persona_id` as the
        // peer_id. Callers using `runtime.persona_id()` as a registry
        // key are then safe to also reach for `ctx.identity().id`
        // (= peer_id) from the Context trait without divergence.
        //
        // The input `persona_id` parameter is retained for API
        // continuity (callers shouldn't break) but its value is
        // logged-then-discarded. Divergence is at `debug!` level —
        // for fresh mints the divergence is the NORMAL case
        // (`ResumeOrMintProvider::mint_fresh_intent` allocates
        // `Uuid::new_v4()` before the keypair is generated, so the
        // two Uuids are statistically guaranteed to differ for every
        // fresh persona). Logging it at `warn!` would spam operators
        // at every boot. A future API cleanup drops the parameter
        // entirely and removes this branch.
        let peer_id_uuid = airc.peer_id().as_uuid();
        if persona_id != peer_id_uuid {
            tracing::debug!(
                input_persona_id = %persona_id,
                peer_id = %peer_id_uuid,
                agent_name = %agent_name,
                "PersonaAircRuntime::bootstrap: persona_id parameter ignored — \
                 runtime collapses persona_id := peer_id per Slice 1B of #142. \
                 Expected for fresh mints; a future API cleanup drops the parameter."
            );
        }
        let persona_id = peer_id_uuid;

        info!(
            persona_id = %persona_id,
            agent_name = %agent_name,
            peer_id = %airc.peer_id(),
            client_id = %airc.client_id(),
            home = %home.display(),
            "PersonaAircRuntime bootstrap: identity ready (persona_id == peer_id post-collapse)"
        );

        // Join the default room. From the daemon's perspective the
        // persona is now an enrolled participant — `airc peers`
        // from another scope MUST list this peer_id.
        //
        // CRITICAL: `Airc::join(name)` calls `ChannelName::new(name)`
        // which DERIVES a channel UUID from the name. If we pass the
        // UUID-as-string of the operator's channel, that string gets
        // interpreted as a name and produces a DIFFERENT channel.
        // The persona then sits in the derived channel while the
        // operator publishes into the canonical one — they never
        // see each other. Joining by NAME (e.g. "continuum") lands
        // both in the same channel. PR #1511 integration test caught
        // this; demo binary in slice 11 reshaped via `from_attached`
        // explicitly to work around the same hazard.
        let join_target = match default_room_name.as_deref() {
            Some(name) => name.to_string(),
            None => {
                tracing::warn!(
                    persona_id = %persona_id,
                    agent_name = %agent_name,
                    room_id = %default_room.as_uuid(),
                    "PersonaAircRuntime bootstrap: no default_room_name supplied — \
                     falling back to joining by UUID-as-string, which derives a NEW \
                     channel. Persona will likely land in the wrong room. Resolve: \
                     ensure AircModule discovers default_room_name (via `airc room` \
                     output's `room: <name>` line) and threads it through here.",
                );
                default_room.as_uuid().to_string()
            }
        };
        let room = airc
            .join(&join_target)
            .await
            .map_err(|source| PersonaAircRuntimeError::Join {
                agent_name: agent_name.clone(),
                room_id: default_room.as_uuid(),
                source,
            })?;

        info!(
            persona_id = %persona_id,
            agent_name = %agent_name,
            peer_id = %airc.peer_id(),
            joined_room = %room.channel.as_uuid(),
            room_name = %room.name,
            "PersonaAircRuntime bootstrap: joined room"
        );

        Ok(Self {
            persona_id,
            agent_name,
            home,
            airc: Arc::new(airc),
            default_room,
            inbound_handle: None,
            source,
        })
    }

    /// Wrap an already-attached + already-joined `Arc<Airc>` into a
    /// `PersonaAircRuntime`. Skips the `bootstrap` join step —
    /// useful for the demo binary that joins by NAME (the canonical
    /// path) instead of by uuid-as-string (the bootstrap path's
    /// current shape — see #133-followup note on `bootstrap`).
    ///
    /// The caller is responsible for: (1) calling `attach_as` /
    /// `join` BEFORE handing the Arc in, (2) supplying the
    /// `RoomId` matching the room they joined.
    pub fn from_attached(
        persona_id: Uuid,
        agent_name: impl Into<String>,
        home: PathBuf,
        airc: Arc<Airc>,
        default_room: RoomId,
        source: crate::persona::identity_provider::PersonaIdentitySource,
    ) -> Self {
        // Slice 1B of #142: collapse persona_id := peer_id. Same
        // rationale as in `bootstrap` above. The input parameter is
        // retained for API continuity but its value is reseated to
        // the airc-lib peer_id (cryptographic ground truth).
        let peer_id_uuid = airc.peer_id().as_uuid();
        let agent_name = agent_name.into();
        if persona_id != peer_id_uuid {
            // Expected for fresh mints — see equivalent doc in
            // `bootstrap` above. `debug!` not `warn!` to avoid log
            // spam at every boot.
            tracing::debug!(
                input_persona_id = %persona_id,
                peer_id = %peer_id_uuid,
                agent_name = %agent_name,
                "PersonaAircRuntime::from_attached: persona_id parameter \
                 ignored — runtime collapses persona_id := peer_id per Slice \
                 1B of #142."
            );
        }
        Self {
            persona_id: peer_id_uuid,
            agent_name,
            home,
            airc,
            default_room,
            inbound_handle: None,
            source,
        }
    }

    /// The persona's stable continuum identifier.
    pub fn persona_id(&self) -> Uuid {
        self.persona_id
    }

    /// Where this citizen's identity came from — resumed vs minted.
    pub fn source(&self) -> crate::persona::identity_provider::PersonaIdentitySource {
        self.source
    }

    /// The persona's airc agent_name (matches what shows up in
    /// `airc peers` / `airc whois`).
    pub fn agent_name(&self) -> &str {
        &self.agent_name
    }

    /// The persona's airc home directory.
    pub fn home(&self) -> &Path {
        &self.home
    }

    /// The persona's `Arc<Airc>` handle. Cognition + outbound paths
    /// hold this Arc to reach the persona's grid presence — for
    /// `say`, `publish`, `subscribe`, `peer_id`, etc. Direct access
    /// is intentional: there's no continuum-side wrapper between a
    /// persona and its own airc handle.
    pub fn airc(&self) -> &Arc<Airc> {
        &self.airc
    }

    /// Convenience: publish a plain text message in the persona's
    /// default room, signed under the persona's identity. Equivalent
    /// to `self.airc().say(text)`. Exists so the common case reads
    /// cleanly at the call site.
    pub async fn say(&self, text: &str) -> Result<EventId, AircError> {
        self.airc.say(text).await
    }

    /// The default room the persona joined at bootstrap.
    pub fn default_room(&self) -> RoomId {
        self.default_room
    }
}

// AircCitizen + AircTranscriptReader impls — substrate's universal
// airc-handle interface, satisfied by the production runtime. Per
// [[personas-are-citizens-airc-is-identity-provider]] the trait IS the
// citizen surface; the concrete runtime is one impl among future
// peers (human, web, browser). See `persona::airc_citizen` for the
// trait definition + rationale.
#[async_trait::async_trait]
impl crate::persona::airc_source::AircTranscriptReader for PersonaAircRuntime {
    async fn page_recent(
        &self,
        limit: usize,
    ) -> Result<Vec<airc_lib::TranscriptEvent>, AircError> {
        self.airc.page_recent(limit).await
    }
}

#[async_trait::async_trait]
impl crate::persona::airc_citizen::AircCitizen for PersonaAircRuntime {
    fn peer_id(&self) -> Uuid {
        self.airc.peer_id().as_uuid()
    }

    async fn subscribe(&self) -> Result<airc_lib::EventStream, AircError> {
        self.airc.subscribe().await
    }

    async fn say(&self, text: &str) -> Result<EventId, AircError> {
        self.airc.say(text).await
    }
}

impl Drop for PersonaAircRuntime {
    fn drop(&mut self) {
        if let Some(handle) = self.inbound_handle.take() {
            handle.abort();
        }
        // Arc<Airc> drops alongside the runtime; airc-lib handles
        // its own cleanup (daemon connection close, identity state
        // flush).
        warn!(
            persona_id = %self.persona_id,
            agent_name = %self.agent_name,
            "PersonaAircRuntime dropped — persona left the grid"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[tokio::test]
    async fn bootstrap_resolves_home_under_personas_directory() {
        // This unit test verifies path layout only — actual daemon
        // attach lives in an integration test that needs a running
        // airc daemon. The layout assertion catches the
        // [[personas-are-citizens-airc-is-identity-provider]] memory's
        // "do NOT nest persona homes inside another scope's airc home"
        // rule at compile-ish time.
        let temp = TempDir::new().expect("tempdir");
        let expected_home = crate::context::citizen_home_path(
            temp.path(),
            crate::identity::IdentityKind::Persona,
            None,
            "helper-ai-test",
        );
        // Slice 4 of #142: symmetric layout under
        // citizens/personas/<name>/airc/.
        assert_eq!(
            expected_home,
            temp.path()
                .join("citizens")
                .join("personas")
                .join("helper-ai-test")
                .join("airc")
        );
        assert!(!expected_home.exists());
    }
}
