// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The *representation* of a renderable asset. The scene graph is neutral over
 * this: a backend picks a loader by kind. `None` on an [`AssetRef`] means
 * "infer from the source extension". Gaussian splats and generated assets are
 * named here so the model anticipates them without a schema change.
 */
export type AssetKind = "Mesh" | "Humanoid" | "GaussianSplat" | "Generated";
