// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A linear RGBA color. POD; converts into Bevy `Color`. Canonicalized to
 * linear space so the round-trip through `Color` is lossless regardless of how
 * the source color was authored (hsl/srgb/etc).
 */
export type ColorDesc = { r: number, g: number, b: number, a: number, };
