// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";

/**
 * The room/backdrop environment — a glTF loaded as an ECS `RoomConfig` child
 * of the scene root (mirrors the runtime `RoomConfig`).
 */
export type EnvironmentPayload = { scene_id: string, asset: AssetRef, };
