// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvatarPayload } from "./AvatarPayload";
import type { CameraPayload } from "./CameraPayload";
import type { EnvironmentPayload } from "./EnvironmentPayload";
import type { LightDesc } from "./LightDesc";
import type { PropPayload } from "./PropPayload";

/**
 * What a [`SceneNode`] *is*. Adding a new renderable kind = a new variant here
 * + a `SceneObject` impl + a loader; the tree, transforms, physics, and
 * hierarchy are unchanged. `Group` is the transform-only inheritance node.
 */
export type NodePayload = "Group" | { "Avatar": AvatarPayload } | { "Prop": PropPayload } | { "Light": LightDesc } | { "Camera": CameraPayload } | { "Environment": EnvironmentPayload };
