// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `tool/usage` — no inputs; the report is the whole tally since the
 * last deploy.
 */
export type ToolUsageParams = Record<symbol, never>;
