// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `tool/conformance` — an optional case-insensitive substring to
 * filter violations by tool name (so "why can't I use `data/*`?" is answerable).
 * Empty ⇒ the whole surface.
 */
export type ToolConformanceParams = { 
/**
 * Optional substring filter on the offending tool name (case-insensitive).
 */
filter?: string, };
