// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What [`super::FineTuningAdapter::create_job`] returns. Acts as a
 * correlation token across the substrate side (`local_id`) and the
 * provider side (`provider_job_id`).
 */
export type JobHandle = { 
/**
 * Which adapter created this — used by the registry to look the
 * adapter back up on `poll` / `cancel`.
 */
providerId: string, 
/**
 * Provider-side identifier (OpenAI's `ftjob-abc123`, Mistral's
 * `job-xyz`, etc). For [`super::FineTuningAdapter`] impls that
 * run in-process (local Candle), this echoes `local_id` as a
 * string.
 */
providerJobId: string, 
/**
 * Substrate-side correlation id. Stable; safe to persist; used
 * by telemetry / alloy lineage.
 */
localId: string, };
