// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-job observed metrics. Substrate-side telemetry +
 * reputation signal input
 * ([[forge-alloy-secures-commodity-zero-trust-plus-reputation]]).
 */
export type JobMetrics = { trainedTokens: number, 
/**
 * Validation loss at the end of training. Lower is better; the
 * substrate uses this to decide if the layer is worth shipping
 * into the mesh.
 */
finalLoss?: number, finalValidationLoss?: number, wallClockMs: number, 
/**
 * Trillion-token-cost USD reported by the provider, if it tells
 * us. Helps the substrate's economic dispatcher
 * ([[forge-alloy-secures-commodity-zero-trust-plus-reputation]])
 * pick the cheapest viable provider per request.
 */
costUsd?: number, 
/**
 * The transformer blocks this adapter actually trained, as the engine reported it after
 * the run (not what was asked: an engine without `top_layers` adapts every block). `None`
 * = the provider does not say. The promotion gate compares a reduced-depth gene knowing it.
 */
layersAdapted?: number, };
