// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LoRA-specific knobs. Same field set every cloud provider exposes
 * (rank + alpha + dropout + target_modules); local Candle adds none
 * beyond these.
 *
 * `PartialEq` (not `Eq`) because of the `dropout: f32` field. The
 * training-trigger bucket-coherence check compares two
 * `LoRAHyperparams` via `!=`, which requires the trait.
 */
export type LoRAHyperparams = { 
/**
 * LoRA rank — the bottleneck dimension. Common: 4, 8, 16, 32, 64.
 * Higher rank = more capacity but more weights to train + store.
 */
rank: number, 
/**
 * LoRA alpha — the scaling factor applied during merge
 * (`W' = W + (alpha/rank) * B @ A`). Common heuristic: `alpha =
 * rank * 2`. Setting `alpha == rank` is a common mistake the
 * `genome/job-create` validator warns on.
 */
alpha: number, 
/**
 * Dropout on the LoRA branch during training. Common: 0.0, 0.05,
 * 0.1. Defaults to 0.0 for most providers.
 */
dropout: number, 
/**
 * Which transformer projection layers to inject LoRA into.
 * Empty `Vec` lets the adapter pick provider defaults
 * (usually `q_proj` + `v_proj`).
 */
targetModules: Array<string>, 
/**
 * Adapt only the last `top_layers` transformer blocks; `None` adapts every block. The
 * backward pass stops at the lowest adapted block, so the training graph's memory falls
 * roughly linearly with this (fork #27: Qwen2.5-1.5B at window 512, 2576 MiB for all 28
 * blocks, 1316 MiB for the last 7). A full-depth 27B run did not fit beside its serving
 * context (41.5 GB at window 1536), so a resident dream chooses a depth. Only the
 * in-engine trainer reads it; other adapters ignore it and train every block.
 */
topLayers?: number, };
