// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LivedCall } from "./LivedCall";

/**
 * One training pair — the unit of evidence.
 *
 * `metadata` is `serde_json::Value` because it's audit-trail
 * pass-through (which engram this came from, what session, what
 * noteworthy score). The substrate doesn't dispatch on it; it
 * flows into telemetry + alloy provenance.
 */
export type TrainingExample = { prompt: string, completion: string, metadata?: Record<string, unknown> | undefined, 
/**
 * The call she actually lived, when this example came from one (card ad107e18):
 * the exact request the engine was served and her exact response, reasoning and
 * tool calls included. A trainer that renders it trains on what she saw and did;
 * `prompt`/`completion` stay as its flat projection for trainers that take text.
 */
lived?: LivedCall, };
