// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pressure tier — drives the broker's response.
 *
 * Serialized as lowercase (`"normal" | "warning" | "high" | "critical"`)
 * to match the existing `label()` impl + every other tier string the
 * system emits in logs and IPC. ts-rs export keeps the TS union honest
 * — operators can pattern-match without stringly-typed comparisons.
 */
export type PressureTier = "normal" | "warning" | "high" | "critical";
