// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cross-tier entry snapshot for diagnostics, status output, and future
 * scheduler decisions. Pool-specific values stay inside the pool; this is
 * the uniform RTOS-facing shape.
 */
export type ResourcePoolEntry = { key: string, sizeBytes: bigint, pinnedCount: number, loadedAt: bigint, lastAccessAt: bigint, accessCount: bigint, };
