// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `ai/inference/models`: the loadable catalog + which are serving.
 */
export type ModelsResult = { 
/**
 * Loadable on-disk model ids (each is what `serving/pin` takes) — from the
 * model registry's catalog, which OWNS "what can this host run".
 */
available: Array<string>, 
/**
 * The ids serving right now. The engine is single-resident, so this is the
 * active model (0 or 1), sourced from the canonical serving snapshot.
 */
serving: Array<string>, 
/**
 * The single active (answering) model, if any.
 */
active?: string, };
