// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai/inference/models` has no params — it lists what the gateway can load.
 */
export type ModelsParams = Record<symbol, never>;
