// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `ai/inference/load` / `ai/inference/unload` — the model id.
 */
export type ModelRef = { 
/**
 * The model identifier to act on — the SAME id `ai/inference/models` lists
 * and a persona generates with (a hub id like
 * `continuum-ai/qwen3.5-4b-code-forged-GGUF`, not a filesystem path).
 */
model: string, };
