// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeakerType } from "./SpeakerType";

export type UtteranceEvent = { session_id: string, speaker_id: string, speaker_name: string, speaker_type: SpeakerType, transcript: string, confidence: number, timestamp: number, };
