// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tool call to correct: its (possibly mangled) name and string parameters.
 */
export type ToolCorrectParams = { 
/**
 * The model-produced tool name (may be an alias or mis-namespaced form).
 */
tool_name: string, 
/**
 * The parameters as the model emitted them (string values). Corrected param
 * keys (e.g. `query -> pattern`) are reported in the result.
 */
parameters: { [key in string]: string }, };
