// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `search/params`.
 */
export type SearchParamsParams = { 
/**
 * Which algorithm's parameters to report (bow, bm25, cosine).
 */
algorithm: string, };
