// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolveOutcome = { success: boolean, dispatchId: string, 
/**
 * `retryable` (the next tick re-creates the job) or `dispatched` (the named job
 * was adopted). Absent on refusal.
 */
resolution?: string, 
/**
 * Examples the intent carries, back on their way to a job.
 */
examples?: number, jobId?: string, errorKind?: string, error?: string, };
