#!/usr/bin/env bash
#
# Lane F PR-1 — TS Cognition Deletion Ratchet (local script)
#
# Mechanical gate that prevents the persona-cognition TypeScript layer from
# growing while the Rust runtime takes over. See
# docs/planning/ALPHA-GAP-ANALYSIS.md §"Lane F: TS Cognition Deletion
# Ratchet" for the design.
#
# The ratchet fails the build if EITHER:
#   1. Total TS LOC under a watched cognition directory exceeds its baseline.
#   2. A new .ts file appears under a watched cognition directory and is
#      neither in the baseline file-set nor in the explicit allowlist.
#
# Allowed kinds of TS (per Lane F spec): ORM nouns, generated schema, UI
# types, thin transport shims. We do not classify by content (fragile) —
# we classify by path via the allowlist file.
#
# Usage:
#   scripts/ratchet/persona-ts-ratchet.sh check        # CI mode (default)
#   scripts/ratchet/persona-ts-ratchet.sh refresh      # regenerate baseline (deletion landed)
#   scripts/ratchet/persona-ts-ratchet.sh --root DIR check    # override repo root
#
# Exit codes:
#   0 — baseline holds (LOC <= baseline AND no unexpected new files)
#   1 — ratchet violated; build must fail
#   2 — usage error / missing baseline
#
# Refresh is INTENTIONAL: after legitimate TS deletion lands, run `refresh`
# to tighten the ratchet to the new (lower) line counts. The ratchet only
# moves in the deletion direction — that's why it's called a ratchet.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ROOT="$DEFAULT_ROOT"
MODE="check"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --root)
            ROOT="$2"
            shift 2
            ;;
        check|refresh)
            MODE="$1"
            shift
            ;;
        -h|--help)
            sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "ratchet: unknown argument '$1'" >&2
            echo "usage: persona-ts-ratchet.sh [--root DIR] [check|refresh]" >&2
            exit 2
            ;;
    esac
done

BASELINE_FILE="${PERSONA_RATCHET_BASELINE:-$SCRIPT_DIR/persona-ts-baseline.txt}"
ALLOWLIST_FILE="${PERSONA_RATCHET_ALLOWLIST:-$SCRIPT_DIR/persona-ts-allowlist.txt}"

# Watched cognition directories — relative to repo root. The Lane F gate
# applies to all of these. Order is significant for stable baseline output.
WATCHED_DIRS=(
    "src/system/user/server/modules/cognition"
    "src/system/user/server/modules/cognitive"
    "src/system/user/server/modules/consciousness"
    "src/system/user/server/modules/being"
    "src/system/user/server/modules/central-nervous-system"
    "src/system/user/server/attention"
    "src/system/ai/server"
)

# Returns LOC count (non-zero) for all .ts files under $1, excluding .d.ts
# (declarations are not cognition). Returns 0 if dir is missing or empty.
dir_ts_loc() {
    local dir="$1"
    if [[ ! -d "$ROOT/$dir" ]]; then
        echo "0"
        return
    fi
    find "$ROOT/$dir" -name '*.ts' -not -name '*.d.ts' -print0 2>/dev/null \
        | xargs -0 wc -l 2>/dev/null \
        | tail -1 \
        | awk '{print ($1 == "" ? 0 : $1)}'
}

# Emits sorted list of relative .ts paths (excluding .d.ts) under $1.
dir_ts_files() {
    local dir="$1"
    if [[ ! -d "$ROOT/$dir" ]]; then
        return
    fi
    find "$ROOT/$dir" -name '*.ts' -not -name '*.d.ts' -type f 2>/dev/null \
        | sed "s|^$ROOT/||" \
        | sort
}

# Read baseline LOC for $1; emits empty string if not in baseline.
baseline_loc_for() {
    local dir="$1"
    if [[ ! -f "$BASELINE_FILE" ]]; then
        return
    fi
    awk -v d="$dir" '$1 == "loc" && $2 == d { print $3 }' "$BASELINE_FILE"
}

# Read baseline file-set; emits sorted list of paths in the baseline.
baseline_files() {
    if [[ ! -f "$BASELINE_FILE" ]]; then
        return
    fi
    awk '$1 == "file" { print $2 }' "$BASELINE_FILE" | sort
}

# Read allowlist patterns; one path-glob per line, empty/# lines ignored.
allowlist_patterns() {
    if [[ ! -f "$ALLOWLIST_FILE" ]]; then
        return
    fi
    grep -vE '^\s*(#|$)' "$ALLOWLIST_FILE" || true
}

# Returns 0 if $1 (relative path) matches an allowlist pattern.
is_allowlisted() {
    local path="$1"
    local pat
    while IFS= read -r pat; do
        [[ -z "$pat" ]] && continue
        # shellcheck disable=SC2053
        if [[ "$path" == $pat ]]; then
            return 0
        fi
    done < <(allowlist_patterns)
    return 1
}

if [[ "$MODE" == "refresh" ]]; then
    echo "==> Refreshing baseline at $BASELINE_FILE"
    {
        echo "# Lane F persona-ts ratchet baseline — autogenerated by persona-ts-ratchet.sh refresh"
        echo "# Format:"
        echo "#   loc <dir>  <line-count>"
        echo "#   file <relative-path>"
        echo "# The ratchet fails if a watched dir's LOC exceeds its baseline OR a new file appears"
        echo "# that is neither in the baseline file-set nor matched by persona-ts-allowlist.txt."
        echo "# Refresh after legitimate TS deletion lands — the ratchet only moves down."
        echo "# Refreshed: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        for dir in "${WATCHED_DIRS[@]}"; do
            loc="$(dir_ts_loc "$dir")"
            echo "loc $dir $loc"
        done
        for dir in "${WATCHED_DIRS[@]}"; do
            while IFS= read -r f; do
                [[ -z "$f" ]] && continue
                echo "file $f"
            done < <(dir_ts_files "$dir")
        done
    } > "$BASELINE_FILE"
    total_loc=$(awk '$1 == "loc" { s += $3 } END { print s+0 }' "$BASELINE_FILE")
    total_files=$(awk '$1 == "file" { c++ } END { print c+0 }' "$BASELINE_FILE")
    echo "==> Baseline written: $total_files files, $total_loc LOC across ${#WATCHED_DIRS[@]} watched dirs."
    exit 0
fi

# check mode
if [[ ! -f "$BASELINE_FILE" ]]; then
    echo "ratchet: baseline file missing at $BASELINE_FILE" >&2
    echo "ratchet: run 'scripts/ratchet/persona-ts-ratchet.sh refresh' to create it." >&2
    exit 2
fi

violations=()

# (1) LOC ratchet — per dir.
for dir in "${WATCHED_DIRS[@]}"; do
    current="$(dir_ts_loc "$dir")"
    baseline="$(baseline_loc_for "$dir")"
    if [[ -z "$baseline" ]]; then
        # Dir wasn't in baseline (rare; baseline was refreshed before this dir was added).
        # Treat as zero so any non-zero current count fails loudly.
        baseline=0
    fi
    if (( current > baseline )); then
        violations+=("LOC grew in $dir: baseline=$baseline current=$current (delta=+$((current - baseline)))")
    fi
done

# (2) New-file ratchet — anything outside baseline AND outside allowlist.
current_files_tmp="$(mktemp)"
baseline_files_tmp="$(mktemp)"
trap 'rm -f "$current_files_tmp" "$baseline_files_tmp"' EXIT

for dir in "${WATCHED_DIRS[@]}"; do
    dir_ts_files "$dir" >> "$current_files_tmp"
done
sort -u "$current_files_tmp" -o "$current_files_tmp"

baseline_files > "$baseline_files_tmp"

new_files=$(comm -23 "$current_files_tmp" "$baseline_files_tmp")
if [[ -n "$new_files" ]]; then
    while IFS= read -r path; do
        [[ -z "$path" ]] && continue
        if ! is_allowlisted "$path"; then
            violations+=("NEW unallowed TS file: $path")
        fi
    done <<< "$new_files"
fi

if [[ ${#violations[@]} -eq 0 ]]; then
    total_loc=$(awk '$1 == "loc" { s += $3 } END { print s+0 }' "$BASELINE_FILE")
    echo "ratchet: OK — persona TS cognition stayed at or below baseline ($total_loc LOC across ${#WATCHED_DIRS[@]} dirs)."
    exit 0
fi

echo "==================================================" >&2
echo "Lane F TS-cognition ratchet FAILED" >&2
echo "==================================================" >&2
echo >&2
echo "The persona-cognition TypeScript layer must shrink, not grow." >&2
echo "Rust modules in core/continuum-core/src/ should be" >&2
echo "absorbing this work — see ALPHA-GAP-ANALYSIS.md Lane F + Lane D." >&2
echo >&2
echo "Violations:" >&2
for v in "${violations[@]}"; do
    echo "  - $v" >&2
done
echo >&2
echo "Options:" >&2
echo "  1. Move the new behavior into Rust (preferred — that's the lane)." >&2
echo "  2. If your file is a generated schema, ORM noun, or UI type," >&2
echo "     add a path-glob for it in scripts/ratchet/persona-ts-allowlist.txt." >&2
echo "  3. If you DELETED TS and the ratchet should tighten, run:" >&2
echo "     scripts/ratchet/persona-ts-ratchet.sh refresh" >&2
echo "     and commit the updated baseline." >&2
echo >&2
exit 1
