// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `contract:bid` — an executor's offer to take on a proposed contract.
 */
export type ContractBidPayload = { contractId: string, bidderId: string, 
/**
 * `number` per the `ContractProposedPayload::max_bid` note — JSON wire
 * carries a number, `bigint` breaks `JSON.stringify`, bids stay < 2^53.
 */
bidAmount: number, 
/**
 * Bidder's promised SLA (max latency in ms). Proposer uses this
 * in the bid-selection policy (lower latency + lower bid wins,
 * per the policy engine).
 */
maxLatencyMs: number, 
/**
 * Bidder's expiry — how long this bid is honored if accepted.
 * `number` per the `max_bid` note — Unix-ms timestamps stay below 2^53.
 */
bidExpiryUnixMs: number, };
