// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `contract:accepted` — proposer's signed selection of one bidder.
 */
export type ContractAcceptedPayload = { contractId: string, proposerId: string, acceptedBidderId: string, 
/**
 * Hash of the accepted bid envelope — pins exactly which bid was
 * taken (defense against bid-rewrite attacks where two bids share
 * a contract_id).
 */
acceptedBidHash: string, };
