// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvictableEntry } from "./EvictableEntry";

/**
 * Result of `gpu/eviction-candidates` — the evictable consumers, best-candidate
 * first. A named wrapper so the wire type is a struct, not a bare `Array<T>`.
 */
export type EvictionCandidates = { 
/**
 * Tracked consumers that may be evicted, sorted highest-score (best to evict)
 * first. Realtime consumers are excluded.
 */
candidates: Array<EvictableEntry>, };
