// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerStatus } from "./WorkerStatus";

/**
 * Ping result - basic health check
 */
export type PingResult = { uptimeMs: bigint, queueDepth: number, processedTotal: bigint, errorsTotal: bigint, memoryMb: number, status: WorkerStatus, };
