// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `vdd/report` — optional filters + the latest-only collapse.
 */
export type VddReportParams = { 
/**
 * Narrow to one commit's records.
 */
gitSha: string | null, 
/**
 * Narrow to one scenario.
 */
scenario: string | null, 
/**
 * Collapse duplicate `(git_sha, scenario)` rows to the latest per scenario —
 * the "most recent result per scenario" view PR-body snippets want.
 */
latestOnly: boolean, };
