#!/usr/bin/env tsx
/**
 * Worker Registry Generator
 *
 * Discovers all worker.config.ts files and generates:
 * 1. workers-config.json (for bash scripts)
 * 2. WorkerRegistry.ts (for TypeScript code)
 *
 * Run: npx tsx generator/generate-worker-registry.ts
 */

import * as fs from 'fs';
import * as path from 'path';

interface WorkerConfig {
  name: string;
  binary: string;
  socket: string;
  args?: string[];
  description: string;
  enabled?: boolean;
}

interface WorkersConfigJson {
  workers: WorkerConfig[];
  sharedSockets: string[];
}

async function discoverWorkerConfigs(): Promise<WorkerConfig[]> {
  const workersDir = path.join(__dirname, '../workers');
  const workerConfigs: WorkerConfig[] = [];

  if (!fs.existsSync(workersDir)) {
    console.error('❌ Workers directory not found:', workersDir);
    return [];
  }

  const entries = fs.readdirSync(workersDir, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const workerDir = path.join(workersDir, entry.name);
    const configPath = path.join(workerDir, 'worker.config.ts');

    if (fs.existsSync(configPath)) {
      try {
        // Import the worker config
        const configModule = await import(configPath);
        const config = configModule.default as WorkerConfig;

        workerConfigs.push(config);
        console.log(`✅ Discovered worker: ${config.name}`);
      } catch (error) {
        console.error(`⚠️  Failed to load config for ${entry.name}:`, error);
      }
    }
  }

  return workerConfigs;
}

function generateWorkersConfigJson(workers: WorkerConfig[]): WorkersConfigJson {
  return {
    workers,
    sharedSockets: [
      '/tmp/jtag-command-router.sock'
    ]
  };
}

function generateWorkerRegistryTs(workers: WorkerConfig[]): string {
  const imports = workers
    .map((w, i) => `import worker${i} from '../../workers/${w.name}/worker.config';`)
    .join('\n');

  const workersList = workers
    .map((w, i) => `  worker${i}`)
    .join(',\n');

  return `/**
 * Worker Registry - Auto-generated by generate-worker-registry.ts
 * DO NOT EDIT MANUALLY
 *
 * Generated: ${new Date().toISOString()}
 */

${imports}

export const WORKER_REGISTRY = [
${workersList}
] as const;

export type WorkerRegistry = typeof WORKER_REGISTRY;
`;
}

async function main() {
  console.log('🔧 Generating worker registry...\n');

  // Discover all worker configs
  const workers = await discoverWorkerConfigs();

  if (workers.length === 0) {
    console.log('⚠️  No workers found. Skipping generation.');
    return;
  }

  console.log(`\n📋 Found ${workers.length} workers\n`);

  // Generate workers-config.json for bash scripts
  const jsonConfig = generateWorkersConfigJson(workers);
  const jsonPath = path.join(__dirname, '../workers/workers-config.json');
  fs.writeFileSync(jsonPath, JSON.stringify(jsonConfig, null, 2) + '\n');
  console.log(`✅ Generated: ${jsonPath}`);

  // Generate WorkerRegistry.ts for TypeScript
  const tsRegistry = generateWorkerRegistryTs(workers);
  const tsPath = path.join(__dirname, '../shared/types/WorkerRegistry.ts');
  fs.mkdirSync(path.dirname(tsPath), { recursive: true });
  fs.writeFileSync(tsPath, tsRegistry);
  console.log(`✅ Generated: ${tsPath}`);

  console.log('\n🎉 Worker registry generation complete!');
}

main().catch(error => {
  console.error('❌ Generation failed:', error);
  process.exit(1);
});
