// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextGenerationResponse } from "../ai/TextGenerationResponse";

/**
 * One inference response from the remote peer back to the
 * requester. Correlation_id matches the request that produced it.
 */
export type RemoteInferenceResponse = { correlationId: string, 
/**
 * The peer's own peer_id (stringified). Lets the requester
 * confirm which peer actually served the request — useful when
 * the transport's peer-pick logic isn't deterministic.
 */
servedBy: string, 
/**
 * The peer's inference produced this. Local adapter trait
 * shape, fully populated. When the peer errored, this is
 * surfaced via `RemoteInferenceError` from the transport;
 * when the peer responded with a typed-but-failed result
 * (e.g. cloud rate limit), the error field on the response
 * carries it.
 */
textResponse: TextGenerationResponse, };
