// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Errors specific to the remote inference transport layer.
 * Distinct from `TextGenerationResponse.error` (which is the
 * model's own error) — these are transport / discovery /
 * correlation failures the substrate-as-transport detected.
 */
export type RemoteInferenceError = { "kind": "transport", message: string, } | { "kind": "no_peer_reachable", message: string, } | { "kind": "timeout", elapsed_ms: bigint, } | { "kind": "correlation_mismatch", expected: string, actual: string, } | { "kind": "peer_adapter_failed", message: string, } | { "kind": "policy_denied", reason: string, };
