// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageArtifact } from "../media/ImageArtifact";

export type VisionLookResult = { 
/**
 * What your eyes report about the image.
 */
description: string, 
/**
 * Which vision model looked (attribution for the receipt).
 */
model: string, 
/**
 * Original image retained independently of the description and prompt.
 */
artifact?: ImageArtifact, };
