// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageArtifact } from "../media/ImageArtifact";

export type VisionLookParams = { 
/**
 * Path to the image file to look at (png/jpg/gif/webp/bmp), as you would
 * pass it to code/read.
 */
file_path: string, 
/**
 * A retained capture reference, usable after its pixels leave the transcript.
 * Supply this OR file_path. Reads verify digest and byte length.
 */
artifact?: ImageArtifact, 
/**
 * Optional: what to focus on ("count the shapes", "read the chart title").
 * Omit for a general description.
 */
focus?: string, };
