// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `vision/cache-stats` — cache diagnostics.
 */
export type VisionCacheStatsResult = { entries: number, max_entries: number, hits: number, misses: number, hit_rate: number, evictions: number, };
