// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaId } from "../genome/PersonaId";
import type { FinishReason } from "./FinishReason";
import type { InferenceRequestId } from "./InferenceRequestId";

/**
 * Emitted when generation completes (any FinishReason). Carries
 * the full response + timing for observability + sentinel
 * attribution.
 */
export type InferenceComplete = { requestId: InferenceRequestId, persona: PersonaId, 
/**
 * Tokens emitted by the model. Raw-token engines populate
 * directly; adapter-based engines (PR-4) populate empty Vec
 * + the actual output goes in `completion_text` because the
 * adapter doesn't expose token-level output.
 */
completionTokens: Array<number>, 
/**
 * PR-4 addition: plain-text completion from adapter-based
 * engines (LlamaCppAdapter). `None` = raw-token path; the
 * caller decodes `completion_tokens` if it needs text.
 */
completionText?: string, finishReason: FinishReason, 
/**
 * Wall-clock duration from request receipt to last token.
 */
elapsedMs: number, 
/**
 * Number of tokens generated. Equals `completion_tokens.len()`
 * for raw-token engines; adapter-based engines populate from
 * the adapter's UsageMetrics.completion_tokens count.
 */
tokensGenerated: number, };
