// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageRef } from "../genome/PageRef";
import type { PersonaId } from "../genome/PersonaId";
import type { InferenceRequestId } from "./InferenceRequestId";

/**
 * Emitted when inference would have needed a page that isn't
 * resident in the persona's working set. The engine refuses
 * (per the no-CPU-fallback contract from #1341) rather than
 * silently demoting; sentinel learns from these to upgrade the
 * missing page's tier policy.
 *
 * The page reference identifies the missing artifact. Reason
 * explains why it wasn't resident (cold miss / evicted mid-turn
 * / never imported by foundry).
 */
export type ResidencyFault = { requestId: InferenceRequestId, persona: PersonaId, missingPage: PageRef, 
/**
 * Loud reason per Joel's never-swallow-errors rule. Examples:
 * "page evicted mid-turn by Bench LFU policy", "foundry
 * never imported MoE expert 3 of artifact X", "KV cache
 * chunk 4 not in working set."
 */
reason: string, };
