// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One eval task. Both the JSONL rows and inline `tasks` deserialize into this;
 * every field is optional so an authoring typo degrades to a benign empty rather
 * than failing the whole run. A task is TEST-GRADED when it carries `test`, else
 * substring-graded against `expect`.
 */
export type EvalTask = { 
/**
 * Stable id for the task (echoed in results so a regression is identifiable).
 */
id: string, 
/**
 * The prompt posed to the persona, framed as a room message.
 */
prompt: string, 
/**
 * Substring the answer must contain (case-insensitive) for descriptive tasks.
 * Ignored when `test` is present.
 */
expect: string, 
/**
 * A test program appended to her extracted code and RUN; pass = exit 0. When
 * present, this objective grade supersedes `expect`.
 */
test?: string, 
/**
 * Language of `test` (the gym grades `rust` only). Defaults to `rust`.
 */
lang?: string, };
