// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Look up one model by its catalog id.
 */
export type ModelsCapabilitiesParams = { 
/**
 * The catalog model id (e.g. `qwen2.5-omni-7b-instruct`), not a raw provider
 * artifact name.
 */
model_id: string, };
