// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `serving/pin` decided: the model now forced, what was serving before, and
 * the fit numbers it was gated on (so the caller sees the headroom, not just a
 * yes).
 */
export type PinReport = { 
/**
 * The model id now pinned — the daemon's next reconcile swaps the live
 * server to it.
 */
pinned_model: string, 
/**
 * What the host was serving at pin time (`None` if nothing was live). The
 * promote/demote "from".
 */
previous_model: string | null, 
/**
 * The host-fit served context window the planner will use for the pin.
 */
served_context_window: number, 
/**
 * The model's weight footprint, GB (what it needs).
 */
weights_gb: number, 
/**
 * The host's usable serving budget at pin time, GB (what it has).
 */
budget_gb: number, 
/**
 * Human-readable summary.
 */
detail: string, };
