// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hop in a verified lineage walk — an artifact's alloy hash and the signer that
 * vouched for it. A consumer's browse/trust surface renders these root-first.
 */
export type LineageHop = { alloy_hash: string, signer_pubkey_hex: string, };
