#!/usr/bin/env tsx
/**
 * Hello Command Integration Tests
 *
 * Tests Hello command with real client connections and system integration.
 * Follows middle-out Layer 4 (System Integration) testing methodology.
 *
 * Generated by: ./jtag generate
 * Run with: npx tsx commands/Hello/test/integration/HelloIntegration.test.ts
 *
 * PREREQUISITES:
 * - Server must be running: npm start
 * - Wait 90+ seconds for deployment to complete
 * - Browser client must be connected
 */

import {
  testClientConnection,
  testClientCommandExecution,
  validateConnectionResult,
  assertConnectionResult
} from '../../../test/utils/ClientTestUtils';

import {
  validateCommandResult,
  testCommandWithTimeout,
  assertCommandResult
} from '../../../test/utils/CommandTestUtils';

import type { HelloParams, HelloResult } from '../../shared/HelloTypes';

console.log('🧪 Hello Command Integration Tests');

function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(`❌ Assertion failed: ${message}`);
  }
  console.log(`✅ ${message}`);
}

/**
 * Test 1: Client connection for Hello testing
 */
async function testHelloClientConnection() {
  console.log('\n🔌 Test 1: Client connection for Hello testing');

  try {
    // Import the browser client (connects to existing server via WebSocket)
    const { jtag } = await import('../../../../browser-index');

    console.log('🔄 Connecting to JTAG system...');
    const client = await jtag.connect();

    // Validate connection
    const connectionInfo = client.getConnectionInfo();

    assert(connectionInfo.environment === 'browser', 'Connected via browser client');
    assert(!connectionInfo.isBootstrapSession, 'Session properly assigned (not bootstrap)');

    console.log(`📊 Connection Details:`);
    console.log(`   Environment: ${connectionInfo.environment}`);
    console.log(`   Connection Type: ${connectionInfo.connectionType}`);
    console.log(`   Session ID: ${connectionInfo.sessionId}`);

    return { client };

  } catch (error) {
    console.error('❌ Client connection failed:', error.message);
    throw error;
  }
}

/**
 * Test 2: Real Hello command execution
 */
async function testRealHelloExecution() {
  console.log('\n⚡ Test 2: Real Hello command execution');

  try {
    const { jtag } = await import('../../../../browser-index');
    const client = await jtag.connect();

    console.log('🚀 Executing Hello command...');

    // TODO: Test basic command execution
    // Example:
    // const { result: basicResult, executionTime: basicTime } = await testClientCommandExecution<HelloResult>(
    //   client,
    //   'Hello',
    //   { requiredParam: 'test-value' },
    //   5000
    // );
    //
    // assert(validateCommandResult(basicResult, ['yourResultField']), 'Basic Hello has correct structure');
    // assert(basicResult.success === true, 'Hello succeeded');
    // console.log(`   Hello execution: ${basicTime}ms`);

    console.log('⚠️  TODO: Add real command execution test for Hello');

  } catch (error) {
    console.error('❌ Real Hello execution failed:', error.message);
    throw error;
  }
}

/**
 * Test 3: Hello with missing required parameters
 *
 * CRITICAL: This test ensures the live system properly handles
 * ValidationError when required parameters are missing
 */
async function testHelloMissingParams() {
  console.log('\n🚨 Test 3: Hello with missing required parameters');

  try {
    const { jtag } = await import('../../../../browser-index');
    const client = await jtag.connect();

    console.log('🔍 Testing Hello without required parameters...');

    // TODO: Test missing required parameter throws ValidationError
    // Example:
    // try {
    //   await client.executeCommand('Hello', {});
    //   assert(false, 'Should have thrown ValidationError');
    // } catch (error) {
    //   assert(error.type === 'validation', 'Throws ValidationError');
    //   assert(error.message.includes('requiredParam'), 'Error mentions missing parameter');
    //   assert(error.message.includes('help tool'), 'Error message is tool-agnostic');
    //   console.log(`✅ ValidationError thrown correctly: ${error.message}`);
    // }

    console.log('⚠️  TODO: Add missing required params test for Hello');

  } catch (error) {
    console.error('❌ Missing params test failed:', error.message);
    throw error;
  }
}

/**
 * Test 4: Hello with optional parameters
 */
async function testHelloOptionalParams() {
  console.log('\n🔧 Test 4: Hello with optional parameters');

  try {
    const { jtag } = await import('../../../../browser-index');
    const client = await jtag.connect();

    // TODO: Test with optional parameters
    // Example:
    // const withOptional = await testClientCommandExecution<HelloResult>(
    //   client,
    //   'Hello',
    //   { requiredParam: 'test', optionalParam: true },
    //   5000
    // );
    //
    // assert(withOptional.result.success === true, 'Hello succeeds with optional params');

    // TODO: Test without optional parameters (should use defaults)
    // const withoutOptional = await testClientCommandExecution<HelloResult>(
    //   client,
    //   'Hello',
    //   { requiredParam: 'test' },
    //   5000
    // );
    //
    // assert(withoutOptional.result.success === true, 'Hello succeeds without optional params');

    console.log('⚠️  TODO: Add optional params test for Hello');

  } catch (error) {
    console.error('❌ Optional params test failed:', error.message);
    throw error;
  }
}

/**
 * Test 5: Hello performance under load
 */
async function testHelloPerformance() {
  console.log('\n⚡ Test 5: Hello performance under load');

  try {
    const { jtag } = await import('../../../../browser-index');
    const client = await jtag.connect();

    // TODO: Test command performance
    // Example:
    // const iterations = 10;
    // const executionTimes: number[] = [];
    //
    // for (let i = 0; i < iterations; i++) {
    //   const { executionTime } = await testClientCommandExecution<HelloResult>(
    //     client,
    //     'Hello',
    //     { requiredParam: `test-${i}` },
    //     5000
    //   );
    //   executionTimes.push(executionTime);
    // }
    //
    // const avgTime = executionTimes.reduce((a, b) => a + b, 0) / iterations;
    // const maxTime = Math.max(...executionTimes);
    //
    // console.log(`   Average execution time: ${avgTime.toFixed(2)}ms`);
    // console.log(`   Max execution time: ${maxTime}ms`);
    //
    // assert(avgTime < 500, `Average time ${avgTime.toFixed(2)}ms under 500ms`);
    // assert(maxTime < 1000, `Max time ${maxTime}ms under 1000ms`);

    console.log('⚠️  TODO: Add performance test for Hello');

  } catch (error) {
    console.error('❌ Performance test failed:', error.message);
    throw error;
  }
}

/**
 * Test 6: Hello with various parameter combinations
 */
async function testHelloParameterCombinations() {
  console.log('\n🧪 Test 6: Hello with various parameter combinations');

  try {
    const { jtag } = await import('../../../../browser-index');
    const client = await jtag.connect();

    // TODO: Test edge cases and parameter combinations
    // Example:
    // const testCases = [
    //   { requiredParam: 'a', optionalParam: true },
    //   { requiredParam: 'very-long-string-to-test-limits', optionalParam: false },
    //   { requiredParam: '123', optionalParam: true },
    // ];
    //
    // for (const params of testCases) {
    //   const { result } = await testClientCommandExecution<HelloResult>(
    //     client,
    //     'Hello',
    //     params,
    //     5000
    //   );
    //   assert(result.success === true, `Hello succeeds with params: ${JSON.stringify(params)}`);
    // }

    console.log('⚠️  TODO: Add parameter combination tests for Hello');

  } catch (error) {
    console.error('❌ Parameter combination test failed:', error.message);
    throw error;
  }
}

/**
 * Run all integration tests
 */
async function runAllHelloIntegrationTests() {
  console.log('🚀 Starting Hello Command Integration Tests\n');
  console.log('⚠️  PREREQUISITES:');
  console.log('   - Server running: npm start (wait 90+ seconds)');
  console.log('   - Browser client connected\n');

  try {
    await testHelloClientConnection();
    await testRealHelloExecution();
    await testHelloMissingParams();
    await testHelloOptionalParams();
    await testHelloPerformance();
    await testHelloParameterCombinations();

    console.log('\n🎉 ALL Hello INTEGRATION TESTS PASSED!');
    console.log('📋 Validated:');
    console.log('  ✅ Client connection to live system');
    console.log('  ✅ Real command execution via WebSocket');
    console.log('  ✅ ValidationError handling for missing params');
    console.log('  ✅ Optional parameter defaults');
    console.log('  ✅ Performance under load');
    console.log('  ✅ Various parameter combinations');

  } catch (error) {
    console.error('\n❌ Hello integration tests failed:', error.message);
    console.error('   Make sure server is running: npm start');
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  runAllHelloIntegrationTests();
} else {
  module.exports = { runAllHelloIntegrationTests };
}
