// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Hub repo hit, trimmed to what a foraging mind needs to choose: the id
 * (the handle to pull/import), the page url, popularity signals, task, and tags.
 */
export type HfHit = { 
/**
 * The repo id, "<owner>/<name>" — the handle for `models/pull` or dataset import.
 */
id: string, 
/**
 * The browsable Hub page for this repo.
 */
url: string, downloads: number, likes: number, 
/**
 * For a model, the pipeline/task tag (e.g. "text-generation"); None for a dataset.
 */
task?: string, 
/**
 * A few descriptive tags (trimmed) — language, task, and license hints.
 */
tags: Array<string>, };
