// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared params for both `hf/search-models` and `hf/search-datasets` — one search
 * contract, two faces (compression: the query shape is identical).
 */
export type HfSearchParams = { 
/**
 * Full-text query, matched against repo id, author, tags and description —
 * e.g. "qwen2.5 coder gguf", "medical dialogue", "function calling dataset".
 */
query: string, 
/**
 * Max results. Default 10, clamped to [1, 50] so the result stays small
 * enough to re-enter cognition as a memory.
 */
limit?: number, 
/**
 * Sort key: "downloads", "likes", "trending", "modified", "created". Omit to
 * let the Hub rank by search relevance.
 */
sort?: string, 
/**
 * Optional Hub filter tag to narrow results — e.g. "text-generation", "gguf",
 * "en", "conversational". Omit for an unfiltered search.
 */
filter?: string, };
