// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `data/create`.
 */
export type DataCreateParams = { 
/**
 * The collection to write to.
 */
collection: string, 
/**
 * Optional record id. A v4 UUID is minted when omitted.
 */
id?: string, 
/**
 * The record body (collection-specific shape).
 */
data: unknown, 
/**
 * Storage handle. Defaults to "main" (the shared DB). Power callers may pass
 * a specific store. Accepts the legacy `dbPath` field name as an alias.
 */
handle?: string, };
