// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderByClause } from "./OrderByClause";

/**
 * Params for `data/list` — read records from a collection.
 *
 * Persona/UI-facing contract: name the `collection` and (optionally) an
 * intuitive plain-JSON `filter`, ordering, and paging. There is deliberately
 * no database handle to reason about — the shared "main" store is the default.
 */
export type DataListParams = { 
/**
 * The collection to read (e.g. "rooms", "users", "messages").
 */
collection: string, 
/**
 * Optional field filter as plain JSON: `{"roomId": "general"}` for an
 * equality match, `{"age": {"$gt": 18}}` for an operator match.
 */
filter?: Record<string, unknown>, 
/**
 * Optional ordering clauses, applied in order.
 */
sort?: Array<OrderByClause>, 
/**
 * Max records to return. Omit for all matching (bounded by the store).
 */
limit?: number, 
/**
 * Records to skip before returning (paging alongside `limit`).
 */
offset?: number, 
/**
 * Storage handle. Defaults to "main" (the shared DB). Power callers may pass
 * "@persona:<slug>" or "@metrics" to target a specific store.
 *
 * WIRE NOTE: on the flat wire the `handle` key is CLAIMED by the
 * [`CommandRequest`](crate::runtime::CommandRequest) envelope (a kernel
 * `HandleRef`), so a string here never reaches these params under that
 * name — callers pass the storage handle as `dbPath` (the alias below),
 * same as `data/create`.
 */
handle?: string, };
