// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchOperation } from "../orm/BatchOperation";

/**
 * Params for `data/batch`.
 */
export type DataBatchParams = { 
/**
 * The operations to apply (each names its own collection + type).
 */
operations: Array<BatchOperation>, 
/**
 * Storage handle. Defaults to "main" (the shared DB). Accepts the legacy
 * `dbPath` field name as an alias.
 */
handle?: string, };
