// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `data/collection-stats`.
 */
export type DataCollectionStatsParams = { 
/**
 * The collection to describe.
 */
collection: string, 
/**
 * Storage handle. Defaults to "main" (the shared DB).
 */
dbPath?: string, };
