name: Validate AI Config

on:
  pull_request:
    paths:
      - 'schema/**'
      - 'templates/**'
      - 'examples/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install AJV CLI
      run: npm install -g ajv-cli
    
    - name: Validate AI Config Schema
      run: |
        # Validate the schema itself
        npx ajv-cli compile -s schema/ai-config.schema.json
        
        # Validate all template configs against the schema
        for template in templates/*/config.json; do
          echo "Validating $template"
          npx ajv-cli validate -s schema/ai-config.schema.json -d "$template"
        done
    
    - name: Validate Example Files
      run: |
        # Install example dependencies
        cd examples
        npm install
        
        # Debug info
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        
        # Ensure example scripts run correctly
        echo "Running visualize-config.js:"
        node --version
        
        # First try with the simple script that doesn't depend on yaml
        node visualize-config-simple.js AI_CONFIG.md
        
        # Then try with the full script if available
        node visualize-config.js AI_CONFIG.md || echo "Full visualization failed, but simple validation passed"