name: Validate AI Config

on:
  pull_request:
    paths:
      - 'schema/**'
      - 'templates/**'
      - 'examples/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install AJV CLI
      run: npm install -g ajv-cli
    
    - name: Validate AI Config Schema
      run: |
        # Validate the schema itself
        npx ajv-cli compile -s schema/ai-config.schema.json
        
        # Validate all template configs against the schema
        for template in templates/*/config.json; do
          echo "Validating $template"
          npx ajv-cli validate -s schema/ai-config.schema.json -d "$template"
        done
    
    - name: Validate Example Files
      run: |
        # Ensure example scripts run correctly
        cd examples
        node visualize-config.js AI_CONFIG.md