/**
 * CodingPlanEntity - Persistent coding plan with hierarchical team coordination
 *
 * First-class entity for the coding agent system. Tracks the full lifecycle:
 * - Draft: PlanFormulator generates initial plan
 * - Proposed: Plan submitted for team review
 * - Approved: Team accepted the plan (or auto-approved for single-agent)
 * - Executing: CodeAgentOrchestrator running steps
 * - Completed/Failed: Final outcome with file changes and errors
 *
 * Hierarchical: A lead creates a top-level plan, then delegates sub-plans
 * to team members via parentPlanId. Each sub-plan is scoped to a file cluster.
 *
 * Team-visible: All assigned AIs can view and propose modifications.
 * Governance: Plans can be proposed for review via DecisionProposal integration.
 */

import type { UUID } from '../../core/types/CrossPlatformUUID';
import {
  TextField,
  NumberField,
  JsonField,
  EnumField,
  CompositeIndex,
} from '../decorators/FieldDecorators';
import { BaseEntity } from './BaseEntity';
import { COLLECTIONS } from '../../shared/Constants';
import type { CodingAction } from '../../code/shared/CodingTypes';

// ────────────────────────────────────────────────────────────
// Plan status lifecycle
// ────────────────────────────────────────────────────────────

export type CodingPlanStatus =
  | 'draft'       // Generated by PlanFormulator, not yet reviewed
  | 'proposed'    // Submitted for team review (DecisionProposal)
  | 'approved'    // Team accepted (or auto-approved for solo tasks)
  | 'executing'   // CodeAgentOrchestrator actively running steps
  | 'completed'   // All steps succeeded
  | 'partial'     // Some steps completed, budget or dependencies prevented full completion
  | 'failed'      // Execution failed (plan formulation error, all steps failed, etc.)
  | 'cancelled';  // Manually cancelled before or during execution

// ────────────────────────────────────────────────────────────
// Step snapshot (persisted version of CodingStep + execution result)
// ────────────────────────────────────────────────────────────

export interface CodingStepSnapshot {
  stepNumber: number;
  action: CodingAction;
  description: string;
  targetFiles: string[];
  toolCall: string;
  toolParams: Record<string, unknown>;
  dependsOn: number[];
  verification: string;

  // Execution state (populated during/after execution)
  status: 'pending' | 'executing' | 'completed' | 'failed' | 'skipped';
  assigneeId?: string;       // Which AI is executing this step (for delegation)
  startedAt?: number;
  completedAt?: number;
  durationMs?: number;
  output?: unknown;
  error?: string;
  retryCount?: number;
}

// ────────────────────────────────────────────────────────────
// Plan generation metadata
// ────────────────────────────────────────────────────────────

export interface PlanGenerationInfo {
  provider: string;        // e.g. 'anthropic'
  model: string;           // e.g. 'claude-sonnet-4-5-20250929'
  temperature: number;
  durationMs: number;      // How long plan generation took
  inputTokens?: number;
  outputTokens?: number;
}

// ────────────────────────────────────────────────────────────
// Entity
// ────────────────────────────────────────────────────────────

@CompositeIndex({
  name: 'idx_coding_plans_persona_status',
  fields: ['createdById', 'status'],
  direction: 'DESC',
})
@CompositeIndex({
  name: 'idx_coding_plans_task',
  fields: ['taskId'],
  direction: 'DESC',
})
@CompositeIndex({
  name: 'idx_coding_plans_parent',
  fields: ['parentPlanId'],
  direction: 'DESC',
})
export class CodingPlanEntity extends BaseEntity {
  static readonly collection = COLLECTIONS.CODING_PLANS;

  // ── Identity ──────────────────────────────────────────────

  /** The coding task this plan addresses */
  @TextField({ index: true })
  taskId!: UUID;

  /** Parent plan ID (null for top-level plans, set for delegated sub-plans) */
  @TextField({ nullable: true, index: true })
  parentPlanId?: UUID;

  /** AI that created/formulated this plan */
  @TextField({ index: true })
  createdById!: UUID;

  /** Lead AI coordinating this plan (may differ from creator for delegated sub-plans) */
  @TextField({ index: true })
  leadId!: UUID;

  // ── Plan content ──────────────────────────────────────────

  /** Brief summary of the plan's approach */
  @TextField()
  summary!: string;

  /** Original task description that prompted this plan */
  @TextField()
  taskDescription!: string;

  /** Step DAG — the concrete execution plan */
  @JsonField()
  steps!: CodingStepSnapshot[];

  /** Estimated total tool calls for execution */
  @NumberField()
  estimatedToolCalls!: number;

  // ── Team ──────────────────────────────────────────────────

  /** AI persona IDs assigned to work on this plan */
  @JsonField()
  assignees!: UUID[];

  // ── Model info ────────────────────────────────────────────

  /** How the plan was generated */
  @JsonField()
  generatedBy!: PlanGenerationInfo;

  // ── Status & lifecycle ────────────────────────────────────

  @EnumField({ index: true })
  status!: CodingPlanStatus;

  /** When execution started (null if not yet executing) */
  @NumberField({ nullable: true })
  executionStartedAt?: number;

  /** When execution completed/failed (null if still running) */
  @NumberField({ nullable: true })
  executionCompletedAt?: number;

  // ── Execution results ─────────────────────────────────────

  /** Files modified during execution */
  @JsonField()
  filesModified!: string[];

  /** Files created during execution */
  @JsonField()
  filesCreated!: string[];

  /** Change IDs from code/write and code/edit operations (for undo) */
  @JsonField()
  changeIds!: string[];

  /** Errors encountered during execution */
  @JsonField()
  errors!: string[];

  /** Total tool calls consumed */
  @NumberField()
  totalToolCalls!: number;

  /** Total execution duration in milliseconds */
  @NumberField()
  totalDurationMs!: number;

  // ── Governance ────────────────────────────────────────────

  /** DecisionProposal ID if plan was proposed for team review */
  @TextField({ nullable: true })
  proposalId?: UUID;

  // ── Index signature ───────────────────────────────────────

  [key: string]: unknown;

  // ── Constructor ───────────────────────────────────────────

  constructor() {
    super();

    this.taskId = '' as UUID;
    this.createdById = '' as UUID;
    this.leadId = '' as UUID;
    this.summary = '';
    this.taskDescription = '';
    this.steps = [];
    this.estimatedToolCalls = 0;
    this.assignees = [];
    this.generatedBy = { provider: '', model: '', temperature: 0, durationMs: 0 };
    this.status = 'draft';
    this.filesModified = [];
    this.filesCreated = [];
    this.changeIds = [];
    this.errors = [];
    this.totalToolCalls = 0;
    this.totalDurationMs = 0;
  }

  // ── BaseEntity implementation ─────────────────────────────

  get collection(): string {
    return CodingPlanEntity.collection;
  }

  static override getPaginationConfig(): {
    defaultSortField: string;
    defaultSortDirection: 'asc' | 'desc';
    defaultPageSize: number;
    cursorField: string;
  } {
    return {
      defaultSortField: 'createdAt',
      defaultSortDirection: 'desc',
      defaultPageSize: 20,
      cursorField: 'createdAt',
    };
  }

  validate(): { success: boolean; error?: string } {
    if (!this.taskId?.trim()) {
      return { success: false, error: 'CodingPlan taskId is required' };
    }
    if (!this.createdById?.trim()) {
      return { success: false, error: 'CodingPlan createdById is required' };
    }
    if (!this.leadId?.trim()) {
      return { success: false, error: 'CodingPlan leadId is required' };
    }
    if (!this.summary?.trim()) {
      return { success: false, error: 'CodingPlan summary is required' };
    }
    if (!this.taskDescription?.trim()) {
      return { success: false, error: 'CodingPlan taskDescription is required' };
    }
    if (!Array.isArray(this.steps)) {
      return { success: false, error: 'CodingPlan steps must be an array' };
    }
    if (this.steps.length === 0) {
      return { success: false, error: 'CodingPlan must have at least one step' };
    }
    if (!Array.isArray(this.assignees)) {
      return { success: false, error: 'CodingPlan assignees must be an array' };
    }
    if (this.assignees.length === 0) {
      return { success: false, error: 'CodingPlan must have at least one assignee' };
    }

    const validStatuses: CodingPlanStatus[] = [
      'draft', 'proposed', 'approved', 'executing',
      'completed', 'partial', 'failed', 'cancelled',
    ];
    if (!validStatuses.includes(this.status)) {
      return { success: false, error: `CodingPlan status must be one of: ${validStatuses.join(', ')}` };
    }

    // Validate step structure
    for (const step of this.steps) {
      if (typeof step.stepNumber !== 'number' || step.stepNumber < 1) {
        return { success: false, error: `CodingPlan step has invalid stepNumber: ${step.stepNumber}` };
      }
      if (!step.action) {
        return { success: false, error: `CodingPlan step ${step.stepNumber} is missing action` };
      }
      if (!step.toolCall?.startsWith('code/')) {
        return { success: false, error: `CodingPlan step ${step.stepNumber} has invalid toolCall: ${step.toolCall}` };
      }
    }

    return { success: true };
  }

  // ── Convenience methods ───────────────────────────────────

  /** Whether this is a sub-plan delegated from a parent */
  get isDelegated(): boolean {
    return !!this.parentPlanId;
  }

  /** Number of steps completed */
  get stepsCompleted(): number {
    return this.steps.filter(s => s.status === 'completed').length;
  }

  /** Number of steps failed */
  get stepsFailed(): number {
    return this.steps.filter(s => s.status === 'failed').length;
  }

  /** Number of steps still pending or executing */
  get stepsRemaining(): number {
    return this.steps.filter(s => s.status === 'pending' || s.status === 'executing').length;
  }

  /** Progress as a fraction (0.0 - 1.0) */
  get progress(): number {
    if (this.steps.length === 0) return 0;
    return this.stepsCompleted / this.steps.length;
  }
}
