/**
 * Room Entity - Decorated ChatRoomData for field extraction
 *
 * Uses field decorators to define storage requirements for the serde-style adapter system
 * Replaces manual field mappings with elegant decorator-based schema definition
 */

import type { UUID } from '../../core/types/CrossPlatformUUID';

// Room-specific types moved here since domain files are deleted
export type RoomType = 'public' | 'private' | 'direct';
export type RoomStatus = 'active' | 'archived' | 'deleted';

export interface RoomPrivacy {
  isPublic: boolean;
  requiresInvite: boolean;
  allowGuestAccess: boolean;
  searchable: boolean;
}

export interface RoomSettings {
  allowThreads: boolean;
  allowReactions: boolean;
  allowFileSharing: boolean;
  messageRetentionDays: number;
  slowMode: number;
}

export interface RoomMember {
  userId: UUID;
  role: 'owner' | 'admin' | 'member';
  joinedAt: Date;
  lastReadAt?: Date;
}

import {
  PrimaryField,
  TextField,
  DateField,
  EnumField,
  JsonField,
  ForeignKeyField
} from '../decorators/FieldDecorators';
import { BaseEntity } from './BaseEntity';

/**
 * Decorated Room Entity - Storage-aware version of ChatRoomData
 *
 * The decorators define which fields get extracted to dedicated columns
 * vs stored as JSON blobs for optimal query performance
 */
export class RoomEntity extends BaseEntity {
  // Single source of truth for collection name - used by both decorators and commands
  static readonly collection = 'Room';

  @TextField({ index: true })
  name: string;

  @TextField()
  displayName: string;

  @TextField({ nullable: true })
  description?: string;

  @TextField({ nullable: true })
  topic?: string;

  @EnumField({ index: true })
  type: RoomType;

  @EnumField({ index: true })
  status: RoomStatus;

  @ForeignKeyField({ references: 'users.id', index: true })
  ownerId: UUID;

  @DateField({ index: true })
  lastMessageAt?: Date;

  // Complex objects stored as JSON blobs
  @JsonField()
  privacy: RoomPrivacy;

  @JsonField()
  settings: RoomSettings;

  @JsonField()
  members: readonly RoomMember[];

  @JsonField()
  tags: readonly string[];

  constructor() {
    super(); // Initialize BaseEntity fields (id, createdAt, updatedAt, version)

    // Default values - id autogenerated by BaseEntity
    this.name = '';
    this.displayName = '';
    this.type = 'public';
    this.status = 'active';
    this.ownerId = '' as UUID;
    this.privacy = { isPublic: true, requiresInvite: false, allowGuestAccess: false, searchable: true };
    this.settings = { allowThreads: true, allowReactions: true, allowFileSharing: true, messageRetentionDays: 365, slowMode: 0 };
    // Stats removed - will be a relationship/join query
    this.members = [];
    this.tags = [];
  }
}