/**
 * Command Names - SINGLE SOURCE OF TRUTH
 * 
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * ⚠️ Generated from command directory structure via generator/generate-command-constants.ts
 * ⚠️ Regenerate: npm run prebuild (or npm run build:ts)
 * 
 * **Usage:**
 * ```typescript
 * import { COMMANDS } from '@shared/generated-command-constants';
 * 
 * // Good:
 * await Commands.execute(COMMANDS.DATA_LIST, params);
 * if (command === COMMANDS.SESSION_CREATE) { ... }
 * 
 * // Bad (NEVER do this):
 * await Commands.execute('data/list', params); // ❌ Hardcoded string
 * if (command === 'session/create') { ... }  // ❌ Magic string
 * ```
 * 
 * **Exception:**
 * Only 'list' command may be hardcoded (bootstrap requirement before constants load)
 */

export const COMMANDS = {
  ADAPTER_ADOPT: 'adapter/adopt',
  ADAPTER_SEARCH: 'adapter/search',
  ADAPTER_TRY: 'adapter/try',
  AI_ADAPTER_TEST: 'ai/adapter/test',
  AI_BAG_OF_WORDS: 'ai/bag-of-words',
  AI_CONTEXT_SEARCH: 'ai/context/search',
  AI_CONTEXT_SLICE: 'ai/context/slice',
  AI_COST: 'ai/cost',
  AI_DATASET_CREATE: 'ai/dataset/create',
  AI_DATASET_LIST: 'ai/dataset/list',
  AI_DETECT_SEMANTIC_LOOP: 'ai/detect-semantic-loop',
  AI_EMBEDDING_GENERATE: 'ai/embedding/generate',
  AI_GENERATE: 'ai/generate',
  AI_GENOME_STATS: 'ai/genome/stats',
  AI_KEY_TEST: 'ai/key/test',
  AI_MODEL_FIND: 'ai/model/find',
  AI_MODEL_LIST: 'ai/model/list',
  AI_MUTE: 'ai/mute',
  AI_PROVIDERS_STATUS: 'ai/providers/status',
  AI_RAG_INDEX_CODEBASE: 'ai/rag/index-codebase',
  AI_RAG_INDEX_CREATE: 'ai/rag/index/create',
  AI_RAG_INSPECT: 'ai/rag/inspect',
  AI_RAG_QUERY_CLOSE: 'ai/rag/query-close',
  AI_RAG_QUERY_FETCH: 'ai/rag/query-fetch',
  AI_RAG_QUERY_OPEN: 'ai/rag/query-open',
  AI_REPORT: 'ai/report',
  AI_REPORT_DECISIONS: 'ai/report/decisions',
  AI_SHOULD_RESPOND: 'ai/should-respond',
  AI_SHOULD_RESPOND_FAST: 'ai/should-respond-fast',
  AI_SLEEP: 'ai/sleep',
  AI_STATUS: 'ai/status',
  AI_THOUGHTSTREAM: 'ai/thoughtstream',
  AI_VALIDATE_RESPONSE: 'ai/validate-response',
  CANVAS_STROKE_ADD: 'canvas/stroke/add',
  CANVAS_STROKE_LIST: 'canvas/stroke/list',
  CANVAS_VISION: 'canvas/vision',
  CODE_DIFF: 'code/diff',
  CODE_EDIT: 'code/edit',
  CODE_GIT: 'code/git',
  CODE_HISTORY: 'code/history',
  CODE_READ: 'code/read',
  CODE_SEARCH: 'code/search',
  CODE_SHELL_SENTINEL: 'code/shell/sentinel',
  CODE_SHELL_WATCH: 'code/shell/watch',
  CODE_TREE: 'code/tree',
  CODE_UNDO: 'code/undo',
  CODE_VERIFY: 'code/verify',
  CODE_WRITE: 'code/write',
  COLLABORATION_ACTIVITY_CREATE: 'collaboration/activity/create',
  COLLABORATION_ACTIVITY_GET: 'collaboration/activity/get',
  COLLABORATION_ACTIVITY_JOIN: 'collaboration/activity/join',
  COLLABORATION_ACTIVITY_LIST: 'collaboration/activity/list',
  COLLABORATION_ACTIVITY_UPDATE: 'collaboration/activity/update',
  COLLABORATION_ACTIVITY_USER_PRESENT: 'collaboration/activity/user-present',
  COLLABORATION_CHAT_ANALYZE: 'collaboration/chat/analyze',
  COLLABORATION_CHAT_EXPORT: 'collaboration/chat/export',
  COLLABORATION_CHAT_POLL: 'collaboration/chat/poll',
  COLLABORATION_CHAT_SEND: 'collaboration/chat/send',
  COLLABORATION_CONTENT_OPEN: 'collaboration/content/open',
  COLLABORATION_DECISION_CREATE: 'collaboration/decision/create',
  COLLABORATION_DECISION_FINALIZE: 'collaboration/decision/finalize',
  COLLABORATION_DECISION_LIST: 'collaboration/decision/list',
  COLLABORATION_DECISION_PROPOSE: 'collaboration/decision/propose',
  COLLABORATION_DECISION_RANK: 'collaboration/decision/rank',
  COLLABORATION_DECISION_VIEW: 'collaboration/decision/view',
  COLLABORATION_DECISION_VOTE: 'collaboration/decision/vote',
  COLLABORATION_DM: 'collaboration/dm',
  COLLABORATION_LIVE_JOIN: 'collaboration/live/join',
  COLLABORATION_LIVE_LEAVE: 'collaboration/live/leave',
  COLLABORATION_LIVE_START: 'collaboration/live/start',
  COLLABORATION_LIVE_TRANSCRIPTION: 'collaboration/live/transcription',
  COLLABORATION_WALL: 'collaboration/wall',
  COMMS_TEST: 'comms-test',
  CONTINUUM_EMOTION: 'continuum/emotion',
  CONTINUUM_SET: 'continuum/set',
  DATA: 'data',
  DATA_BACKFILL_VECTORS: 'data/backfill-vectors',
  DATA_CLEAR: 'data/clear',
  DATA_CLOSE: 'data/close',
  DATA_CREATE: 'data/create',
  DATA_DELETE: 'data/delete',
  DATA_GENERATE_EMBEDDING: 'data/generate-embedding',
  DATA_LIST: 'data/list',
  DATA_LIST_HANDLES: 'data/list-handles',
  DATA_OPEN: 'data/open',
  DATA_QUERY_CLOSE: 'data/query-close',
  DATA_QUERY_NEXT: 'data/query-next',
  DATA_QUERY_OPEN: 'data/query-open',
  DATA_READ: 'data/read',
  DATA_SCHEMA: 'data/schema',
  DATA_TRUNCATE: 'data/truncate',
  DATA_UPDATE: 'data/update',
  DATA_VECTOR_SEARCH: 'data/vector-search',
  DEVELOPMENT_BENCHMARK_VECTORS: 'development/benchmark-vectors',
  DEVELOPMENT_BUILD: 'development/build',
  DEVELOPMENT_COMPILE_TYPESCRIPT: 'development/compile-typescript',
  DEVELOPMENT_DEBUG_ARTIFACTS_CHECK: 'development/debug/artifacts-check',
  DEVELOPMENT_DEBUG_CHAT_SEND: 'development/debug/chat-send',
  DEVELOPMENT_DEBUG_CRUD_SYNC: 'development/debug/crud-sync',
  DEVELOPMENT_DEBUG_ERROR: 'development/debug/error',
  DEVELOPMENT_DEBUG_HTML_INSPECTOR: 'development/debug/html-inspector',
  DEVELOPMENT_DEBUG_SCROLL_TEST: 'development/debug/scroll-test',
  DEVELOPMENT_DEBUG_WIDGET_CSS: 'development/debug/widget-css',
  DEVELOPMENT_DEBUG_WIDGET_EVENTS: 'development/debug/widget-events',
  DEVELOPMENT_DEBUG_WIDGET_INTERACT: 'development/debug/widget-interact',
  DEVELOPMENT_DEBUG_WIDGET_STATE: 'development/debug/widget-state',
  DEVELOPMENT_EXEC: 'development/exec',
  DEVELOPMENT_GENERATE: 'development/generate',
  DEVELOPMENT_GENERATE_AUDIT: 'development/generate/audit',
  DEVELOPMENT_PROPOSE_COMMAND: 'development/propose-command',
  DEVELOPMENT_SANDBOX_EXECUTE: 'development/sandbox-execute',
  DEVELOPMENT_SCHEMA_GENERATE: 'development/schema/generate',
  DEVELOPMENT_SHELL_EXECUTE: 'development/shell/execute',
  DEVELOPMENT_TIMING: 'development/timing',
  FILE: 'file',
  FILE_APPEND: 'file/append',
  FILE_LOAD: 'file/load',
  FILE_MIME_TYPE: 'file/mime-type',
  FILE_SAVE: 'file/save',
  GENOME: 'genome',
  GENOME_BATCH_MICRO_TUNE: 'genome/batch-micro-tune',
  GENOME_JOB_CREATE: 'genome/job-create',
  GENOME_JOB_STATUS: 'genome/job-status',
  GENOME_PAGING_ACTIVATE: 'genome/paging-activate',
  GENOME_PAGING_ADAPTER_REGISTER: 'genome/paging-adapter-register',
  GENOME_PAGING_DEACTIVATE: 'genome/paging-deactivate',
  GENOME_PAGING_REGISTER: 'genome/paging-register',
  GENOME_PAGING_STATS: 'genome/paging-stats',
  GENOME_PAGING_UNREGISTER: 'genome/paging-unregister',
  HELP: 'help',
  INFERENCE_GENERATE: 'inference/generate',
  INTERFACE_CLICK: 'interface/click',
  INTERFACE_GET_TEXT: 'interface/get-text',
  INTERFACE_NAVIGATE: 'interface/navigate',
  INTERFACE_PROXY_NAVIGATE: 'interface/proxy-navigate',
  INTERFACE_SCREENSHOT: 'interface/screenshot',
  INTERFACE_SCROLL: 'interface/scroll',
  INTERFACE_TYPE: 'interface/type',
  INTERFACE_WAIT_FOR_ELEMENT: 'interface/wait-for-element',
  INTERFACE_WEB_FETCH: 'interface/web/fetch',
  INTERFACE_WEB_SEARCH: 'interface/web/search',
  LIST: 'list',
  LOGS_CONFIG: 'logs/config',
  LOGS_LIST: 'logs/list',
  LOGS_READ: 'logs/read',
  LOGS_SEARCH: 'logs/search',
  LOGS_STATS: 'logs/stats',
  MEDIA_PROCESS: 'media/process',
  MEDIA_RESIZE: 'media/resize',
  PERSONA_GENOME: 'persona/genome',
  PERSONA_LEARNING_CAPTURE_FEEDBACK: 'persona/learning/capture-feedback',
  PERSONA_LEARNING_CAPTURE_INTERACTION: 'persona/learning/capture-interaction',
  PERSONA_LEARNING_MULTI_AGENT_LEARN: 'persona/learning/multi-agent-learn',
  PERSONA_LEARNING_PATTERN_CAPTURE: 'persona/learning/pattern/capture',
  PERSONA_LEARNING_PATTERN_ENDORSE: 'persona/learning/pattern/endorse',
  PERSONA_LEARNING_PATTERN_QUERY: 'persona/learning/pattern/query',
  PING: 'ping',
  POSITRON_CURSOR: 'positron/cursor',
  PROCESS_REGISTRY: 'process-registry',
  RAG_BUDGET: 'rag/budget',
  RAG_LOAD: 'rag/load',
  SECURITY_SETUP: 'security/setup',
  SESSION_CREATE: 'session/create',
  SESSION_DESTROY: 'session/destroy',
  SESSION_GET_ID: 'session/get-id',
  SESSION_GET_USER: 'session/get-user',
  SKILL_ACTIVATE: 'skill/activate',
  SKILL_GENERATE: 'skill/generate',
  SKILL_LIST: 'skill/list',
  SKILL_PROPOSE: 'skill/propose',
  SKILL_VALIDATE: 'skill/validate',
  SOCIAL_BROWSE: 'social/browse',
  SOCIAL_CLASSIFY: 'social/classify',
  SOCIAL_COMMENT: 'social/comment',
  SOCIAL_COMMUNITY: 'social/community',
  SOCIAL_DOWNVOTE: 'social/downvote',
  SOCIAL_ENGAGE: 'social/engage',
  SOCIAL_FEED: 'social/feed',
  SOCIAL_NOTIFICATIONS: 'social/notifications',
  SOCIAL_POST: 'social/post',
  SOCIAL_PROFILE: 'social/profile',
  SOCIAL_PROPOSE: 'social/propose',
  SOCIAL_SEARCH: 'social/search',
  SOCIAL_SIGNUP: 'social/signup',
  SOCIAL_TRENDING: 'social/trending',
  STATE_CONTENT_CLOSE: 'state/content/close',
  STATE_CONTENT_SWITCH: 'state/content/switch',
  STATE_CREATE: 'state/create',
  STATE_GET: 'state/get',
  STATE_UPDATE: 'state/update',
  SYSTEM_DAEMONS: 'system/daemons',
  THEME: 'theme',
  THEME_GET: 'theme/get',
  THEME_LIST: 'theme/list',
  THEME_SET: 'theme/set',
  TRAINING_IMPORT: 'training/import',
  USER_CREATE: 'user/create',
  USER_GET_ME: 'user/get-me',
  UTILITIES_DOCS_LIST: 'utilities/docs/list',
  UTILITIES_DOCS_READ: 'utilities/docs/read',
  UTILITIES_DOCS_SEARCH: 'utilities/docs/search',
  UTILITIES_HELLO: 'utilities/hello',
  UTILITIES_LEASE_REQUEST: 'utilities/lease/request',
  UTILITIES_PIPE_CHAIN: 'utilities/pipe/chain',
  VOICE_START: 'voice/start',
  VOICE_STOP: 'voice/stop',
  VOICE_SYNTHESIZE: 'voice/synthesize',
  VOICE_TRANSCRIBE: 'voice/transcribe',
  WORKSPACE_GIT_COMMIT: 'workspace/git/commit',
  WORKSPACE_GIT_PUSH: 'workspace/git/push',
  WORKSPACE_GIT_STATUS: 'workspace/git/status',
  WORKSPACE_GIT_WORKSPACE_CLEAN: 'workspace/git/workspace/clean',
  WORKSPACE_GIT_WORKSPACE_INIT: 'workspace/git/workspace/init',
  WORKSPACE_RECIPE_LOAD: 'workspace/recipe/load',
  WORKSPACE_TASK_COMPLETE: 'workspace/task/complete',
  WORKSPACE_TASK_CREATE: 'workspace/task/create',
  WORKSPACE_TASK_LIST: 'workspace/task/list',
  WORKSPACE_TREE: 'workspace/tree',
} as const;

/** Type-safe command name type for autocomplete and type checking */
export type CommandName = typeof COMMANDS[keyof typeof COMMANDS];
