// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `chat/poll` — a chronologically-ordered list of message
 * records. The kernel-level wire response wraps this in
 * `CommandResponse<ChatPollResult>`, so callers see
 * `{ success, data: { messages, count }, error? }`.
 */
export type ChatPollResult = { 
/**
 * Messages returned by the poll, in chronological order
 * (earliest first) regardless of the underlying query direction.
 * Each entry is the raw `ChatMessageEntity` payload as stored by
 * the data module — no transformation, no field projection. TS
 * consumers cast it via the existing `ChatMessageEntity` type
 * (which itself is already ts-rs-exported from the entity layer).
 */
messages: Array<unknown>, 
/**
 * Number of messages in `messages`. Convenience field so callers
 * don't have to `.len()` on every consumer.
 */
count: number, 
/**
 * Echo of the `after_message_id` the caller passed in, for
 * pagination/loop ergonomics — the next poll round just keeps
 * passing the most-recently-seen id.
 */
afterMessageId?: string, 
/**
 * Echo of the `before_message_id` the caller passed in — the next
 * scroll-back page passes the OLDEST id it now holds. An empty
 * `messages` with this set means history is exhausted.
 */
beforeMessageId?: string, };
